-- Generated by build_product_categories.py — verified product-category taxonomy.
-- Idempotent: upsert on slug. Run AFTER migration 0070.
-- Customer-facing / market-factual only; no medical or effect claims.

insert into public.kb_product_categories
  (slug, name, group_key, summary, aliases, wa_inventory_types, sort_order, active)
values
  ('flower', 'Flower', 'flower', 'Dried, cured cannabis buds sold by weight for smoking or as an ingredient in other products.', '{"bud","eighth","nug"}', '{"Flower Lot","Marijuana Mix","Marijuana Mix Packaged"}', 0, true),
  ('pre-roll', 'Pre-Rolls', 'flower', 'Ready-to-smoke cannabis joints rolled from ground flower; may be single or multi-packs and can be infused.', '{"preroll","joint","pre roll","cone"}', '{"Marijuana Mix Infused"}', 1, true),
  ('wax', 'Wax', 'concentrate', 'A soft, opaque cannabis concentrate with a wax-like texture, made by extracting resin from flower.', '{"budder","crumble"}', '{"Hydrocarbon Wax"}', 2, true),
  ('shatter', 'Shatter', 'concentrate', 'A hard, glass-like cannabis concentrate that is brittle and translucent.', '{}', '{"Food Grade Solvent Extract"}', 3, true),
  ('live-resin', 'Live Resin', 'concentrate', 'A concentrate made from fresh-frozen cannabis to preserve a fuller terpene profile.', '{"resin"}', '{"Marijuana Extract for Inhalation"}', 4, true),
  ('rosin', 'Rosin', 'concentrate', 'A solventless concentrate pressed from flower or hash using heat and pressure.', '{"solventless"}', '{"Marijuana Extract for Inhalation"}', 5, true),
  ('co2-oil', 'CO2 Oil', 'concentrate', 'A cannabis oil extracted using pressurized carbon dioxide, commonly used in cartridges.', '{"co2","hash oil"}', '{"CO2 Hash Oil"}', 6, true),
  ('distillate', 'Distillate', 'concentrate', 'A highly refined cannabis oil produced by distillation, used in cartridges and edibles.', '{}', '{"Marijuana Extract for Inhalation"}', 7, true),
  ('kief', 'Kief', 'concentrate', 'The collected resin trichomes sifted from cannabis flower.', '{"dry sift"}', '{"Kief"}', 8, true),
  ('hash', 'Hash', 'concentrate', 'A traditional concentrate made by compressing cannabis resin.', '{"hashish"}', '{"Hash"}', 9, true),
  ('bubble-hash', 'Bubble Hash', 'concentrate', 'A solventless hash made using ice water and agitation to separate trichomes.', '{"ice water hash","water hash"}', '{"Bubble Hash"}', 10, true),
  ('vape-cartridge', 'Vape Cartridges', 'vape', 'Pre-filled cartridges of cannabis oil that attach to a battery for vaporizing.', '{"cart","cartridge","510"}', '{"Marijuana Extract for Inhalation","CO2 Hash Oil"}', 11, true),
  ('disposable-vape', 'Disposable Vapes', 'vape', 'All-in-one vaporizer pens pre-filled with cannabis oil and a built-in battery.', '{"disposable","all-in-one"}', '{"Marijuana Extract for Inhalation"}', 12, true),
  ('edible-gummies', 'Gummies', 'edible', 'Chewy cannabis-infused candies dosed per piece.', '{"gummy","chew"}', '{"Solid Marijuana Infused Edible"}', 13, true),
  ('edible-chocolate', 'Chocolates', 'edible', 'Cannabis-infused chocolate bars and confections dosed per serving.', '{"chocolate bar"}', '{"Solid Marijuana Infused Edible"}', 14, true),
  ('edible-candy', 'Candy', 'edible', 'Cannabis-infused hard candies, caramels, and other confections.', '{"hard candy","caramel"}', '{"Solid Marijuana Infused Edible"}', 15, true),
  ('edible-baked', 'Baked Goods', 'edible', 'Cannabis-infused cookies, brownies, and other baked treats.', '{"cookie","brownie","snack"}', '{"Solid Marijuana Infused Edible"}', 16, true),
  ('edible-drink', 'Beverages', 'edible', 'Ready-to-drink cannabis-infused beverages and drink mixes.', '{"drink","beverage","soda","seltzer"}', '{"Liquid Marijuana Infused Edible"}', 17, true),
  ('capsule', 'Capsules', 'edible', 'Cannabis-infused capsules or pills dosed per unit.', '{"pill","softgel"}', '{"Capsule"}', 18, true),
  ('tincture', 'Tinctures', 'liquid', 'Liquid cannabis extracts dosed with a dropper, taken orally.', '{"drops","sublingual"}', '{"Tincture","Liquid Marijuana Infused Edible"}', 19, true),
  ('infused-oil', 'Cooking Oils', 'liquid', 'Cannabis-infused cooking oils and butters used as ingredients.', '{"cooking oil","infused butter","ghee"}', '{"Infused Cooking Oil","Infused Dairy Butter or Fat in Solid Form"}', 20, true),
  ('topical', 'Topicals', 'topical', 'Cannabis-infused lotions, balms, and salves applied to the skin.', '{"lotion","balm","salve","cream"}', '{"Marijuana Infused Topicals"}', 21, true),
  ('topical-bath', 'Bath & Body', 'topical', 'Cannabis-infused bath soaks and body products.', '{"bath bomb","bath soak"}', '{"Marijuana Infused Topicals"}', 22, true),
  ('suppository', 'Suppositories', 'topical', 'Cannabis-infused suppositories.', '{}', '{"Suppository"}', 23, true)
on conflict (slug) do update set
  name = excluded.name,
  group_key = excluded.group_key,
  summary = excluded.summary,
  aliases = excluded.aliases,
  wa_inventory_types = excluded.wa_inventory_types,
  sort_order = excluded.sort_order,
  active = true;
