#!/usr/bin/env python3
"""
strains_extra.py — Expansion pass 2 for the verified strain KB.

Adds more cross-referenced strains on top of the original 101 in
build_strains.py. Same NO-GUESSING-ON-FACTS rule: type + lineage only when
corroborated (Leafly / Wikileaf / AllBud / Seedfinder / breeder-stated);
disputed lineage = None. Sensory/botanical only; no medical/effect claims.

LOOSENED NAME MATCHING (owner request): grower-to-grower spelling and numbering
variants are captured as `aliases` so the retrieval matcher recognizes them all
(e.g. Gorilla Glue #1/#4/GG4, Cherry/Cherries OG). NAMES ONLY — never facts.

build_strains.py SKIPS any EXTRA entry whose slug already exists in the original
STRAINS list (overlaps are harmless), and merges ALIAS_MERGES into existing
entries so name variants of already-listed strains still match.

Tuple order matches build_strains.py STRAINS:
(name, type, lineage|None, dom_terpene, aromas[], flavors[], terpenes[],
 dominant_cannabinoid, potency_note|None, bud_structure|None, origin|None,
 summary, aliases[], sources[], confidence)
"""

S = "sativa"
I = "indica"
H = "hybrid"

LEAFLY = "leafly"
WIKILEAF = "wikileaf"
ALLBUD = "allbud"
SEEDFINDER = "seedfinder"
BREEDER = "breeder-stated"

US = "United States"

# Aliases to MERGE into strains already present in the original 101 list, so
# grower-to-grower name variants resolve to the canonical entry. Keyed by
# canonical slug (lowercase strain name).
ALIAS_MERGES = {
    "og kush": ["og kush #18", "the og"],
    "granddaddy purple": ["gdp", "granddaddy purp", "grand daddy purple", "grandaddy purple", "grand daddy purp"],
    "ak-47": ["ak47", "ak 47"],
    "gsc": ["girl scout cookies", "girlscout cookies"],
    "original glue": ["gorilla glue #4", "gorilla glue 4", "gorilla glue #1", "gorilla glue 1", "gorrilla glue", "the glue"],
    "do-si-dos": ["do si dos", "dosidos", "dosi", "dosido"],
    "sour diesel": ["sour deezy"],
    "blue dream": ["bluedream", "blue dream haze", "azure haze"],
    "cherry pie": ["cherry pie kush", "cherrie pie", "cherry pye"],
    "green crack": ["green crush", "green cush", "mango crack"],
    "purple urkle": ["purple urkel", "urkle", "urkel"],
    "grape ape": ["grapeape", "grape ape kush"],
    "white widow": ["whitewidow"],
    "pineapple express": ["pineapple xpress"],
    "wedding cake": ["pink cookies", "triangle mints #23"],
    "runtz": ["runts", "runtz og"],
    "zkittlez": ["skittlez", "skittles", "zkittles", "the original z"],
    "northern lights": ["nl", "northern light", "northern lights #5"],
    "jack herer": ["the jack", "premium jack"],
    "fire og": ["fire og kush", "fire kush"],
    "sfv og": ["sfv og kush", "san fernando valley og", "sfv"],
    "mac": ["miracle alien cookies", "mac 1", "mac1", "mac #1"],
    "biscotti": ["biscotti cookies"],
    "ice cream cake": ["icecream cake", "ice cream cake #5"],
    "animal cookies": ["animal cookie"],
    "kush mints": ["kushmints", "kush mint"],
    "apple fritter": ["apple fritters"],
    "gushers": ["white gushers", "gusher", "fruit gushers"],
    "mimosa": ["mimosa evo"],
    "lemon tree": ["lemontree"],
    "master kush": ["masterkush"],
    "purple kush": ["purps kush"],
    "white rhino": ["whiterhino", "rhino"],
    "la confidential": ["la con"],
    "9 pound hammer": ["nine pound hammer"],
    "mendo breath": ["mendo breath og"],
    "cheese": ["uk cheese", "exodus cheese", "the cheese"],
    "lemon skunk": ["lemonskunk", "las vegas lemon skunk"],
    "strawberry banana": ["strawnana", "strawberry banana kush"],
    "super lemon haze": ["slh", "super lemon"],
    "super silver haze": ["ssh", "super silver"],
    "tangie": ["cali orange tangie"],
    "trainwreck": ["train wreck"],
    "chocolope": ["chocalope", "d-line"],
    "candyland": ["candy land"],
    "tropicana cookies": ["tropicana", "trop cookies", "tropicanna cookies"],
    "fruity pebbles": ["fpog", "fruity pebbles og", "fruity pebble"],
    "grape pie": ["grape pie kush"],
    "lava cake": ["lava cake kush"],
    "forbidden fruit": ["forbidden fruits"],
    "blueberry": ["blueberry kush", "dj short blueberry"],
    "gelato 41": ["gelato #41", "gelato41"],
    "bubba kush": ["pre-98 bubba kush", "bubba kush pre-98"],
}

EXTRA_STRAINS = [
    # Gorilla Glue sibling
    ("New Glue", H, "Gorilla Glue #4 phenotype", "caryophyllene",
     ["earthy", "diesel", "pine", "pungent"], ["earthy", "diesel", "pine"],
     ["caryophyllene", "limonene", "myrcene"], "thc", "typically very high THC", "dense", US,
     "A Gorilla Glue #4 selection (renamed for trademark reasons) with the same earthy, diesel-pine profile.",
     ["gg5", "gorilla glue #5", "glue 5"], [LEAFLY, SEEDFINDER], 0.82),

    # Cherry family
    ("Cherry OG", H, "Lost Coast OG x Cherry Thai x Afghani", "myrcene",
     ["cherry", "sweet", "earthy", "diesel"], ["cherry", "sweet", "earthy"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", US,
     "A sweet, cherry-forward hybrid with an earthy-diesel backbone; appears under several spelling variants.",
     ["cherries og", "cherry's og", "cherrys og", "cherries", "cherry og kush"], [LEAFLY, WIKILEAF], 0.85),
    ("Cherry AK", S, "Cherry x AK-47", "caryophyllene",
     ["cherry", "sweet", "skunky", "earthy"], ["cherry", "sweet", "skunk"],
     ["caryophyllene", "myrcene", "limonene"], "thc", "typically high THC", "dense", US,
     "A cherry-sweet, skunky sativa-leaning cross of Cherry and AK-47.",
     ["cherry ak-47", "cherry ak47"], [LEAFLY, SEEDFINDER], 0.8),

    # Blue / Blueberry family
    ("Blueberry Muffin", H, "Blueberry x Purple Panty Dropper", "myrcene",
     ["blueberry", "muffin", "sweet", "baked"], ["blueberry", "sweet", "creamy"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", US,
     "A dessert hybrid that smells like fresh blueberry muffins, sweet and baked.",
     ["blueberry muffins"], [LEAFLY, SEEDFINDER], 0.82),
    ("Blue Cheese", I, "Blueberry x UK Cheese", "myrcene",
     ["blueberry", "cheese", "funky", "sweet"], ["blueberry", "cheese", "savory"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", "United Kingdom",
     "A savory-sweet indica marrying Blueberry's berry notes with UK Cheese funk.",
     ["bluecheese", "blue cheese kush"], [LEAFLY, WIKILEAF], 0.88),
    ("Blueberry Headband", H, "Blueberry x Headband", "myrcene",
     ["blueberry", "diesel", "sweet", "earthy"], ["blueberry", "diesel", "sweet"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", US,
     "A cross pairing sweet blueberry with the lemon-diesel of Headband.",
     [], [LEAFLY, SEEDFINDER], 0.8),
    ("Berry White", I, "Blueberry x White Widow", "myrcene",
     ["berry", "sweet", "earthy", "floral"], ["berry", "sweet", "earthy"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "frosty", US,
     "A frosty indica crossing Blueberry and White Widow for sweet berry and earthy notes.",
     [], [LEAFLY, WIKILEAF], 0.82),

    # Cookies / Gelato / dessert family
    ("Thin Mint GSC", H, "Girl Scout Cookies phenotype", "caryophyllene",
     ["mint", "sweet", "earthy", "cookie"], ["mint", "sweet", "earthy"],
     ["caryophyllene", "limonene", "humulene"], "thc", "typically high THC", "dense", US,
     "A minty, cookie-sweet GSC phenotype with frosty coverage.",
     ["thin mints", "thin mint cookies", "gsc thin mint"], [LEAFLY, WIKILEAF], 0.85),
    ("Platinum GSC", H, "Girl Scout Cookies phenotype", "caryophyllene",
     ["sweet", "earthy", "spice", "berry"], ["sweet", "earthy", "spice"],
     ["caryophyllene", "limonene", "humulene"], "thc", "typically high THC", "frosty", US,
     "A frosty, platinum-hued GSC phenotype with sweet, earthy, spicy notes.",
     ["platinum cookies", "platinum girl scout cookies"], [LEAFLY, ALLBUD], 0.82),
    ("Sunset Sherbet", H, "Girl Scout Cookies x Pink Panties", "caryophyllene",
     ["sweet", "berry", "citrus", "creamy"], ["sweet", "berry", "creamy"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "A creamy, fruity GSC descendant with sweet berry and citrus notes; parent of Gelato.",
     ["sherbet", "sherbert", "sunset sherbert"], [LEAFLY, WIKILEAF], 0.88),
    ("Gelato 33", H, "Sunset Sherbet x Thin Mint GSC", "caryophyllene",
     ["sweet", "creamy", "citrus", "berry"], ["sweet", "creamy", "berry"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "The famous Gelato #33 cut: dessert-sweet and creamy with citrus and berry.",
     ["gelato #33", "gelato33", "larry bird", "gelato 33 larry bird"], [LEAFLY, WIKILEAF], 0.88),
    ("Mochi", H, "Sunset Sherbet x Thin Mint GSC", "caryophyllene",
     ["sweet", "mint", "fruity", "creamy"], ["sweet", "mint", "creamy"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "A Gelato-family cut (a.k.a. Mochi Gelato / Gelato 47) with sweet mint and fruit.",
     ["mochi gelato", "gelato 47", "gelato #47"], [LEAFLY, SEEDFINDER], 0.8),
    ("Wedding Crasher", H, "Wedding Cake x Purple Punch", "caryophyllene",
     ["grape", "sweet", "vanilla", "earthy"], ["grape", "sweet", "vanilla"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "A sweet, grape-and-vanilla hybrid pairing Wedding Cake with Purple Punch.",
     [], [LEAFLY, WIKILEAF], 0.85),
    ("Cereal Milk", H, "Y Life (GSC x Cherry Pie) x Snowman", "limonene",
     ["sweet", "creamy", "fruity", "milky"], ["sweet", "creamy", "fruity"],
     ["limonene", "caryophyllene", "linalool"], "thc", "typically high THC", "dense", US,
     "A creamy, sweet Cookies-family cut reminiscent of sugary cereal milk.",
     ["cereal milk cookies"], [LEAFLY, SEEDFINDER], 0.8),
    ("Jealousy", H, "Gelato 41 x Sherbet Bx1", "caryophyllene",
     ["sweet", "creamy", "fruity", "earthy"], ["sweet", "creamy", "fruity"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically very high THC", "dense", US,
     "A sweet, creamy, fruity modern Cookies/Gelato cut with a gassy finish.",
     [], [LEAFLY, SEEDFINDER], 0.8),
    ("Animal Mints", H, "Animal Cookies x SinMint Cookies", "caryophyllene",
     ["mint", "cookie", "earthy", "sweet"], ["mint", "cookie", "earthy"],
     ["caryophyllene", "limonene", "humulene"], "thc", "typically very high THC", "frosty", US,
     "A minty, cookie-sweet hybrid with dense, frosty buds.",
     ["animal mint"], [LEAFLY, SEEDFINDER], 0.82),

    # Runtz / candy family
    ("White Runtz", H, "Gelato x Zkittlez", "limonene",
     ["sweet", "candy", "fruity", "creamy"], ["sweet", "candy", "fruity"],
     ["limonene", "caryophyllene", "linalool"], "thc", "typically very high THC", "frosty", US,
     "A frosty, candy-sweet Runtz phenotype with fruity, creamy notes.",
     ["white runts"], [LEAFLY, WIKILEAF], 0.82),
    ("Pink Runtz", H, "Runtz phenotype", "limonene",
     ["sweet", "candy", "fruity", "berry"], ["sweet", "candy", "berry"],
     ["limonene", "caryophyllene", "linalool"], "thc", "typically high THC", "dense", US,
     "A candy-sweet, fruity-berry Runtz phenotype.",
     ["pink runts"], [LEAFLY, SEEDFINDER], 0.8),
    ("Lemon Cherry Gelato", H, "Sunset Sherbet x GSC x undisclosed", "limonene",
     ["lemon", "cherry", "sweet", "creamy"], ["lemon", "cherry", "creamy"],
     ["limonene", "caryophyllene", "linalool"], "thc", "typically very high THC", "dense", US,
     "A citrus-and-cherry Gelato-family cut with creamy sweetness; lineage partly undisclosed.",
     ["lcg", "lemon cherry", "lemon cherry gelato 41"], [LEAFLY, SEEDFINDER], 0.78),

    # Purple family
    ("Mendocino Purps", I, "California cut (clone-only)", "myrcene",
     ["grape", "earthy", "sweet", "coffee"], ["grape", "earthy", "sweet"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", "California, United States",
     "A foundational purple cut behind many West Coast grape strains.",
     ["mendo purps", "the purps"], [LEAFLY, SEEDFINDER], 0.8),

    # Haze / sativa family
    ("Amnesia Haze", S, "Haze x Afghani/Hawaiian lineage", "terpinolene",
     ["citrus", "lemon", "earthy", "spicy"], ["citrus", "lemon", "earthy"],
     ["terpinolene", "limonene", "caryophyllene"], "thc", "typically high THC", "fluffy", "Netherlands",
     "A bright, citrus-lemon haze with earthy spice; a coffeeshop classic.",
     ["amnesia"], [LEAFLY, WIKILEAF], 0.85),
    ("Cinex", S, "Cinderella 99 x Vortex", "terpinolene",
     ["citrus", "floral", "sweet", "earthy"], ["citrus", "floral", "sweet"],
     ["terpinolene", "limonene", "ocimene"], "thc", "typically high THC", "dense", US,
     "A bright citrus-floral sativa crossing Cinderella 99 and Vortex.",
     ["cinex sativa"], [LEAFLY, SEEDFINDER], 0.8),
    ("Cinderella 99", S, "Jack Herer x Shiva Skunk", "limonene",
     ["pineapple", "citrus", "sweet", "tropical"], ["pineapple", "citrus", "sweet"],
     ["limonene", "caryophyllene", "ocimene"], "thc", "typically high THC", "dense", US,
     "A tropical, pineapple-citrus sativa (a.k.a. Cindy 99 / C99).",
     ["cindy 99", "c99", "cinderella", "cindy"], [LEAFLY, WIKILEAF], 0.82),
    ("Agent Orange", H, "Orange Velvet x Jack the Ripper", "terpinolene",
     ["orange", "citrus", "sweet", "earthy"], ["orange", "citrus", "sweet"],
     ["terpinolene", "limonene", "myrcene"], "thc", "typically high THC", "dense", US,
     "A citrus-orange hybrid with sweet and earthy notes.",
     [], [LEAFLY, SEEDFINDER], 0.8),
    ("Ghost Train Haze", S, "Ghost OG x Neville's Wreck", "terpinolene",
     ["citrus", "floral", "pine", "sour"], ["citrus", "floral", "sour"],
     ["terpinolene", "limonene", "caryophyllene"], "thc", "typically very high THC", "frosty", US,
     "A potent citrus-floral haze with sour-pine notes and heavy resin.",
     ["gth", "ghost train"], [LEAFLY, WIKILEAF], 0.82),

    # Tropical / fruit family
    ("Mango Kush", I, "Mango x Hindu Kush", "myrcene",
     ["mango", "tropical", "sweet", "earthy"], ["mango", "tropical", "sweet"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", US,
     "A tropical indica with sweet mango over an earthy-kush base.",
     ["mango kush indica"], [LEAFLY, WIKILEAF], 0.82),
    ("Papaya", I, "Citral #13 x Ice #2", "myrcene",
     ["papaya", "tropical", "sweet", "mango"], ["papaya", "tropical", "sweet"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", US,
     "A tropical indica with sweet papaya and mango notes.",
     ["papaya kush", "wifi papaya"], [LEAFLY, SEEDFINDER], 0.8),
    ("Clementine", S, "Tangie x Lemon Skunk", "terpinolene",
     ["orange", "citrus", "sweet", "earthy"], ["orange", "citrus", "sweet"],
     ["terpinolene", "limonene", "myrcene"], "thc", "typically high THC", "dense", US,
     "A bright orange-citrus sativa with sweet, earthy undertones.",
     [], [LEAFLY, WIKILEAF], 0.82),
    ("Orange Cookies", H, "Orange Juice x Girl Scout Cookies", "limonene",
     ["orange", "citrus", "sweet", "cookie"], ["orange", "citrus", "sweet"],
     ["limonene", "caryophyllene", "humulene"], "thc", "typically high THC", "dense", US,
     "A sweet orange-citrus Cookies cross.",
     [], [LEAFLY, SEEDFINDER], 0.8),
    ("Pineapple Chunk", I, "Pineapple x Skunk #1 x Cheese", "myrcene",
     ["pineapple", "cheese", "earthy", "sweet"], ["pineapple", "cheese", "earthy"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", US,
     "A pineapple-and-cheese indica with an earthy backbone.",
     [], [LEAFLY, SEEDFINDER], 0.78),

    # OG / Kush / gas family
    ("Tahoe OG", H, "OG Kush phenotype", "myrcene",
     ["lemon", "earthy", "pine", "fuel"], ["lemon", "earthy", "fuel"],
     ["myrcene", "limonene", "caryophyllene"], "thc", "typically high THC", "dense", "California, United States",
     "A heavy OG Kush cut with lemon, earthy-pine, and fuel notes.",
     ["tahoe og kush"], [LEAFLY, WIKILEAF], 0.82),
    ("Ghost OG", H, "OG Kush phenotype", "limonene",
     ["lemon", "pine", "earthy", "fuel"], ["lemon", "pine", "earthy"],
     ["limonene", "myrcene", "caryophyllene"], "thc", "typically high THC", "dense", US,
     "A bright, lemony OG Kush cut behind Ghost Train Haze.",
     [], [LEAFLY, SEEDFINDER], 0.8),
    ("Skywalker OG", I, "Skywalker x OG Kush", "myrcene",
     ["earthy", "pine", "fuel", "spicy"], ["earthy", "pine", "fuel"],
     ["myrcene", "limonene", "caryophyllene"], "thc", "typically very high THC", "dense", US,
     "A heavy, earthy-fuel OG indica with peppery spice.",
     ["skywalker og kush"], [LEAFLY, WIKILEAF], 0.85),
    ("Death Star", I, "Sensi Star x Sour Diesel", "caryophyllene",
     ["diesel", "earthy", "skunky", "sweet"], ["diesel", "earthy", "sweet"],
     ["caryophyllene", "myrcene", "limonene"], "thc", "typically high THC", "dense", "Ohio, United States",
     "A diesel-and-earth indica crossing Sensi Star with Sour Diesel.",
     ["deathstar"], [LEAFLY, WIKILEAF], 0.82),
    ("Cookies and Cream", H, "Starfighter x GSC phenotype", "caryophyllene",
     ["sweet", "vanilla", "nutty", "earthy"], ["vanilla", "sweet", "nutty"],
     ["caryophyllene", "limonene", "humulene"], "thc", "typically high THC", "dense", US,
     "A sweet, vanilla-and-nutty Cookies hybrid.",
     ["cookies n cream", "cookies & cream"], [LEAFLY, WIKILEAF], 0.82),
    ("Banana OG", I, "Banana x OG Kush", "limonene",
     ["banana", "sweet", "earthy", "tropical"], ["banana", "sweet", "earthy"],
     ["limonene", "myrcene", "caryophyllene"], "thc", "typically very high THC", "dense", US,
     "A sweet banana-and-earth OG indica.",
     [], [LEAFLY, WIKILEAF], 0.8),

    # Diesel / chem / gas family
    ("NYC Diesel", S, "Mexican x Afghani (Soma cut)", "myrcene",
     ["diesel", "lime", "grapefruit", "earthy"], ["diesel", "grapefruit", "lime"],
     ["myrcene", "limonene", "caryophyllene"], "thc", "typically high THC", "dense", "New York, United States",
     "A citrus-forward diesel sativa with grapefruit and lime over a fuel base.",
     ["nyc d", "new york city diesel", "nyc sour diesel"], [LEAFLY, WIKILEAF], 0.82),
    ("Chemdawg 91", H, "Chemdog phenotype", "caryophyllene",
     ["diesel", "pungent", "earthy", "pine"], ["diesel", "earthy", "pine"],
     ["caryophyllene", "myrcene", "limonene"], "thc", "typically very high THC", "dense", US,
     "A loud, diesel Chemdog cut (a.k.a. Chem 91).",
     ["chem 91", "chemdog 91", "chemdawg 91"], [LEAFLY, SEEDFINDER], 0.8),
    ("Jet Fuel", S, "Aspen OG x High Country Diesel", "caryophyllene",
     ["diesel", "pungent", "earthy", "sweet"], ["diesel", "earthy", "sweet"],
     ["caryophyllene", "myrcene", "limonene"], "thc", "typically high THC", "dense", US,
     "A gassy, diesel-forward sativa (a.k.a. G6).",
     ["g6", "jet fuel g6"], [LEAFLY, WIKILEAF], 0.8),

    # Skunk family
    ("Skunk #1", H, "Afghani x Acapulco Gold x Colombian Gold", "myrcene",
     ["skunky", "earthy", "sweet", "pungent"], ["skunk", "earthy", "sweet"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", "Netherlands",
     "The foundational Skunk hybrid behind countless modern strains.",
     ["skunk no 1", "skunk 1", "skunk one"], [LEAFLY, WIKILEAF], 0.85),

    # Jack / spicy family
    ("Jack the Ripper", S, "Jack's Cleaner x Space Queen", "terpinolene",
     ["lemon", "citrus", "spicy", "earthy"], ["lemon", "citrus", "spice"],
     ["terpinolene", "limonene", "ocimene"], "thc", "typically high THC", "dense", US,
     "A lemony, spicy sativa from TGA with bright citrus.",
     ["jtr"], [LEAFLY, SEEDFINDER], 0.8),
    ("Jack Flash", S, "Jack Herer x Super Skunk x Haze", "terpinolene",
     ["citrus", "spicy", "earthy", "sweet"], ["citrus", "spice", "earthy"],
     ["terpinolene", "myrcene", "caryophyllene"], "thc", "typically high THC", "fluffy", "Netherlands",
     "A spicy-citrus sativa in the Jack Herer family.",
     ["jack flash sativa"], [LEAFLY, SEEDFINDER], 0.78),

    # Wedding / cake / modern hybrid family
    ("Wedding Pie", H, "Wedding Cake x Grape Pie", "caryophyllene",
     ["grape", "sweet", "earthy", "spice"], ["grape", "sweet", "earthy"],
     ["caryophyllene", "limonene", "myrcene"], "thc", "typically high THC", "dense", US,
     "A grape-sweet, earthy hybrid pairing Wedding Cake with Grape Pie.",
     [], [LEAFLY, SEEDFINDER], 0.78),
    ("Birthday Cake", H, "GSC x Cherry Pie", "caryophyllene",
     ["sweet", "vanilla", "cookie", "earthy"], ["vanilla", "sweet", "cookie"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "A sweet vanilla-cake Cookies cross (a.k.a. Birthday Cake Kush).",
     ["birthday cake kush", "bday cake"], [LEAFLY, WIKILEAF], 0.8),
    ("London Pound Cake", I, "Sunset Sherbet x undisclosed", "caryophyllene",
     ["berry", "grape", "sweet", "citrus"], ["berry", "grape", "sweet"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "A berry-and-grape Cookies cut with sweet citrus; partial undisclosed lineage.",
     ["london pound cake 75", "lpc"], [LEAFLY, SEEDFINDER], 0.76),
    ("Oreoz", H, "Cookies and Cream x Secret Weapon", "caryophyllene",
     ["chocolate", "diesel", "sweet", "earthy"], ["chocolate", "diesel", "sweet"],
     ["caryophyllene", "limonene", "humulene"], "thc", "typically very high THC", "frosty", US,
     "A chocolate-and-diesel hybrid with heavy frost (a.k.a. Oreo Cookies).",
     ["oreo cookies", "oreoz cookies", "oreos"], [LEAFLY, SEEDFINDER], 0.8),

    # Sundae / dessert family
    ("Sundae Driver", H, "Fruity Pebbles OG x Grape Pie", "caryophyllene",
     ["sweet", "creamy", "grape", "chocolate"], ["sweet", "creamy", "grape"],
     ["caryophyllene", "limonene", "linalool"], "thc", "typically high THC", "dense", US,
     "A creamy, grape-and-chocolate dessert hybrid.",
     ["sunday driver"], [LEAFLY, WIKILEAF], 0.82),

    # Heavy indica family
    ("Critical Kush", I, "Critical Mass x OG Kush", "myrcene",
     ["earthy", "spicy", "sweet", "pine"], ["earthy", "spice", "sweet"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", "Netherlands",
     "An earthy-spicy kush indica with heavy, dense buds.",
     ["critical kush indica"], [LEAFLY, SEEDFINDER], 0.8),
    ("God's Gift", I, "Granddaddy Purple x OG Kush", "myrcene",
     ["grape", "berry", "citrus", "earthy"], ["grape", "berry", "citrus"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", "California, United States",
     "A grape-and-berry indica with citrus over an earthy base.",
     ["gods gift"], [LEAFLY, WIKILEAF], 0.82),
    ("Bubble Gum", H, "Indiana Bubblegum lineage", "myrcene",
     ["bubblegum", "sweet", "berry", "fruity"], ["bubblegum", "sweet", "berry"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", "Indiana, United States",
     "A sweet, true-to-name bubblegum hybrid.",
     ["bubblegum", "bubba gum", "indiana bubblegum"], [LEAFLY, WIKILEAF], 0.8),

    # OG cuts / collab family
    ("Larry OG", H, "OG Kush phenotype (Orange County)", "limonene",
     ["lemon", "citrus", "pine", "earthy"], ["lemon", "citrus", "pine"],
     ["limonene", "myrcene", "caryophyllene"], "thc", "typically high THC", "dense", "California, United States",
     "A bright, lemon-citrus OG cut (a.k.a. Lemon Larry OG).",
     ["lemon larry", "lemon larry og", "larry og kush"], [LEAFLY, WIKILEAF], 0.8),
    ("Gary Payton", H, "The Y x Snowman", "caryophyllene",
     ["earthy", "diesel", "sweet", "herbal"], ["earthy", "diesel", "sweet"],
     ["caryophyllene", "limonene", "humulene"], "thc", "typically very high THC", "frosty", US,
     "A Cookies-collab hybrid with earthy-diesel and sweet-herbal notes.",
     ["gp", "gary payton cookies"], [LEAFLY, SEEDFINDER], 0.78),

    # Additional well-documented classics
    ("Sour OG", H, "Sour Diesel x OG Kush", "caryophyllene",
     ["diesel", "lemon", "earthy", "pine"], ["diesel", "lemon", "earthy"],
     ["caryophyllene", "limonene", "myrcene"], "thc", "typically high THC", "dense", US,
     "A diesel-and-lemon hybrid pairing Sour Diesel with OG Kush.",
     ["sour og kush"], [LEAFLY, SEEDFINDER], 0.8),
    ("Tangerine Dream", H, "G13 x Afghani x Neville's Haze", "limonene",
     ["tangerine", "citrus", "sweet", "earthy"], ["tangerine", "citrus", "sweet"],
     ["limonene", "myrcene", "caryophyllene"], "thc", "typically high THC", "dense", "Netherlands",
     "A sweet tangerine-citrus hybrid from Barney's Farm.",
     ["tangerine dream sativa"], [LEAFLY, WIKILEAF], 0.8),
    ("Sensi Star", I, "Afghani lineage", "myrcene",
     ["earthy", "citrus", "metallic", "sweet"], ["earthy", "citrus", "sweet"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", "Netherlands",
     "A potent, frosty indica with earthy-citrus notes; multiple Cup wins.",
     [], [LEAFLY, WIKILEAF], 0.8),
    ("Hash Plant", I, "Northern Lights #1 x Afghani", "myrcene",
     ["earthy", "hash", "spicy", "sweet"], ["earthy", "hash", "spice"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "dense", "Netherlands",
     "A resinous, hash-forward indica with earthy spice.",
     ["hashplant"], [LEAFLY, SEEDFINDER], 0.78),
    ("G13", I, "clone-only (origin disputed)", "myrcene",
     ["earthy", "pine", "sweet", "fruity"], ["earthy", "pine", "sweet"],
     ["myrcene", "caryophyllene", "limonene"], "thc", "typically high THC", "dense", US,
     "A legendary, mythologized indica cut with earthy-pine and sweet notes.",
     ["g-13", "g 13"], [LEAFLY, WIKILEAF], 0.72),
    ("Headcheese", H, "Headband x 707 Truthband", "caryophyllene",
     ["cheese", "diesel", "earthy", "sour"], ["cheese", "diesel", "sour"],
     ["caryophyllene", "myrcene", "limonene"], "thc", "typically high THC", "dense", US,
     "A funky cheese-and-diesel hybrid.",
     ["head cheese"], [LEAFLY, SEEDFINDER], 0.74),
    ("Lemon OG", H, "Las Vegas Lemon Skunk x The OG #18", "limonene",
     ["lemon", "citrus", "earthy", "fuel"], ["lemon", "citrus", "fuel"],
     ["limonene", "myrcene", "caryophyllene"], "thc", "typically high THC", "dense", US,
     "A lemony, fuel-tinged OG hybrid.",
     ["lemon og kush"], [LEAFLY, SEEDFINDER], 0.76),
    ("Pineapple", S, "Ed Rosenthal Super Bud phenotype", "myrcene",
     ["pineapple", "tropical", "sweet", "citrus"], ["pineapple", "tropical", "sweet"],
     ["myrcene", "limonene", "pinene"], "thc", "typically high THC", "dense", US,
     "A tropical pineapple-forward sativa-leaning phenotype.",
     ["pineapple og"], [LEAFLY, SEEDFINDER], 0.75),
    ("Strawberry Cough", S, "Strawberry Fields x Haze", "myrcene",
     ["strawberry", "sweet", "berry", "earthy"], ["strawberry", "sweet", "berry"],
     ["myrcene", "caryophyllene", "pinene"], "thc", "typically high THC", "fluffy", US,
     "A sweet, true-to-name strawberry sativa with a smooth, expansive feel.",
     ["strawberry cough sativa"], [LEAFLY, WIKILEAF], 0.85),

    # High-CBD / alternate-cannabinoid additions
    ("Remedy", I, "Cannatonic x Afghan Skunk", "myrcene",
     ["earthy", "floral", "pine", "sweet"], ["earthy", "floral", "sweet"],
     ["myrcene", "pinene", "caryophyllene"], "cbd", "high-CBD / very low THC", "dense", US,
     "A high-CBD, very-low-THC indica with earthy-floral, piney notes.",
     ["the remedy"], [LEAFLY, SEEDFINDER], 0.8),
    ("Sweet and Sour Widow", H, "high-CBD White Widow line", "myrcene",
     ["earthy", "sweet", "sour", "skunky"], ["earthy", "sweet", "sour"],
     ["myrcene", "caryophyllene", "pinene"], "balanced", "balanced CBD:THC", "dense", US,
     "A roughly balanced CBD:THC White Widow line with sweet-and-sour notes.",
     ["sweet & sour widow"], [LEAFLY, SEEDFINDER], 0.74),
    ("Valentine X", H, "ACDC phenotype", "myrcene",
     ["earthy", "sweet", "herbal", "pine"], ["earthy", "sweet", "herbal"],
     ["myrcene", "pinene", "caryophyllene"], "cbd", "very high CBD (often ~25:1 CBD:THC)", "fluffy", US,
     "An ACDC-derived, very-high-CBD cultivar with earthy-herbal notes.",
     ["valentinex", "valentine"], [LEAFLY, SEEDFINDER], 0.78),
    ("Suzy Q", H, "high-CBD line", "myrcene",
     ["earthy", "herbal", "sweet", "woody"], ["earthy", "herbal", "sweet"],
     ["myrcene", "pinene", "caryophyllene"], "cbd", "very high CBD / very low THC", "fluffy", US,
     "A very-high-CBD, very-low-THC cultivar with earthy-herbal notes.",
     ["suzy-q", "suzyq"], [LEAFLY, SEEDFINDER], 0.74),
    ("Critical Mass CBD", I, "Critical Mass x high-CBD line", "myrcene",
     ["earthy", "sweet", "skunky", "citrus"], ["earthy", "sweet", "citrus"],
     ["myrcene", "caryophyllene", "limonene"], "balanced", "balanced-to-high CBD", "dense", "Spain",
     "A CBD-rich Critical Mass selection with earthy-sweet notes.",
     ["critical cbd", "critical mass cbd 1:1"], [LEAFLY, SEEDFINDER], 0.74),
]
