"use client";

/**
 * DispositionAdvisorPanel (Task Q) — on-demand, DRAFTS-ONLY AI briefing for
 * the Returns & Destruction command center. Reads aggregate counts only
 * (no customer details) and returns: what needs attention, what's compliant,
 * and the exact next steps. Advisory only — it never mutates anything.
 */
import { useState, useTransition } from "react";
import { Button } from "@/components/admin/ui";
import { useToast } from "@/components/admin/ux";
import {
  generateDispositionAdviceAction,
  type DispositionAdvisorResult,
} from "@/app/admin/inventory/disposition/actions";
import type { DispositionAdvice } from "@/lib/inventory/disposition-advisor";

function BulletList({
  title,
  items,
  tone,
}: {
  title: string;
  items: string[];
  tone: "good" | "warn" | "action";
}) {
  if (items.length === 0) return null;
  const color = tone === "good" ? "text-[var(--admin-accent)]" : tone === "warn" ? "text-[#ff6b6b]" : "text-white";
  const dot = tone === "good" ? "bg-[var(--admin-accent)]" : tone === "warn" ? "bg-[#ff6b6b]" : "bg-[#8ab4f8]";
  return (
    <div>
      <div className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{title}</div>
      <ul className="mt-1.5 space-y-1.5">
        {items.map((it, i) => (
          <li key={i} className="flex gap-2 text-sm text-white/80">
            <span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
            <span>{it}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function DispositionAdvisorPanel({ aiEnabled }: { aiEnabled: boolean }) {
  const { toast } = useToast();
  const [advice, setAdvice] = useState<DispositionAdvice | null>(null);
  const [question, setQuestion] = useState("");
  const [pending, startTransition] = useTransition();

  function run() {
    setAdvice(null);
    startTransition(async () => {
      const res: DispositionAdvisorResult = await generateDispositionAdviceAction(
        question.trim() || undefined,
      );
      if (!res.ok) {
        toast({ tone: "error", message: res.error });
        return;
      }
      setAdvice(res.advice);
      toast({ tone: "success", message: "Disposition advisor ready." });
    });
  }

  return (
    <section className="rounded-2xl border border-[var(--admin-accent)]/25 bg-[var(--admin-accent)]/[0.04] p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="flex items-center gap-2 text-base font-semibold text-white">
            <span>✨ Disposition advisor</span>
          </h2>
          <p className="mt-0.5 text-sm text-white/60">
            A plain-language read of your returns &amp; destruction queue — what needs attention, what&apos;s
            compliant, and what to do next. Grounded in the counts on this page (no customer details sent).
            Advisory / drafts only.
          </p>
        </div>
        {aiEnabled && (
          <Button type="button" onClick={run} disabled={pending} variant="special" size="sm">
            {pending ? "Reviewing…" : advice ? "Re-review" : "Ask the advisor"}
          </Button>
        )}
      </div>

      {aiEnabled && (
        <div className="mt-3">
          <input
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                e.preventDefault();
                run();
              }
            }}
            placeholder="Optional question — e.g. “A customer wants to return an opened vape from last week, what do I do?”"
            className="w-full rounded-lg border border-white/15 bg-black/30 px-3 py-2 text-sm text-white/85 placeholder:text-white/30 focus:border-[var(--admin-accent)]/50 focus:outline-none"
          />
        </div>
      )}

      {!aiEnabled ? (
        <p className="mt-3 text-xs text-[var(--admin-gold)]">
          The advisor turns on once an <code className="font-mono">AI_API_KEY</code> is set. Everything else on this
          page works without it.
        </p>
      ) : advice ? (
        <div className="mt-4 space-y-4 rounded-xl border border-white/10 bg-black/40 p-4">
          {advice.headline && <p className="text-sm font-medium text-white/90">{advice.headline}</p>}
          <div className="grid gap-4 md:grid-cols-3">
            <BulletList title="Needs attention" items={advice.attention} tone="warn" />
            <BulletList title="Compliant" items={advice.compliant} tone="good" />
            <BulletList title="Next steps" items={advice.steps} tone="action" />
          </div>
          <p className="text-[0.65rem] text-white/35">
            Generated by {advice.model} from the aggregate queue above. Advisory only — the compliance rules baked
            into the forms are the source of truth.
          </p>
        </div>
      ) : (
        <p className="mt-3 text-xs text-white/45">
          Click <span className="font-semibold text-white/70">Ask the advisor</span> for a briefing, or type a
          question about a specific return or destruction.
        </p>
      )}
    </section>
  );
}
