/**
 * ACH AUTHORITIES - the written rules behind paying people by direct deposit.
 *
 * R39 S1. GENERATED by /workspace/scripts/r39_gen_authorities.py from quotes
 * that r39_extract_quotes.py copied mechanically out of docs/authorities/.
 * No quote below was typed by hand. Edit the mirrored source and regenerate;
 * do not hand-edit a quote here, because the verbatim test will reject it.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WHAT THIS REGISTRY ANSWERS
 * ──────────────────────────────────────────────────────────────────────────
 *
 *   - How is a payee's account proven to be real before money goes to it?
 *     (prenote vs. micro-entry "test credit" - Nacha's own definitions)
 *   - What must happen when somebody asks to change where their money goes?
 *     (Nacha Fraud Monitoring Phase 2; the WA State Auditor's callback advice)
 *   - How long must the signed form be kept? (Nacha 2 years after
 *     termination via ODFI summaries; WAC 314-55-087 five years for licensee
 *     employee records)
 *   - Which day is a banking day? (FedACH holiday rule)
 *   - Is an e-signed form as good as paper? (RCW 1.80 / 15 U.S.C. §7001, §7006)
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WEIGHT, HONESTLY
 * ──────────────────────────────────────────────────────────────────────────
 *
 * The Nacha Operating Rules themselves are a licensed publication and are not
 * mirrored. What IS mirrored is Nacha's own public rule summaries and the
 * originator guides that ODFIs (banks) publish to their customers. Those are
 * tagged `industry_guidance`: they tell Greenway what its bank will expect,
 * but they are not law, and the badge on screen says so. The Washington and
 * federal e-signature statutes and WAC 314-55-087 are binding law and carry
 * their own kinds.
 *
 * STANDING RULE 24: every `quote` is a character-for-character copy of the
 * file named in `sourceFile`; tests/compliance/r39-ach-authorities.test.ts and
 * scripts/verify-verbatim-quotes.ts both re-read it on every run.
 */

export type AchAuthorityKind = "industry_guidance" | "state_manual" | "state_law" | "statute";

export type AchAuthority = {
  readonly id: AchAuthorityId;
  readonly kind: AchAuthorityKind;
  /** Full citation as shown on screen. Publication prefixes are routed by ACH_PUBLICATION_FILES. */
  readonly citation: string;
  /** Mirrored file, relative to docs/authorities/. */
  readonly sourceFile: string;
  /** Public URL of the original. */
  readonly source: string;
  readonly quote: string;
  readonly whatItMeansHere: string;
};

export type AchAuthorityId =
  | "ach-micro-entry-definition"
  | "ach-micro-entry-under-one-dollar"
  | "ach-micro-entry-acctverify"
  | "ach-micro-entry-no-simultaneous-live"
  | "ach-prenote-vs-micro-formatting"
  | "ach-fraud-phase-2-all-originators"
  | "ach-fraud-phase-2-change-controls"
  | "ach-fraud-phase-2-annual-review"
  | "ach-false-pretenses"
  | "ach-only-consumer-debits-need-signed-writing"
  | "ach-prenote-zero-dollar-not-ownership"
  | "ach-prenote-three-banking-days"
  | "ach-returns-second-banking-day"
  | "ach-noc-six-banking-days"
  | "ach-reversal-five-banking-days"
  | "ach-reversal-description"
  | "ach-authorization-two-years-campus"
  | "ach-authorization-two-years-united"
  | "ach-prenotes-optional"
  | "ach-prenote-codes"
  | "ach-prenote-wait-history"
  | "ach-payroll-description"
  | "ach-verify-with-contact-on-file"
  | "ach-noc-no-new-authorization"
  | "ach-fedach-saturday-sunday"
  | "ach-plaid-same-day"
  | "ach-sao-verify-by-phone"
  | "ach-sao-segregate-duties"
  | "ach-callback-manipulation"
  | "ach-unc-verbal-in-person-or-phone"
  | "ach-wac-087-five-years"
  | "ach-wac-087-employee-records"
  | "ach-rcw-1-80-040-agreement"
  | "ach-rcw-1-80-060-signature"
  | "ach-rcw-1-80-080-attribution"
  | "ach-usc-7001-a"
  | "ach-usc-7006-5";

/** Every id above, as a runtime list. Checked against the registry by test. */
export const ALL_ACH_AUTHORITY_IDS: readonly AchAuthorityId[] = [
  "ach-micro-entry-definition",
  "ach-micro-entry-under-one-dollar",
  "ach-micro-entry-acctverify",
  "ach-micro-entry-no-simultaneous-live",
  "ach-prenote-vs-micro-formatting",
  "ach-fraud-phase-2-all-originators",
  "ach-fraud-phase-2-change-controls",
  "ach-fraud-phase-2-annual-review",
  "ach-false-pretenses",
  "ach-only-consumer-debits-need-signed-writing",
  "ach-prenote-zero-dollar-not-ownership",
  "ach-prenote-three-banking-days",
  "ach-returns-second-banking-day",
  "ach-noc-six-banking-days",
  "ach-reversal-five-banking-days",
  "ach-reversal-description",
  "ach-authorization-two-years-campus",
  "ach-authorization-two-years-united",
  "ach-prenotes-optional",
  "ach-prenote-codes",
  "ach-prenote-wait-history",
  "ach-payroll-description",
  "ach-verify-with-contact-on-file",
  "ach-noc-no-new-authorization",
  "ach-fedach-saturday-sunday",
  "ach-plaid-same-day",
  "ach-sao-verify-by-phone",
  "ach-sao-segregate-duties",
  "ach-callback-manipulation",
  "ach-unc-verbal-in-person-or-phone",
  "ach-wac-087-five-years",
  "ach-wac-087-employee-records",
  "ach-rcw-1-80-040-agreement",
  "ach-rcw-1-80-060-signature",
  "ach-rcw-1-80-080-attribution",
  "ach-usc-7001-a",
  "ach-usc-7006-5",
];

/**
 * Citation prefix -> mirrored file (relative to docs/authorities/). The verbatim
 * verifier (scripts/verify-verbatim-quotes.ts) routes these publications through
 * this table, so a reworded citation fails loudly instead of being skipped.
 */
export const ACH_PUBLICATION_FILES: Readonly<Record<string, string>> = {
  "Nacha, Micro-Entries (Phase 1) rule summary": "ach/nacha-micro-entries-phase-1.txt",
  "Nacha, Fraud Monitoring Phase 2 rule summary": "ach/nacha-fraud-monitoring-phase-2.txt",
  "Nacha, Meaningful Modernization rule summary": "ach/nacha-meaningful-modernization.txt",
  "Simmons Bank, ACH Origination Guidelines (July 2024)": "ach/odfi-simmons-ach-origination-guidelines.txt",
  "Campus Federal Credit Union, Originator's Responsibilities (2024 brochure)": "ach/odfi-campus-federal-originator-responsibilities-2024.txt",
  "United Bank, Nacha Operating Rules Updates and Reminders 2024": "ach/odfi-access-united-nacha-updates-2024.txt",
  "First Citizens Bank, NACHA File Specifications (Rev 02/2024)": "ach/odfi-first-citizens-nacha-file-specs.txt",
  "Grand Valley Bank, Prenotification Entries: Reduction in Waiting Period for Live Entries": "ach/odfi-grand-valley-prenote-waiting-period.txt",
  "mypeoples.bank, 2026 Originators newsletter (January 2026)": "ach/odfi-peoples-bank-2026-originators-newsletter.txt",
  "Federal Reserve Financial Services, Holiday Schedules": "ach/frbservices-holiday-schedule.txt",
  "Plaid Docs, Auth - Same Day Micro-deposits": "ach/plaid-auth-same-day-micro-deposits.txt",
  "Washington State Auditor's Office, Protect your vendor master file from fraudsters": "ach/wa-sao-vendor-master-file.txt",
  "Disbursement Controls, Vendor Contact Change Risks": "ach/disbursementcontrols-vendor-contact-change-risk.txt",
  "UNC-Chapel Hill Finance, Safely Updating Vendor Bank Accounts (June 15, 2020)": "ach/unc-finance-safely-updating-vendor-bank-accounts.txt",
};

export const ACH_AUTHORITIES: readonly AchAuthority[] = [
  {
    id: "ach-micro-entry-definition",
    kind: "industry_guidance",
    citation: "Nacha, Micro-Entries (Phase 1) rule summary",
    sourceFile: "ach/nacha-micro-entries-phase-1.txt",
    source: "https://www.nacha.org/micro-entries",
    quote:
    "A Micro-Entry will be “a credit or debit Entry used by an Originator for the purpose of " +
    "verifying a Receiver’s account or an individual's access to an account.”",
    whatItMeansHere:
    "This is what the \"$1 test credit\" Michael asked about actually is, in Nacha's own words: a " +
    "small real deposit whose only job is to prove the account works and that the payee can see " +
    "it. It is not a check and it is not a prenote. Greenway would only ever send the CREDIT " +
    "half; this system never originates debits, so there is no offsetting pull-back.",
  },
  {
    id: "ach-micro-entry-under-one-dollar",
    kind: "industry_guidance",
    citation: "Nacha, Micro-Entries (Phase 1) rule summary",
    sourceFile: "ach/nacha-micro-entries-phase-1.txt",
    source: "https://www.nacha.org/micro-entries",
    quote:
    "A credit Micro-Entry must be in the amount of less than $1.00 One or more debit " +
    "Micro-Entries must not exceed, in total, the amount of the corresponding credit " +
    "Micro-Entries This definition accommodates the existing practices of offsetting the amounts " +
    "of credit Micro-Entries with one or more debits, which nets the total verification practice " +
    "to $0;",
    whatItMeansHere:
    "The test credit must be under one dollar, so the system refuses any verification credit of " +
    "$1.00 or more. The second sentence is about offsetting debits, which Greenway never sends - " +
    "it is quoted whole so nobody trims it into a sentence that sounds like it allows a debit. " +
    "The vendor form already promises the test credit is not recoverable.",
  },
  {
    id: "ach-micro-entry-acctverify",
    kind: "industry_guidance",
    citation: "Nacha, Micro-Entries (Phase 1) rule summary",
    sourceFile: "ach/nacha-micro-entries-phase-1.txt",
    source: "https://www.nacha.org/micro-entries",
    quote:
    "In the Company Entry Description field, the Rule requires the use of “ACCTVERIFY”",
    whatItMeansHere:
    "If Greenway ever sends a test credit, the batch description must read ACCTVERIFY, not VENDOR " +
    "PAY or PAYROLL. The system stamps that word itself so nobody has to remember it, and so the " +
    "payee's statement shows a line that obviously is a verification and not a short payment.",
  },
  {
    id: "ach-micro-entry-no-simultaneous-live",
    kind: "industry_guidance",
    citation: "Nacha, Micro-Entries (Phase 1) rule summary",
    sourceFile: "ach/nacha-micro-entries-phase-1.txt",
    source: "https://www.nacha.org/micro-entries",
    quote:
    "An Originator using Micro-Entries may initiate future Entries to the Receiver’s account as " +
    "soon as the Originator’s process for validating the amounts of the Micro-Entries has been " +
    "completed The Originator is in the best position to know when the validation process is " +
    "complete A future Entry may not be originated simultaneously with Micro-Entries ODFIs are " +
    "not required to review or inspect files to enforce this In Phase 2 of the Rule risk " +
    "management requirements will be applied to Originators.",
    whatItMeansHere:
    "The real payment must wait until the payee has confirmed the test amount. The system " +
    "therefore keeps a payee in Pending Verification until the confirmed amount is recorded, and " +
    "refuses to put a live payment in the same file as the test credit, even when that would be " +
    "convenient.",
  },
  {
    id: "ach-prenote-vs-micro-formatting",
    kind: "industry_guidance",
    citation: "Nacha, Micro-Entries (Phase 1) rule summary",
    sourceFile: "ach/nacha-micro-entries-phase-1.txt",
    source: "https://www.nacha.org/micro-entries",
    quote:
    "Prenotification Entries can be easily identified by a unique transaction code and a dollar " +
    "amount of zero. For these entries, a specific company entry description is not needed to " +
    "identify these entries as an account validation tool, and Originators have discretion over " +
    "the content of the company entry description field.",
    whatItMeansHere:
    "Nacha's own explanation of the difference Michael asked about. A prenote is identified by " +
    "its special transaction code and a zero amount - no money moves and nothing posts. A test " +
    "credit is a real deposit and is identified by the word ACCTVERIFY. Two different tools; the " +
    "system treats them as two different verification methods.",
  },
  {
    id: "ach-fraud-phase-2-all-originators",
    kind: "industry_guidance",
    citation: "Nacha, Fraud Monitoring Phase 2 rule summary",
    sourceFile: "ach/nacha-fraud-monitoring-phase-2.txt",
    source: "https://www.nacha.org/rules/risk-management-topics-fraud-monitoring-phase-2",
    quote:
    "(effective June 19, 2026) will eliminate the volume threshold and will require all " +
    "non-consumer Originators, Third-Party Service Providers, and Third-Party Senders (regardless " +
    "of origination or transmission volume) to comply with the fraud monitoring rules.",
    whatItMeansHere:
    "Greenway is a non-consumer Originator, so this applies to Greenway now - it took effect June " +
    "19, 2026, and practically June 22, 2026 because the 19th was Juneteenth. Size does not " +
    "matter any more: a ten-employee shop is in scope exactly like a large one. That is why this " +
    "round builds written, logged procedures instead of relying on memory.",
  },
  {
    id: "ach-fraud-phase-2-change-controls",
    kind: "industry_guidance",
    citation: "Nacha, Fraud Monitoring Phase 2 rule summary",
    sourceFile: "ach/nacha-fraud-monitoring-phase-2.txt",
    source: "https://www.nacha.org/rules/risk-management-topics-fraud-monitoring-phase-2",
    quote:
    "Originators may be best placed to implement procedures to protect against account takeover " +
    "or other vectors for initiating unauthorized transactions. Such procedures could include " +
    "change controls regarding payment information and instructions for vendor and payroll " +
    "payments.",
    whatItMeansHere:
    "This is the sentence the whole vault design answers. A bank-detail change is the single most " +
    "valuable thing a fraudster can achieve, so a change puts the payee ON HOLD, must be verified " +
    "by a callback to a number already on file, and must be released by Michael or Stephen with a " +
    "written record. Payments cannot go to new details until that happens.",
  },
  {
    id: "ach-fraud-phase-2-annual-review",
    kind: "industry_guidance",
    citation: "Nacha, Fraud Monitoring Phase 2 rule summary",
    sourceFile: "ach/nacha-fraud-monitoring-phase-2.txt",
    source: "https://www.nacha.org/rules/risk-management-topics-fraud-monitoring-phase-2",
    quote:
    "establish and implement risk-based processes and procedures, relevant to the role it plays " +
    "in the authorization or Transmission of Entries, that are reasonably intended to identify " +
    "Entries that are suspected of being unauthorized or authorized under False Pretenses; and " +
    "review (at least annually) these processes and procedures and make appropriate updates to " +
    "address evolving risks.",
    whatItMeansHere:
    "Two duties: have risk-based procedures, and review them at least once a year. The system " +
    "records the last review date and flags the procedures as overdue after twelve months, so the " +
    "annual review is something the screen asks for rather than something to remember.",
  },
  {
    id: "ach-false-pretenses",
    kind: "industry_guidance",
    citation: "Nacha, Fraud Monitoring Phase 2 rule summary",
    sourceFile: "ach/nacha-fraud-monitoring-phase-2.txt",
    source: "https://www.nacha.org/rules/risk-management-topics-fraud-monitoring-phase-2",
    quote:
    "the inducement of a payment by a Person misrepresenting (a) that Person’s identity, (b) that " +
    "Person’s association with or authority to act on behalf of another Person, or (c) the " +
    "ownership of an account to be credited.”",
    whatItMeansHere:
    "This names the exact frauds this vault defends against: someone pretending to be a vendor or " +
    "an employee and asking for payments to go to their account. A request that looks legitimate " +
    "is the danger, which is why the callback uses the number on file and never the number in the " +
    "request.",
  },
  {
    id: "ach-only-consumer-debits-need-signed-writing",
    kind: "industry_guidance",
    citation: "Nacha, Meaningful Modernization rule summary",
    sourceFile: "ach/nacha-meaningful-modernization.txt",
    source: "https://www.nacha.org/rules/meaningful-modernization",
    quote:
    "Explicitly states that authorization of an ACH payment by any method allowed by " +
    "law/regulation Only consumer debit authorizations require a writing that is signed or " +
    "similarly authenticated",
    whatItMeansHere:
    "Greenway only sends credits, so strictly speaking the Rules do not demand a signed paper " +
    "form for these payments. Greenway still collects one (paper or e-signed) because it is the " +
    "evidence that the payee chose the account, and because the bank's origination agreement may " +
    "demand more than the Rules do. The form is evidence, not a formality.",
  },
  {
    id: "ach-prenote-zero-dollar-not-ownership",
    kind: "industry_guidance",
    citation: "Simmons Bank, ACH Origination Guidelines (July 2024)",
    sourceFile: "ach/odfi-simmons-ach-origination-guidelines.txt",
    source: "https://www.simmonsbank.com/siteassets/pdfs/qrg-ach-origination-guidelines.pdf",
    quote:
    "Prenotes are zero-dollar entries sent to a Receiver’s account to verify the account number " +
    "is a valid account at the Receiving Bank (RDFI). Prenotes do not validate ownership of the " +
    "account.",
    whatItMeansHere:
    "The plain-English answer to \"is a prenote a check?\": no. It is a zero-dollar electronic test " +
    "message sent through the ACH network. Nothing is deposited, nothing is printed, and the " +
    "payee usually never sees it. The second sentence matters most: a prenote that goes through " +
    "proves the account EXISTS, not that it belongs to the payee. The callback is still required.",
  },
  {
    id: "ach-prenote-three-banking-days",
    kind: "industry_guidance",
    citation: "Simmons Bank, ACH Origination Guidelines (July 2024)",
    sourceFile: "ach/odfi-simmons-ach-origination-guidelines.txt",
    source: "https://www.simmonsbank.com/siteassets/pdfs/qrg-ach-origination-guidelines.pdf",
    quote:
    "After three (3) banking days of the Settlement Date of the prenote, provided the ODFI has " +
    "not received a Return or Notification of Change (NOC), an Originator may initiate Entries to " +
    "the Receiver’s account. If an NOC is received the Originator must make the correcting " +
    "entries prior to initiating future Entries to the Receiver’s account. If an ACH Return is " +
    "received the Originator must reach out to the Receiver for updated account information.",
    whatItMeansHere:
    "The waiting rule the system enforces. Once a prenote settles, the payee stays in Prenote " +
    "Sent for three banking days; if a return or a Notification of Change arrives, the payee goes " +
    "ON HOLD and the details are fixed first. Banking days are FedACH days, which is why the " +
    "system uses the Federal Reserve holiday list and not the calendar.",
  },
  {
    id: "ach-returns-second-banking-day",
    kind: "industry_guidance",
    citation: "Simmons Bank, ACH Origination Guidelines (July 2024)",
    sourceFile: "ach/odfi-simmons-ach-origination-guidelines.txt",
    source: "https://www.simmonsbank.com/siteassets/pdfs/qrg-ach-origination-guidelines.pdf",
    quote:
    "The RDFI must return the entry in time for Simmons Bank (ODFI) to receive it, by the opening " +
    "of business on the second banking day following the settlement date.",
    whatItMeansHere:
    "This is WHY the prenote wait is three banking days: a bank that is going to reject the " +
    "account must do so by the opening of business on the second banking day after settlement. By " +
    "the third banking day any timely rejection has already arrived, so the ready date is " +
    "settlement plus three FedACH banking days.",
  },
  {
    id: "ach-noc-six-banking-days",
    kind: "industry_guidance",
    citation: "Simmons Bank, ACH Origination Guidelines (July 2024)",
    sourceFile: "ach/odfi-simmons-ach-origination-guidelines.txt",
    source: "https://www.simmonsbank.com/siteassets/pdfs/qrg-ach-origination-guidelines.pdf",
    quote:
    "If your company sends recurring payments (i.e., daily, bi-weekly, monthly), you are required " +
    "to update the incorrect information before processing the next payment or within six banking " +
    "days of receiving the Notification of Change information.",
    whatItMeansHere:
    "When a payee's bank sends a Notification of Change (it fixed a wrong digit or account type " +
    "on its end), Greenway must update the vault before the next payment or within six banking " +
    "days. Payroll is recurring, so the system computes that due date and blocks the next payroll " +
    "file until the correction is recorded.",
  },
  {
    id: "ach-reversal-five-banking-days",
    kind: "industry_guidance",
    citation: "Simmons Bank, ACH Origination Guidelines (July 2024)",
    sourceFile: "ach/odfi-simmons-ach-origination-guidelines.txt",
    source: "https://www.simmonsbank.com/siteassets/pdfs/qrg-ach-origination-guidelines.pdf",
    quote:
    "An erroneous entry or file can contain the wrong amount, is a duplicate of a previous " +
    "file/transaction or was sent to an unintended party. The reversal of these entries must be " +
    "transmitted within five (5) banking days from the Settlement Date of the erroneous or " +
    "duplicate entry or file.",
    whatItMeansHere:
    "If a payment goes out twice, to the wrong account, or for the wrong amount, the only way to " +
    "try to pull it back through the ACH network closes five banking days after settlement. The " +
    "returns log shows that deadline as a date the moment an error is recorded, because it cannot " +
    "be extended.",
  },
  {
    id: "ach-reversal-description",
    kind: "industry_guidance",
    citation: "Simmons Bank, ACH Origination Guidelines (July 2024)",
    sourceFile: "ach/odfi-simmons-ach-origination-guidelines.txt",
    source: "https://www.simmonsbank.com/siteassets/pdfs/qrg-ach-origination-guidelines.pdf",
    quote:
    "As the Originator, you must make a reasonable attempt to notify the Receiver that a " +
    "reversing entry has been sent to their account, with the reason for the reversal, no later " +
    "than the Settlement Date of the reversing entry. When the reversal is originated the word " +
    "“REVERSAL” (in all Caps) must appear in the Company Entry Description field in the " +
    "Company/Batch Header Record.",
    whatItMeansHere:
    "A reversal must be labelled REVERSAL and the payee must be told before it settles. The " +
    "vendor and employee forms already promise that notice; the system records who was notified " +
    "and when, so the promise in the form and the record in the file say the same thing.",
  },
  {
    id: "ach-authorization-two-years-campus",
    kind: "industry_guidance",
    citation: "Campus Federal Credit Union, Originator's Responsibilities (2024 brochure)",
    sourceFile: "ach/odfi-campus-federal-originator-responsibilities-2024.txt",
    source: "https://www.campusfederal.org/uploads/docs/brochures/CFCU-Originator-Responsibilities-2024.pdf",
    quote:
    "Copies of authorizations are maintained for two years from the date the authorization is " +
    "terminated and must be provided to the RDFI within ten banking days of the request.",
    whatItMeansHere:
    "The ACH rule minimum: keep the authorization for two years after it ends, and be able to " +
    "produce it within ten banking days. That is the shortest of the three clocks that apply to " +
    "Greenway; the Washington cannabis five-year rule and Greenway's six-year policy are longer " +
    "and win, so the system keeps the later date.",
  },
  {
    id: "ach-authorization-two-years-united",
    kind: "industry_guidance",
    citation: "United Bank, Nacha Operating Rules Updates and Reminders 2024",
    sourceFile: "ach/odfi-access-united-nacha-updates-2024.txt",
    source: "https://www.accessunited.com/assets/files/84KFPs67",
    quote:
    "Authorization must be retained by the Originator for a period of two years following the " +
    "termination or revocation of the authorization. In the case of a paper authorization that " +
    "has been signed by the Receiver, the Originator must retain either the original or a copy of " +
    "the signed authorization.",
    whatItMeansHere:
    "A second, independent bank summary of the same two-year rule, quoted so the retention basis " +
    "does not rest on one bank's brochure. It also says what to keep: the original signed form or " +
    "a copy. That is why an uploaded paper form is stored as the file itself and never only as " +
    "data keyed from it.",
  },
  {
    id: "ach-prenotes-optional",
    kind: "industry_guidance",
    citation: "United Bank, Nacha Operating Rules Updates and Reminders 2024",
    sourceFile: "ach/odfi-access-united-nacha-updates-2024.txt",
    source: "https://www.accessunited.com/assets/files/84KFPs67",
    quote:
    "A prenotification is a zero-dollar entry generated to validate an account held at a " +
    "Receiving Depository Financial Institution (RDFI). Companies may originate prenotifications; " +
    "however, they are not required under the Rules. A prenotification is a tool to ensure the " +
    "account information given by the receiver is accurate prior to initiating a live dollar " +
    "transaction. If the Originator chooses to initiate a prenotification, they must wait three " +
    "(3) banking days prior to initiating the live dollar transaction.",
    whatItMeansHere:
    "Prenotes are optional under the Rules, and Michael is still confirming whether Timberland " +
    "accepts them. So the system offers prenote OR a test credit OR callback-only (with a written " +
    "reason), and records which one was used. Whichever Timberland supports, the payee cannot be " +
    "paid until the chosen check is finished.",
  },
  {
    id: "ach-prenote-codes",
    kind: "industry_guidance",
    citation: "First Citizens Bank, NACHA File Specifications (Rev 02/2024)",
    sourceFile: "ach/odfi-first-citizens-nacha-file-specs.txt",
    source: "https://www.firstcitizens.com/content/dam/firstcitizens/pdfs/commercial/commercial-advantage/nacha-file-specs.pdf",
    quote:
    "For Prenotes: 23 - Checking Credits; 33 - Savings Credits; 28 - Checking Debits; 38 - " +
    "Savings Debits For Live Dollar: 22 - Checking Credits; 32 - Savings Credits; 27 - Checking " +
    "Debits; 37 - Savings Debits",
    whatItMeansHere:
    "The transaction codes. Greenway only sends credits, so live payments use 22 (checking) and " +
    "32 (savings), and a prenote uses 23 (checking) or 33 (savings). The debit codes appear in " +
    "the quote only because they share the sentence; the system has no code path that can produce " +
    "27, 28, 37 or 38.",
  },
  {
    id: "ach-prenote-wait-history",
    kind: "industry_guidance",
    citation: "Grand Valley Bank, Prenotification Entries: Reduction in Waiting Period for Live Entries",
    sourceFile: "ach/odfi-grand-valley-prenote-waiting-period.txt",
    source: "https://www.grandvalleybank.com/assets/files/ip5QIqAu",
    quote:
    "In the past, Originators have had to wait six Banking Days before transmitting “live” " +
    "entries following a Prenote. However, in today’s banking environment, that length of waiting " +
    "time often appears excessive, making the use of a Prenote ineffective for many Originators. " +
    "Responding to the financial industry’s support for shortening that period, the Rule will " +
    "make the waiting period three banking days.",
    whatItMeansHere:
    "History, quoted so an older article or a long-serving bookkeeper saying \"six days\" does not " +
    "cause confusion. The wait used to be six banking days; the Rules cut it to three. The system " +
    "uses three, which matches the 2024 bank summaries quoted next to this one.",
  },
  {
    id: "ach-payroll-description",
    kind: "industry_guidance",
    citation: "mypeoples.bank, 2026 Originators newsletter (January 2026)",
    sourceFile: "ach/odfi-peoples-bank-2026-originators-newsletter.txt",
    source: "https://www.mypeoples.bank/uploads/userfiles/files/documents/2026%20Originators%20newsletter.pdf",
    quote:
    "The Company Entry Description field must contain PAYROLL, all capitalized, for PPD Credits " +
    "paying wages, salaries and other similar types of compensation.",
    whatItMeansHere:
    "From March 20, 2026 a payroll batch must say PAYROLL in capitals. The payroll file builder " +
    "already defaults to PAYROLL; this authority is why it may not be changed to something " +
    "friendlier like \"PAY\" or \"WAGES\", and why a test fails if it is.",
  },
  {
    id: "ach-verify-with-contact-on-file",
    kind: "industry_guidance",
    citation: "mypeoples.bank, 2026 Originators newsletter (January 2026)",
    sourceFile: "ach/odfi-peoples-bank-2026-originators-newsletter.txt",
    source: "https://www.mypeoples.bank/uploads/userfiles/files/documents/2026%20Originators%20newsletter.pdf",
    quote:
    "If a long-time Receiver unexpectedly sends new account details, especially via email, text " +
    "or fax, treat it as a red flag. The Originator should use the contact information on file, " +
    "not the information in the change request message, to verify account changes. Apply “know " +
    "your customer” practices to confirm the request is legitimate before proceeding. Your " +
    "company is responsible for following up on any request to change a Receiver’s account " +
    "information with a phone call to the number on file in your records, without relying on the " +
    "contact information included in the request.",
    whatItMeansHere:
    "The callback rule in a bank's words: a change request is verified by calling the number " +
    "already in Greenway's records, never a number in the email, text or fax asking for the " +
    "change. The verification screen shows only numbers that were on file before the request, and " +
    "never a number typed into the request.",
  },
  {
    id: "ach-noc-no-new-authorization",
    kind: "industry_guidance",
    citation: "mypeoples.bank, 2026 Originators newsletter (January 2026)",
    sourceFile: "ach/odfi-peoples-bank-2026-originators-newsletter.txt",
    source: "https://www.mypeoples.bank/uploads/userfiles/files/documents/2026%20Originators%20newsletter.pdf",
    quote:
    "By complying with the NOC, your business can originate from future transactions without " +
    "having to obtain a new authorization.",
    whatItMeansHere:
    "Applying a Notification of Change does not require the payee to sign a new form. The system " +
    "records the NOC as the reason for the corrected details, so the change has a paper trail " +
    "without dragging the payee back in for a signature.",
  },
  {
    id: "ach-fedach-saturday-sunday",
    kind: "industry_guidance",
    citation: "Federal Reserve Financial Services, Holiday Schedules",
    sourceFile: "ach/frbservices-holiday-schedule.txt",
    source: "https://www.frbservices.org/about/holiday-schedules",
    quote:
    "*For holidays falling on Saturday, Federal Reserve Banks and Branches will be open the " +
    "preceding Friday. **For holidays falling on Sunday, Federal Reserve Banks and Branches will " +
    "be closed the following Monday.",
    whatItMeansHere:
    "The two rules that make FedACH banking days differ from the federal calendar. A Saturday " +
    "holiday does NOT close the Fed on Friday; a Sunday holiday DOES close it on Monday. The " +
    "existing payroll deposit calendar follows a different rule (DC holidays) and must not be " +
    "reused for ACH timing; this engine has its own.",
  },
  {
    id: "ach-plaid-same-day",
    kind: "industry_guidance",
    citation: "Plaid Docs, Auth - Same Day Micro-deposits",
    sourceFile: "ach/plaid-auth-same-day-micro-deposits.txt",
    source: "https://plaid.com/docs/auth/coverage/same-day/",
    quote:
    "Behind the scenes, Plaid sends a micro-deposit to the user's account that will post within " +
    "one to two business days.",
    whatItMeansHere:
    "Why Plaid is not the default. Greenway's Plaid plan is limited, and even same-day " +
    "micro-deposits take one to two business days and need the payee to come back and confirm. A " +
    "prenote from Greenway's own file needs nothing from the payee, so it is the easier route if " +
    "Timberland accepts prenotes. Plaid stays available as a later option.",
  },
  {
    id: "ach-sao-verify-by-phone",
    kind: "state_manual",
    citation: "Washington State Auditor's Office, Protect your vendor master file from fraudsters",
    sourceFile: "ach/wa-sao-vendor-master-file.txt",
    source: "https://sao.wa.gov/the-audit-connection-blog/protect-your-vendor-master-file-fraudsters",
    quote:
    "It's critical to independently verify any requests to change vendor information directly " +
    "with your vendor. You should do this by phone, using contact information that is known, " +
    "reliable and already on file.",
    whatItMeansHere:
    "Washington's own auditor says the same thing as the bank summaries: call, using contact " +
    "information already on file. The State Auditor audits public bodies, not Greenway, so this " +
    "is persuasive and not binding - but it is the clearest Washington statement of the standard.",
  },
  {
    id: "ach-sao-segregate-duties",
    kind: "state_manual",
    citation: "Washington State Auditor's Office, Protect your vendor master file from fraudsters",
    sourceFile: "ach/wa-sao-vendor-master-file.txt",
    source: "https://sao.wa.gov/the-audit-connection-blog/protect-your-vendor-master-file-fraudsters",
    quote:
    "Just like payroll clerks should not be able to add new employees or edit the payroll master " +
    "file, accounts payable clerks should not be able to add new vendors or change vendor " +
    "information in the vendor master file.",
    whatItMeansHere:
    "The reason managers can upload a signed form but cannot open it, edit bank details or " +
    "release a payee. Only Michael and Stephen can change the vendor or employee master file. " +
    "With two people that is the strongest separation available, and the solo-release log covers " +
    "the days only one of them is in.",
  },
  {
    id: "ach-callback-manipulation",
    kind: "industry_guidance",
    citation: "Disbursement Controls, Vendor Contact Change Risks",
    sourceFile: "ach/disbursementcontrols-vendor-contact-change-risk.txt",
    source: "https://www.disbursementcontrols.com/vendor-contact-change-risk",
    quote:
    "Many organizations use callback procedures to validate banking changes or payment requests. " +
    "If fraudsters successfully change vendor phone numbers or contact information, they may " +
    "redirect validation calls directly to themselves. This allows criminals to defeat one of the " +
    "most used fraud prevention controls by creating the illusion of independent verification. " +
    "Organizations that rely solely on contact details provided within change requests may " +
    "unknowingly validate fraudulent changes with the attackers themselves.",
    whatItMeansHere:
    "The trap a plain callback falls into: the fraudster first changes the phone number, then " +
    "asks for the bank change, then answers the callback. That is why a contact change within the " +
    "look-back window before a bank change raises the risk and forces the callback to an older " +
    "number on file.",
  },
  {
    id: "ach-unc-verbal-in-person-or-phone",
    kind: "industry_guidance",
    citation: "UNC-Chapel Hill Finance, Safely Updating Vendor Bank Accounts (June 15, 2020)",
    sourceFile: "ach/unc-finance-safely-updating-vendor-bank-accounts.txt",
    source: "https://finance.unc.edu/news/2020/06/15/safely-updating-vendor-bank-accounts",
    quote:
    "Therefore, it is critical to validate vendor bank accounts by communicating verbally (in " +
    "person or by telephone) with a known contact. This must be done by calling the company’s " +
    "accounting, billing, or accounts receivable department at a phone number from an independent " +
    "source . This information should not be validated with a phone number provided by an emailed " +
    "request to update banking information.",
    whatItMeansHere:
    "A university accounts-payable policy that says what the release screen asks for: the payee " +
    "confirms the bank details verbally, either face to face or on a phone call to a number found " +
    "independently, never one from the email that asked for the change. That is why the release " +
    "form offers two methods, phone or in person. A phone callback must use a number on file for " +
    "the 90-day look-back; an in-person confirmation involves no phone number, so the look-back " +
    "does not apply, but a written note of who confirmed it is still required.",
  },
  {
    id: "ach-wac-087-five-years",
    kind: "state_law",
    citation: "WAC 314-55-087(1)",
    sourceFile: "state-wa/wac-314-55-087.txt",
    source: "https://app.leg.wa.gov/WAC/default.aspx?cite=314-55-087",
    quote:
    "(1) Cannabis licensees are responsible to keep records that clearly reflect all financial " +
    "transactions and the financial condition of the business. The following records must be kept " +
    "and maintained on the licensed premises for a five-year period and must be made available " +
    "for inspection if requested by an employee of the LCB:",
    whatItMeansHere:
    "The Washington cannabis rule. Bank statements, financial transaction records and employee " +
    "records must be kept on the licensed premises for five years and shown to the LCB on " +
    "request. A signed ACH authorization is a record of a financial arrangement and part of the " +
    "employee file, so it is kept at least five years.",
  },
  {
    id: "ach-wac-087-employee-records",
    kind: "state_law",
    citation: "WAC 314-55-087(1)(e)",
    sourceFile: "state-wa/wac-314-55-087.txt",
    source: "https://app.leg.wa.gov/WAC/default.aspx?cite=314-55-087",
    quote:
    "(e) All employee records to include, but not limited to, training, payroll, and date of " +
    "hire;",
    whatItMeansHere:
    "\"All employee records ... payroll\" - an employee's direct-deposit authorization is a payroll " +
    "record, so it goes in the employee file and is kept for the WAC period. Greenway's policy " +
    "keeps it six years after it ends, which is longer than both this rule and the ACH rule.",
  },
  {
    id: "ach-rcw-1-80-040-agreement",
    kind: "state_law",
    citation: "RCW 1.80.040(2)",
    sourceFile: "state-wa/rcw-1.80.040.txt",
    source: "https://app.leg.wa.gov/RCW/default.aspx?cite=1.80.040",
    quote:
    "(2) This chapter applies only to transactions between parties each of which has agreed to " +
    "conduct transactions by electronic means. Whether the parties agree to conduct a transaction " +
    "by electronic means is determined from the context and surrounding circumstances, including " +
    "the parties' conduct.",
    whatItMeansHere:
    "E-signing is only valid if the person agreed to do business electronically. That is why the " +
    "e-sign page asks for an explicit consent click before the form is shown, records it with a " +
    "timestamp, and offers paper instead. Declining e-sign never blocks someone from signing on " +
    "paper.",
  },
  {
    id: "ach-rcw-1-80-060-signature",
    kind: "state_law",
    citation: "RCW 1.80.060",
    sourceFile: "state-wa/rcw-1.80.060.txt",
    source: "https://app.leg.wa.gov/RCW/default.aspx?cite=1.80.060",
    quote:
    "(1) A record or signature may not be denied legal effect or enforceability solely because it " +
    "is in electronic form. (2) A contract may not be denied legal effect or enforceability " +
    "solely because an electronic record was used in its formation. (3) If a law requires a " +
    "record to be in writing, an electronic record satisfies the law. (4) If a law requires a " +
    "signature, an electronic signature satisfies the law.",
    whatItMeansHere:
    "Washington law: an e-signature counts as a signature, and an electronic record counts as a " +
    "writing. That is what makes an e-signed ACH form exactly as good as a paper one - provided " +
    "the attribution evidence in RCW 1.80.080 is kept with it.",
  },
  {
    id: "ach-rcw-1-80-080-attribution",
    kind: "state_law",
    citation: "RCW 1.80.080(1)",
    sourceFile: "state-wa/rcw-1.80.080.txt",
    source: "https://app.leg.wa.gov/RCW/default.aspx?cite=1.80.080",
    quote:
    "(1) An electronic record or electronic signature is attributable to a person if it was the " +
    "act of the person. The act of the person may be shown in any manner, including a showing of " +
    "the efficacy of any security procedure applied to determine the person to which the " +
    "electronic record or electronic signature was attributable.",
    whatItMeansHere:
    "If anyone ever disputes a signature, the question is whether it was that person's act, and a " +
    "security procedure helps prove it. The e-sign flow therefore records a one-time code sent to " +
    "contact details on file, the time, the IP address, the browser, and a hash of the exact " +
    "document signed, and prints them on a certificate.",
  },
  {
    id: "ach-usc-7001-a",
    kind: "statute",
    citation: "15 U.S.C. §7001(a)",
    sourceFile: "federal/usc-15-7001.txt",
    source: "https://www.law.cornell.edu/uscode/text/15/7001",
    quote:
    "(1) a signature, contract, or other record relating to such transaction may not be denied " +
    "legal effect, validity, or enforceability solely because it is in electronic form; and (2) a " +
    "contract relating to such transaction may not be denied legal effect, validity, or " +
    "enforceability solely because an electronic signature or electronic record was used in its " +
    "formation.",
    whatItMeansHere:
    "The federal E-SIGN Act says the same thing as Washington's UETA for interstate commerce: an " +
    "electronic signature or record may not be refused legal effect just because it is " +
    "electronic. Both are quoted so the e-signed form stands on federal and state law.",
  },
  {
    id: "ach-usc-7006-5",
    kind: "statute",
    citation: "15 U.S.C. §7006(5)",
    sourceFile: "federal/usc-15-7006.txt",
    source: "https://www.law.cornell.edu/uscode/text/15/7006",
    quote:
    "The term “ electronic signature ” means an electronic sound, symbol, or process, attached to " +
    "or logically associated with a contract or other record and executed or adopted by a person " +
    "with the intent to sign the record.",
    whatItMeansHere:
    "What an electronic signature legally is: a sound, symbol or process attached to the record " +
    "and adopted WITH INTENT TO SIGN. That is why the e-sign page requires the signer to type " +
    "their name and tick a statement that typing it is their signature, rather than treating a " +
    "button click as a signature.",
  },
];

/**
 * Look an authority up by an id that came from outside the type system (a
 * stored row, a URL). Returns null rather than throwing so the caller decides
 * what an unknown id means; callers holding a checked AchAuthorityId should
 * reference the record directly instead.
 */
export function achAuthorityById(id: string): AchAuthority | null {
  return ACH_AUTHORITIES.find((a) => a.id === id) ?? null;
}

/**
 * Which mirrored file a citation routes to, or null if it is not an ACH
 * publication. Used by scripts/verify-verbatim-quotes.ts so the router and
 * this registry cannot disagree about a prefix.
 */
export function achPublicationFileFor(cite: string): string | null {
  for (const [prefix, file] of Object.entries(ACH_PUBLICATION_FILES)) {
    if (cite.startsWith(prefix)) return file;
  }
  return null;
}
