/**
 * R39 S5 — ACH document intake (pure; no I/O).
 *
 * Owner answers this implements:
 *   Q2  "managers upload documents; enterprise grade" — drop-only intake.
 *   Q6  "LlamaParse" — a machine DRAFT only; a person always re-keys blind.
 *   Q10 the signed form goes in the employee file AND the vault.
 *
 * Every limit below mirrors a CHECK in supabase/migrations/0258 (pinned by
 * tests/compliance/r39-ach-document-intake.test.ts) so the app refuses a file
 * with a plain sentence before Postgres would refuse it with a code.
 *
 * Upload rules follow the OWASP File Upload Cheat Sheet
 * (cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html):
 *   - "Validate the file type, don't trust the Content-Type header" -> the
 *     magic bytes decide; a declared type that disagrees is refused.
 *   - signature validation "should not be used on its own" -> the extension
 *     must ALSO be allow-listed and agree with the bytes.
 *   - "Change the filename to something generated by the application" ->
 *     storage key is <payee type>/<payee id>/<uuid>.<ext>; the person's file
 *     name is kept only as display text.
 *   - reject colons, null bytes / control characters, double extensions that
 *     hide an executable, and over-long names; "Set a file size limit".
 *
 * HEIC signature: ISO BMFF "ftyp" box at byte 4; the major or a compatible
 * brand must be heic / heix / heim / heis (IANA image/heic registration, as
 * summarised by Library of Congress fdd000526).
 */
import { isValidRouting } from "./nacha-core";
import { MAX_ACCOUNTS_PER_PAYEE, type AccountType, type SplitRule } from "./ach-authorization-core";

// ---------------------------------------------------------------- limits ----

/** 25 MiB — 0258: byte_size > 0 and byte_size <= 26214400. */
export const MAX_DOC_BYTES = 26214400;
export const MAX_ORIGINAL_FILENAME_CHARS = 180;

export const DOC_MIME_TYPES = ["application/pdf", "image/jpeg", "image/png", "image/heic"] as const;
export type DocMime = (typeof DOC_MIME_TYPES)[number];

export const DOC_KINDS = ["signed_form", "voided_check", "bank_letter", "esign_certificate", "other"] as const;
export type DocKind = (typeof DOC_KINDS)[number];

/** Kinds a person may upload. esign_certificate is produced by the app (S6). */
export const UPLOADABLE_DOC_KINDS: readonly DocKind[] = ["signed_form", "voided_check", "bank_letter", "other"];

export const DOC_KIND_LABELS: Readonly<Record<DocKind, string>> = {
  signed_form: "Signed authorization form",
  voided_check: "Voided check",
  bank_letter: "Bank letter",
  esign_certificate: "E-sign certificate",
  other: "Other supporting document",
};

export const INTAKE_STATUSES = ["received", "extracted", "rekeyed", "accepted", "rejected"] as const;
export type IntakeStatus = (typeof INTAKE_STATUSES)[number];

/** File extension written to storage for each type (app-generated name). */
export const STORAGE_EXT: Readonly<Record<DocMime, string>> = {
  "application/pdf": "pdf",
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/heic": "heic",
};

/** Extensions a person's file may carry for each sniffed type. */
export const ALLOWED_EXTS: Readonly<Record<DocMime, readonly string[]>> = {
  "application/pdf": ["pdf"],
  "image/jpeg": ["jpg", "jpeg"],
  "image/png": ["png"],
  "image/heic": ["heic", "heif", "hif"],
};

/** Declared types a browser may send for each sniffed type ("" = unknown). */
const DECLARED_OK: Readonly<Record<DocMime, readonly string[]>> = {
  "application/pdf": ["application/pdf", "application/x-pdf"],
  "image/jpeg": ["image/jpeg", "image/jpg", "image/pjpeg"],
  "image/png": ["image/png"],
  "image/heic": ["image/heic", "image/heif"],
};
const DECLARED_UNKNOWN = ["", "application/octet-stream", "binary/octet-stream"];

/**
 * Inner extensions that mean "this is really a program or a page" — a name
 * like statement.php.pdf or check.html.png is refused (OWASP double extension).
 */
const DANGEROUS_INNER_EXTS = new Set([
  "php", "php3", "php4", "php5", "phtml", "phar", "asp", "aspx", "jsp", "jspx", "cgi", "pl", "py", "rb",
  "sh", "bash", "bat", "cmd", "com", "exe", "dll", "msi", "scr", "ps1", "vbs", "vbe", "js", "mjs", "jar",
  "html", "htm", "xhtml", "svg", "xml", "hta", "lnk", "app", "dmg",
]);

// ------------------------------------------------------------- signature ----

const HEIC_BRANDS = new Set(["heic", "heix", "heim", "heis"]);

function ascii(bytes: Uint8Array, start: number, len: number): string {
  let s = "";
  for (let i = start; i < start + len && i < bytes.length; i += 1) s += String.fromCharCode(bytes[i]);
  return s;
}

/**
 * Identify the file from its first bytes. Returns null for anything that is
 * not one of the four allowed types — the caller refuses it.
 *   PDF  "%PDF-" at 0 (ISO 32000 header; all five bytes required)
 *   PNG  89 50 4E 47 0D 0A 1A 0A at 0
 *   JPEG FF D8 FF at 0
 *   HEIC "ftyp" at 4 and a heic/heix/heim/heis brand inside the ftyp box
 */
export function sniffDocMime(bytes: Uint8Array): DocMime | null {
  if (bytes.length >= 5 && ascii(bytes, 0, 5) === "%PDF-") return "application/pdf";
  const png = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  if (bytes.length >= 8 && png.every((b, i) => bytes[i] === b)) return "image/png";
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return "image/jpeg";
  if (bytes.length >= 12 && ascii(bytes, 4, 4) === "ftyp") {
    const boxLen = ((bytes[0] << 24) >>> 0) + (bytes[1] << 16) + (bytes[2] << 8) + bytes[3];
    // major brand at 8; minor version at 12..15; compatible brands from 16.
    if (HEIC_BRANDS.has(ascii(bytes, 8, 4))) return "image/heic";
    const end = Math.min(boxLen >= 16 ? boxLen : 0, bytes.length, 4096);
    for (let off = 16; off + 4 <= end; off += 4) {
      if (HEIC_BRANDS.has(ascii(bytes, off, 4))) return "image/heic";
    }
  }
  return null;
}

// -------------------------------------------------------------- filename ----

export type FilenameCheck =
  | { ok: true; display: string; ext: string }
  | { ok: false; refusal: string };

/**
 * Check the person's file name. It is never used as a storage key; it is kept
 * as display text, so it must be printable, short and not misleading.
 */
export function checkOriginalFilename(raw: string | null | undefined): FilenameCheck {
  const name = String(raw ?? "");
  // eslint-disable-next-line no-control-regex
  if (/[\u0000-\u001f\u007f]/.test(name)) return { ok: false, refusal: "The file name has hidden control characters. Rename the file and try again." };
  // OWASP: "reject any filename containing a colon" - checked on the raw name,
  // so a Windows path (C:\...) or an NTFS stream (x.pdf:evil) is refused too.
  if (name.includes(":")) return { ok: false, refusal: "File names may not contain a colon (:). Rename the file and try again." };
  // Browsers send only the base name, but strip any path a client might add.
  const base = name.split(/[\\/]/).pop()!.trim();
  if (!base) return { ok: false, refusal: "The file has no name. Rename it (for example signed-form.pdf) and try again." };
  if (base.length > MAX_ORIGINAL_FILENAME_CHARS) {
    return { ok: false, refusal: `The file name is longer than ${MAX_ORIGINAL_FILENAME_CHARS} characters. Shorten it and try again.` };
  }
  const parts = base.split(".");
  if (parts.length < 2 || !parts[parts.length - 1]) {
    return { ok: false, refusal: "The file name has no extension. Upload a .pdf, .jpg, .png or .heic file." };
  }
  const ext = parts[parts.length - 1].toLowerCase();
  for (const inner of parts.slice(1, -1)) {
    if (DANGEROUS_INNER_EXTS.has(inner.toLowerCase())) {
      return { ok: false, refusal: `The file name hides a ".${inner}" extension inside it. Rename the file and try again.` };
    }
  }
  return { ok: true, display: base, ext };
}

// ---------------------------------------------------------------- upload ----

export type UploadInput = {
  bytes: Uint8Array;
  declaredMime: string | null | undefined;
  filename: string | null | undefined;
  kind: string | null | undefined;
};

export type UploadVerdict =
  | { ok: true; mime: DocMime; kind: DocKind; ext: string; displayName: string; byteSize: number }
  | { ok: false; refusal: string };

function sizeLabel(n: number): string {
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

/** Decide whether one dropped file may be stored. Pure: no hashing, no I/O. */
export function checkDocumentUpload(input: UploadInput): UploadVerdict {
  const kind = String(input.kind ?? "") as DocKind;
  if (!UPLOADABLE_DOC_KINDS.includes(kind)) {
    return { ok: false, refusal: "Pick what the document is: signed form, voided check, bank letter, or other." };
  }
  const size = input.bytes.length;
  if (size <= 0) return { ok: false, refusal: "The file is empty. Pick the file again." };
  if (size > MAX_DOC_BYTES) {
    return { ok: false, refusal: `The file is ${sizeLabel(size)}; the limit is 25 MB. Scan at a lower resolution or upload a PDF.` };
  }
  const name = checkOriginalFilename(input.filename);
  if (!name.ok) return name;
  const mime = sniffDocMime(input.bytes);
  if (!mime) {
    return { ok: false, refusal: "This file is not a PDF, JPEG, PNG or HEIC (checked from the file itself, not its name). Upload a scan or photo in one of those formats." };
  }
  if (!ALLOWED_EXTS[mime].includes(name.ext)) {
    return {
      ok: false,
      refusal: `The file is really a ${STORAGE_EXT[mime].toUpperCase()} but is named ".${name.ext}". Rename it to .${STORAGE_EXT[mime]} and try again.`,
    };
  }
  const declared = String(input.declaredMime ?? "").trim().toLowerCase();
  if (!DECLARED_UNKNOWN.includes(declared) && !DECLARED_OK[mime].includes(declared)) {
    return { ok: false, refusal: `The browser says this file is "${declared}" but its contents are ${STORAGE_EXT[mime].toUpperCase()}. Re-save the file and try again.` };
  }
  return { ok: true, mime, kind, ext: STORAGE_EXT[mime], displayName: name.display, byteSize: size };
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export type PayeeType = "employee" | "vendor";

/**
 * App-generated storage location. `objectKey` is the key inside the ach-docs
 * bucket; `storagePath` is what the table stores (0258: like 'ach-docs/%').
 */
export function planDocumentPath(input: { payeeType: PayeeType; payeeId: string; fileUuid: string; mime: DocMime }):
  | { ok: true; objectKey: string; storagePath: string }
  | { ok: false; refusal: string } {
  if (input.payeeType !== "employee" && input.payeeType !== "vendor") return { ok: false, refusal: "Unknown payee type." };
  const payeeId = input.payeeId.toLowerCase();
  const fileUuid = input.fileUuid.toLowerCase();
  if (!UUID_RE.test(payeeId)) return { ok: false, refusal: "Unknown payee." };
  if (!UUID_RE.test(fileUuid)) return { ok: false, refusal: "Could not name the file." };
  const objectKey = `${input.payeeType}/${payeeId}/${fileUuid}.${STORAGE_EXT[input.mime]}`;
  return { ok: true, objectKey, storagePath: `ach-docs/${objectKey}` };
}

export function isSha256Hex(s: string): boolean {
  return /^[0-9a-f]{64}$/.test(s);
}

// ---------------------------------------------------------- intake state ----

const INTAKE_NEXT: Readonly<Record<IntakeStatus, readonly IntakeStatus[]>> = {
  received: ["extracted", "rekeyed", "rejected"],
  extracted: ["rekeyed", "rejected"],
  rekeyed: ["accepted", "rejected"],
  accepted: [],
  rejected: [],
};

export function canMoveIntake(from: IntakeStatus, to: IntakeStatus): boolean {
  return INTAKE_NEXT[from].includes(to);
}

export const INTAKE_LABELS: Readonly<Record<IntakeStatus, string>> = {
  received: "Received — waiting for review",
  extracted: "Draft read — waiting for blind re-key",
  rekeyed: "Re-keyed — ready to accept",
  accepted: "Accepted into the vault",
  rejected: "Rejected",
};

/** Event kinds this slice writes (0258: event_kind ~ '^[a-z][a-z_]{2,48}$'). */
export const INTAKE_EVENTS = {
  dropped: "document_dropped", // the only kind a manager may insert (0258 RLS)
  extracted: "document_extracted",
  rekeyMismatch: "document_rekey_mismatch",
  rekeyed: "document_rekeyed",
  accepted: "document_accepted",
  rejected: "document_rejected",
  archived: "document_archived",
} as const;

// ------------------------------------------------------------ the draft ----

export type DraftAccount = {
  bankName: string;
  routing: string;
  account: string;
  accountType: AccountType | null;
  rule: SplitRule | null;
};

export type BankDraft = {
  source: "acroform" | "llamaparse" | "none";
  payeeName: string;
  signedOn: string | null;
  request: "new" | "change" | "cancel" | null;
  accounts: DraftAccount[];
  warnings: string[];
};

export const EMPTY_DRAFT: BankDraft = { source: "none", payeeName: "", signedOn: null, request: null, accounts: [], warnings: [] };

export type FormFields = Readonly<Record<string, string | boolean | null | undefined>>;

function fStr(f: FormFields, k: string): string {
  const v = f[k];
  return typeof v === "string" ? v.trim() : "";
}
/** pdf.js reports a ticked box as its export value ("Yes" on our forms) or true. */
function fOn(f: FormFields, k: string): boolean {
  const v = f[k];
  if (v === true) return true;
  if (typeof v !== "string") return false;
  const t = v.trim();
  return t !== "" && t !== "Off" && t.toLowerCase() !== "false";
}

/**
 * "$1,200.50" -> fixed 120050 cents; "25%" -> 2500 bp; "12.5 %" -> 1250 bp.
 * Blank -> null. Anything else -> an error sentence (never a guess).
 */
export function parseAmountRule(text: string): { ok: true; rule: SplitRule | null } | { ok: false; error: string } {
  const t = text.trim();
  if (!t) return { ok: true, rule: null };
  const pct = /^(\d{1,2}(?:\.\d{1,2})?)\s*%$/.exec(t);
  if (pct) {
    const bp = Math.round(Number(pct[1]) * 100);
    if (bp <= 0 || bp >= 10000) return { ok: false, error: `"${t}" must be more than 0% and less than 100%.` };
    return { ok: true, rule: { kind: "percent", basisPoints: bp } };
  }
  const money = /^\$?\s*(\d{1,3}(?:,\d{3})+|\d+)(?:\.(\d{1,2}))?$/.exec(t);
  if (money) {
    const dollars = Number(money[1].replace(/,/g, ""));
    const cents = dollars * 100 + Number((money[2] ?? "0").padEnd(2, "0"));
    if (!Number.isSafeInteger(cents) || cents <= 0) return { ok: false, error: `"${t}" must be more than $0.` };
    return { ok: true, rule: { kind: "fixed", cents } };
  }
  return { ok: false, error: `"${t}" is not a dollar amount (like $200.00) or a percentage (like 25%).` };
}

function typeFrom(checking: boolean, savings: boolean, label: string, warnings: string[]): AccountType | null {
  if (checking && savings) {
    warnings.push(`${label}: both checking and savings are ticked.`);
    return null;
  }
  return checking ? "checking" : savings ? "savings" : null;
}

function digits(s: string): string {
  return s.replace(/[\s-]/g, "");
}

function requestFrom(n: boolean, c: boolean, x: boolean, warnings: string[]): BankDraft["request"] {
  const count = [n, c, x].filter(Boolean).length;
  if (count > 1) {
    warnings.push("More than one request type (new / change / cancel) is ticked.");
    return null;
  }
  return n ? "new" : c ? "change" : x ? "cancel" : null;
}

/**
 * Flatten pdf.js getFieldObjects() output ({ name: [widget, ...] }) into the
 * plain map draftFromAcroForm reads. Only text, checkbox and radio widgets
 * count (signature widgets are ignored). When a name has several widgets, the
 * first one that is filled / ticked wins; a name whose widgets DISAGREE
 * (two different filled values) is reported, never resolved by guessing.
 */
export function fieldsFromFieldObjects(raw: unknown): { fields: Record<string, string | boolean>; conflicts: string[] } {
  const fields: Record<string, string | boolean> = {};
  const conflicts: string[] = [];
  if (!raw || typeof raw !== "object") return { fields, conflicts };
  for (const [name, widgets] of Object.entries(raw as Record<string, unknown>)) {
    if (!Array.isArray(widgets) || !/^[A-Za-z0-9_]{1,64}$/.test(name)) continue;
    const seen: (string | boolean)[] = [];
    for (const w of widgets) {
      const o = (w ?? {}) as { type?: unknown; value?: unknown };
      if (o.type !== "text" && o.type !== "checkbox" && o.type !== "radiobutton") continue;
      const v = o.value;
      if (typeof v === "boolean") { if (v) seen.push(true); continue; }
      if (typeof v !== "string") continue;
      const t = v.trim();
      if (t === "" || t === "Off") continue;
      seen.push(t.slice(0, 200));
    }
    if (seen.length === 0) continue;
    if (new Set(seen.map(String)).size > 1) conflicts.push(name);
    else fields[name] = seen[0];
  }
  return { fields, conflicts };
}

/** Which of OUR fillable forms these fields came from (by field names), or null. */
export function acroFormKind(raw: unknown): PayeeType | null {
  if (!raw || typeof raw !== "object") return null;
  const names = Object.keys(raw as object);
  const emp = ["e_legal_name", "e_a1_rtn", "e_a1_acct"].every((n) => names.includes(n));
  const ven = ["v_legal_name", "v_rtn", "v_acct", "v_acct2"].every((n) => names.includes(n));
  if (emp === ven) return null;
  return emp ? "employee" : "vendor";
}

/**
 * Map the AcroForm fields of OUR fillable forms (field names read from
 * Greenway-Employee-Direct-Deposit-Authorization-FILLABLE.pdf and
 * Greenway-Vendor-ACH-Authorization-FILLABLE.pdf) into a draft. Every
 * problem becomes a warning; nothing is corrected silently.
 */
export function draftFromAcroForm(payeeType: PayeeType, f: FormFields): BankDraft {
  const warnings: string[] = [];
  const accounts: DraftAccount[] = [];
  if (payeeType === "employee") {
    for (let i = 1; i <= MAX_ACCOUNTS_PER_PAYEE; i += 1) {
      const p = `e_a${i}_`;
      const bankName = fStr(f, `${p}bank`);
      const routing = digits(fStr(f, `${p}rtn`));
      const account = digits(fStr(f, `${p}acct`));
      const amt = fStr(f, `${p}amt`);
      const rem = fOn(f, `${p}rem`);
      const chk = fOn(f, `${p}chk`);
      const sav = fOn(f, `${p}sav`);
      if (!bankName && !routing && !account && !amt && !rem && !chk && !sav) continue;
      const label = `Account ${i}`;
      const accountType = typeFrom(chk, sav, label, warnings);
      let rule: SplitRule | null = null;
      const parsed = parseAmountRule(amt);
      if (!parsed.ok) warnings.push(`${label}: ${parsed.error}`);
      if (rem && parsed.ok && parsed.rule) warnings.push(`${label}: both an amount and "remainder" are filled in.`);
      else if (rem) rule = { kind: "remainder" };
      else if (parsed.ok) rule = parsed.rule;
      if (!rule && !(rem && parsed.ok && parsed.rule)) warnings.push(`${label}: no amount, percentage or remainder is filled in.`);
      if (routing && !isValidRouting(routing)) warnings.push(`${label}: routing number fails the ABA check digit.`);
      if (!routing) warnings.push(`${label}: routing number is blank.`);
      if (!account) warnings.push(`${label}: account number is blank.`);
      if (!accountType && !(chk && sav)) warnings.push(`${label}: checking or savings is not ticked.`);
      accounts.push({ bankName, routing, account, accountType, rule });
    }
    if (accounts.length && accounts.filter((a) => a.rule?.kind === "remainder").length !== 1) {
      warnings.push("Exactly one account should receive the remainder of net pay.");
    }
    if (fOn(f, "e_pay_chk") && !fOn(f, "e_pay_dd")) warnings.push("The employee chose a paper check, not direct deposit.");
    return {
      source: "acroform",
      payeeName: fStr(f, "e_legal_name"),
      signedOn: fStr(f, "e_e_date") || null,
      request: requestFrom(fOn(f, "e_rq_new"), fOn(f, "e_rq_chg"), fOn(f, "e_rq_can"), warnings),
      accounts,
      warnings,
    };
  }
  const routing = digits(fStr(f, "v_rtn"));
  const account = digits(fStr(f, "v_acct"));
  const confirm = digits(fStr(f, "v_acct2"));
  const bankName = fStr(f, "v_bank");
  const accountType = typeFrom(fOn(f, "v_at_chk"), fOn(f, "v_at_sav"), "Account", warnings);
  if (routing || account || bankName) {
    if (!routing) warnings.push("Routing number is blank.");
    else if (!isValidRouting(routing)) warnings.push("Routing number fails the ABA check digit.");
    if (!account) warnings.push("Account number is blank.");
    if (account && confirm && account !== confirm) warnings.push("The account number and its confirmation on the form do not match.");
    if (account && !confirm) warnings.push("The account number confirmation box is blank.");
    if (!accountType && !(fOn(f, "v_at_chk") && fOn(f, "v_at_sav"))) warnings.push("Checking or savings is not ticked.");
    accounts.push({ bankName, routing, account, accountType, rule: { kind: "remainder" } });
  }
  return {
    source: "acroform",
    payeeName: fStr(f, "v_legal_name"),
    signedOn: fStr(f, "v_v_date") || null,
    request: requestFrom(fOn(f, "v_rq_new"), fOn(f, "v_rq_chg"), fOn(f, "v_rq_can"), warnings),
    accounts,
    warnings,
  };
}

/**
 * Text (LlamaParse markdown of a scan / photo) -> routing-number CANDIDATES.
 * Only 9-digit runs that pass the ABA check digit count. The draft never
 * fills an account number from free text: a check's MICR line is too easy to
 * misread, and the blind re-key is the control. Candidates are hints only.
 */
export function routingCandidatesFromText(text: string): string[] {
  const out: string[] = [];
  const re = /(?<!\d)(\d{9})(?!\d)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    if (isValidRouting(m[1]) && !out.includes(m[1])) out.push(m[1]);
  }
  return out;
}

export function draftFromParsedText(text: string): BankDraft {
  const routes = routingCandidatesFromText(text);
  const warnings = ["Read by LlamaParse from a scan. Treat every value as a guess until the blind re-key matches."];
  if (routes.length > 1) warnings.push(`More than one possible routing number was found (${routes.length}).`);
  if (routes.length === 0) warnings.push("No valid routing number was found in the scan.");
  return {
    source: "llamaparse",
    payeeName: "",
    signedOn: null,
    request: null,
    accounts: routes.length === 1 ? [{ bankName: "", routing: routes[0], account: "", accountType: null, rule: null }] : [],
    warnings,
  };
}

// --------------------------------------------------------- blind re-key ----

export type RekeyAccount = {
  routing: string;
  account: string;
  accountType: AccountType;
  rule: SplitRule;
};
export type RekeyEntry = { byId: string; accounts: RekeyAccount[] };

function ruleKey(r: SplitRule | null): string {
  if (!r) return "none";
  return r.kind === "fixed" ? `fixed:${r.cents}` : r.kind === "percent" ? `percent:${r.basisPoints}` : "remainder";
}

/**
 * Field-by-field compare. Returns only the NAMES of differing fields (never
 * the values), so a mismatch message cannot leak the draft to the person
 * re-keying.
 */
export function rekeyDifferences(
  a: readonly { routing: string; account: string; accountType: AccountType | null; rule: SplitRule | null }[],
  b: readonly { routing: string; account: string; accountType: AccountType | null; rule: SplitRule | null }[],
): string[] {
  const diffs: string[] = [];
  if (a.length !== b.length) diffs.push(`number of accounts (${a.length} vs ${b.length})`);
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i += 1) {
    const x = a[i];
    const y = b[i];
    const label = `account ${i + 1}`;
    if (digits(x.routing) !== digits(y.routing)) diffs.push(`${label} routing number`);
    if (digits(x.account) !== digits(y.account)) diffs.push(`${label} account number`);
    if (x.accountType !== y.accountType) diffs.push(`${label} checking/savings`);
    if (ruleKey(x.rule) !== ruleKey(y.rule)) diffs.push(`${label} amount`);
  }
  return diffs;
}

export function validateRekeyEntry(accounts: readonly RekeyAccount[]): string[] {
  const errs: string[] = [];
  if (accounts.length === 0) errs.push("Enter at least one account.");
  if (accounts.length > MAX_ACCOUNTS_PER_PAYEE) errs.push(`At most ${MAX_ACCOUNTS_PER_PAYEE} accounts.`);
  accounts.forEach((a, i) => {
    const label = `Account ${i + 1}`;
    const r = digits(a.routing);
    if (!/^\d{9}$/.test(r)) errs.push(`${label}: routing numbers are exactly 9 digits.`);
    else if (!isValidRouting(r)) errs.push(`${label}: routing number fails the ABA check digit.`);
    if (!/^\d{4,17}$/.test(digits(a.account))) errs.push(`${label}: account numbers are 4-17 digits.`);
    if (a.accountType !== "checking" && a.accountType !== "savings") errs.push(`${label}: pick checking or savings.`);
  });
  return errs;
}

/** A draft is usable alone only if it has no warnings and every account is complete. */
export function draftIsUsable(draft: BankDraft): boolean {
  return (
    draft.source !== "none" &&
    draft.warnings.length === 0 &&
    draft.accounts.length > 0 &&
    draft.accounts.every((a) => Boolean(a.routing && a.account && a.accountType && a.rule))
  );
}

export type RekeyVerdict =
  | { ok: true; basis: "matches_form" | "two_blind_entries"; accounts: RekeyAccount[]; note: string }
  | { ok: false; need: "fix_entry"; errors: string[] }
  | { ok: false; need: "second_entry"; reason: string; differences: string[] }
  | { ok: false; need: "form_disagrees"; reason: string; differences: string[] };

/**
 * The blind re-key rule (S5):
 *   1. The person types the bank details WITHOUT seeing the draft.
 *   2. If a usable draft exists (AcroForm or LlamaParse with every field) and
 *      the entry matches it field for field -> accepted on "matches_form".
 *   3. Otherwise a SECOND blind entry is required, and the two entries must
 *      match each other -> accepted on "two_blind_entries". (Owner Q1: Stephen
 *      and Michael can each do everything, so the second entry may be the same
 *      person; it is recorded either way.)
 * A draft is usable only if it has no warnings and every account is complete.
 */
export function rekeyVerdict(draft: BankDraft, entries: readonly RekeyEntry[]): RekeyVerdict {
  if (entries.length === 0) return { ok: false, need: "fix_entry", errors: ["Enter the bank details."] };
  for (const e of entries) {
    const errs = validateRekeyEntry(e.accounts);
    if (errs.length) return { ok: false, need: "fix_entry", errors: errs };
  }
  const first = entries[0];
  const draftUsable = draftIsUsable(draft);
  if (entries.length === 1) {
    if (!draftUsable) {
      return {
        ok: false,
        need: "second_entry",
        reason: draft.source === "none"
          ? "There is no machine-read draft to check against. Enter the details a second time, without looking at the first entry."
          : "The machine-read draft is incomplete or has warnings. Enter the details a second time, without looking at the first entry.",
        differences: [],
      };
    }
    const d = rekeyDifferences(first.accounts, draft.accounts);
    if (d.length === 0) {
      return { ok: true, basis: "matches_form", accounts: first.accounts, note: "Blind entry matched the form field for field." };
    }
    return {
      ok: false,
      need: "second_entry",
      reason: "Your entry does not match the form. Look at the document again and enter the details a second time.",
      differences: d,
    };
  }
  const second = entries[entries.length - 1];
  // A later blind entry that matches a usable form is verified on its own.
  if (draftUsable && rekeyDifferences(second.accounts, draft.accounts).length === 0) {
    return { ok: true, basis: "matches_form", accounts: second.accounts, note: "Second blind entry matched the form field for field." };
  }
  const d = rekeyDifferences(first.accounts, second.accounts);
  if (d.length) {
    return { ok: false, need: "second_entry", reason: "The two blind entries do not match. Check the document and try again.", differences: d };
  }
  // Our own fillable form is what the payee signed. If two people agree with
  // each other but not with the form's fields, the form wins: do not store
  // numbers the payee never authorized.
  if (draftUsable) {
    const vsForm = rekeyDifferences(second.accounts, draft.accounts);
    if (vsForm.length) {
      return {
        ok: false,
        need: "form_disagrees",
        reason: "Both entries agree with each other, but the form's own filled-in fields say something different. Check the form; if the form itself is wrong, reject it and ask the payee for a new one.",
        differences: vsForm,
      };
    }
  }
  const same = first.byId === second.byId;
  return {
    ok: true,
    basis: "two_blind_entries",
    accounts: second.accounts,
    note: same ? "Two blind entries by the same person matched." : "Two blind entries by different people matched.",
  };
}

/**
 * The FIRST blind entry is kept between passes only as keyed fingerprints
 * (one HMAC per field), never as numbers. ach_authorization_events is
 * append-only and can never be deleted, so plaintext or even ciphertext bank
 * numbers there would outlive the retention period. A fingerprint lets the
 * second pass name which FIELD differs without anyone being able to read it.
 */
export type EntryFingerprint = { v: 1; byId: string; accounts: { routing: string; account: string; type: string; amount: string }[] };

function canonicalFields(a: { routing: string; account: string; accountType: AccountType | null; rule: SplitRule | null }) {
  return { routing: digits(a.routing), account: digits(a.account), type: String(a.accountType), amount: ruleKey(a.rule) };
}

export function fingerprintEntry(e: RekeyEntry, hmac: (s: string) => string): EntryFingerprint {
  return {
    v: 1,
    byId: e.byId,
    accounts: e.accounts.map((a, i) => {
      const c = canonicalFields(a);
      return {
        routing: hmac(`rekey|${i}|routing|${c.routing}`),
        account: hmac(`rekey|${i}|account|${c.account}`),
        type: hmac(`rekey|${i}|type|${c.type}`),
        amount: hmac(`rekey|${i}|amount|${c.amount}`),
      };
    }),
  };
}

export function parseFingerprint(raw: unknown): EntryFingerprint | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as { v?: unknown; byId?: unknown; accounts?: unknown };
  if (o.v !== 1 || typeof o.byId !== "string" || !Array.isArray(o.accounts) || o.accounts.length > MAX_ACCOUNTS_PER_PAYEE) return null;
  const accounts: EntryFingerprint["accounts"] = [];
  for (const a of o.accounts as unknown[]) {
    const x = (a ?? {}) as Record<string, unknown>;
    const ks = ["routing", "account", "type", "amount"] as const;
    if (!ks.every((k) => typeof x[k] === "string" && isSha256Hex(x[k] as string))) return null;
    accounts.push({ routing: x.routing as string, account: x.account as string, type: x.type as string, amount: x.amount as string });
  }
  return { v: 1, byId: o.byId, accounts };
}

export function fingerprintDifferences(a: EntryFingerprint, b: EntryFingerprint): string[] {
  const diffs: string[] = [];
  if (a.accounts.length !== b.accounts.length) diffs.push(`number of accounts (${a.accounts.length} vs ${b.accounts.length})`);
  const n = Math.min(a.accounts.length, b.accounts.length);
  for (let i = 0; i < n; i += 1) {
    const label = `account ${i + 1}`;
    if (a.accounts[i].routing !== b.accounts[i].routing) diffs.push(`${label} routing number`);
    if (a.accounts[i].account !== b.accounts[i].account) diffs.push(`${label} account number`);
    if (a.accounts[i].type !== b.accounts[i].type) diffs.push(`${label} checking/savings`);
    if (a.accounts[i].amount !== b.accounts[i].amount) diffs.push(`${label} amount`);
  }
  return diffs;
}

export type RekeyStep =
  | RekeyVerdict
  | { ok: false; need: "second_entry"; reason: string; differences: string[]; keepPending: EntryFingerprint };

/**
 * One pass of the blind re-key, as the server runs it: `pending` is the
 * fingerprint of the previous unmatched entry (or null). Same rules as
 * rekeyVerdict (a parity test runs both over the same scenarios):
 *   - an entry that matches a usable draft is accepted on "matches_form";
 *   - otherwise it must match the previous entry; if it does not, it becomes
 *     the new pending entry (two CONSECUTIVE agreeing entries are needed);
 *   - two agreeing entries that disagree with a usable draft are refused.
 */
export function rekeyStep(
  draft: BankDraft,
  pending: EntryFingerprint | null,
  current: RekeyEntry,
  hmac: (s: string) => string,
): RekeyStep {
  const errs = validateRekeyEntry(current.accounts);
  if (errs.length) return { ok: false, need: "fix_entry", errors: errs };
  const usable = draftIsUsable(draft);
  if (usable && rekeyDifferences(current.accounts, draft.accounts).length === 0) {
    return {
      ok: true,
      basis: "matches_form",
      accounts: current.accounts,
      note: pending ? "Second blind entry matched the form field for field." : "Blind entry matched the form field for field.",
    };
  }
  const fp = fingerprintEntry(current, hmac);
  if (!pending) {
    if (!usable) {
      return {
        ok: false,
        need: "second_entry",
        reason: draft.source === "none"
          ? "There is no machine-read draft to check against. Enter the details a second time, without looking at the first entry."
          : "The machine-read draft is incomplete or has warnings. Enter the details a second time, without looking at the first entry.",
        differences: [],
        keepPending: fp,
      };
    }
    return {
      ok: false,
      need: "second_entry",
      reason: "Your entry does not match the form. Look at the document again and enter the details a second time.",
      differences: rekeyDifferences(current.accounts, draft.accounts),
      keepPending: fp,
    };
  }
  const d = fingerprintDifferences(pending, fp);
  if (d.length) {
    return { ok: false, need: "second_entry", reason: "The two blind entries do not match. Check the document and try again.", differences: d, keepPending: fp };
  }
  if (usable) {
    return {
      ok: false,
      need: "form_disagrees",
      reason: "Both entries agree with each other, but the form's own filled-in fields say something different. Check the form; if the form itself is wrong, reject it and ask the payee for a new one.",
      differences: rekeyDifferences(current.accounts, draft.accounts),
    };
  }
  return {
    ok: true,
    basis: "two_blind_entries",
    accounts: current.accounts,
    note: pending.byId === current.byId ? "Two blind entries by the same person matched." : "Two blind entries by different people matched.",
  };
}

/** Roles allowed to drop documents: mirrors public.is_manager() (0130). */
export const DROP_ROLES = ["owner", "admin", "manager"] as const;
/** Roles allowed to read, re-key and accept: mirrors public.is_admin() (0001). */
export const REVIEW_ROLES = ["owner", "admin"] as const;
export function canDropDocuments(role: string | null | undefined): boolean {
  return (DROP_ROLES as readonly string[]).includes(String(role ?? ""));
}
export function canReviewDocuments(role: string | null | undefined): boolean {
  return (REVIEW_ROLES as readonly string[]).includes(String(role ?? ""));
}

/**
 * Read one blind entry from a form post. Fields per row i (1..3):
 * a{i}_rtn, a{i}_acct, a{i}_type (checking|savings), a{i}_how
 * (remainder|fixed|percent), a{i}_amt. A row with no routing and no account
 * is skipped. Problems are sentences; nothing is guessed.
 */
export function entryFromForm(get: (k: string) => string, payeeType: PayeeType): { ok: true; accounts: RekeyAccount[]; bankNames: string[] } | { ok: false; errors: string[] } {
  const errors: string[] = [];
  const accounts: RekeyAccount[] = [];
  const bankNames: string[] = [];
  const rows = payeeType === "vendor" ? 1 : MAX_ACCOUNTS_PER_PAYEE;
  for (let i = 1; i <= rows; i += 1) {
    const routing = digits(get(`a${i}_rtn`));
    const account = digits(get(`a${i}_acct`));
    if (!routing && !account) continue;
    const label = `Account ${i}`;
    const type = get(`a${i}_type`).trim();
    const how = payeeType === "vendor" ? "remainder" : get(`a${i}_how`).trim();
    let rule: SplitRule | null = null;
    if (how === "remainder") rule = { kind: "remainder" };
    else if (how === "fixed" || how === "percent") {
      const raw = get(`a${i}_amt`).trim();
      const parsed = parseAmountRule(how === "percent" && raw && !raw.endsWith("%") ? `${raw}%` : raw);
      if (!parsed.ok) errors.push(`${label}: ${parsed.error}`);
      else if (!parsed.rule) errors.push(`${label}: enter the amount.`);
      else if (parsed.rule.kind !== how) errors.push(`${label}: the amount does not match "${how === "fixed" ? "fixed dollar amount" : "percentage"}".`);
      else rule = parsed.rule;
    } else errors.push(`${label}: pick how much goes to this account.`);
    if (type !== "checking" && type !== "savings") errors.push(`${label}: pick checking or savings.`);
    if (rule && (type === "checking" || type === "savings")) {
      accounts.push({ routing, account, accountType: type, rule });
      bankNames.push(get(`a${i}_bank`).trim());
    }
  }
  if (errors.length) return { ok: false, errors };
  return { ok: true, accounts, bankNames };
}

// ---------------------------------------------------------------- accept ----

/** Payee-specific checks before anything is written. */
export function acceptChecks(payeeType: PayeeType, accounts: readonly RekeyAccount[]): string[] {
  const errs: string[] = [];
  if (payeeType === "vendor") {
    if (accounts.length !== 1) errs.push("A vendor is paid into exactly one account.");
    if (accounts[0] && accounts[0].rule.kind !== "remainder") errs.push("A vendor's single account receives the whole payment.");
    return errs;
  }
  const keys = accounts.map((a) => `${digits(a.routing)}|${digits(a.account).replace(/^0+(?=.)/, "")}|${a.accountType}`);
  if (new Set(keys).size !== keys.length) errs.push("The same account is listed twice.");
  if (accounts.filter((a) => a.rule.kind === "remainder").length !== 1) errs.push("Exactly one account must receive the remainder of net pay.");
  let bp = 0;
  for (const a of accounts) {
    if (a.rule.kind === "fixed" && (!Number.isSafeInteger(a.rule.cents) || a.rule.cents <= 0)) errs.push("A fixed amount must be more than $0.");
    if (a.rule.kind === "percent") {
      if (!Number.isInteger(a.rule.basisPoints) || a.rule.basisPoints < 1 || a.rule.basisPoints > 9999) errs.push("A percentage must be between 0.01% and 99.99%.");
      bp += a.rule.basisPoints;
    }
  }
  if (bp >= 10000) errs.push("Percentages add up to 100% or more, leaving nothing for the remainder account.");
  return errs;
}

/**
 * The date the payee signed (YYYY-MM-DD). Not in the future, not before 2000
 * (0258: ended_on >= signed_on, retention counts from it).
 */
export function checkSignedOn(raw: string | null | undefined, todayIso: string): { ok: true; date: string } | { ok: false; error: string } {
  const t = String(raw ?? "").trim();
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(t);
  if (!m) return { ok: false, error: "Enter the date the form was signed (YYYY-MM-DD)." };
  const d = new Date(`${t}T00:00:00Z`);
  if (Number.isNaN(d.getTime()) || d.toISOString().slice(0, 10) !== t) return { ok: false, error: `"${t}" is not a real date.` };
  if (t > todayIso.slice(0, 10)) return { ok: false, error: "The signed date cannot be in the future." };
  if (Number(m[1]) < 2000) return { ok: false, error: "The signed date is too far in the past; check the form." };
  return { ok: true, date: t };
}

/** Last 4 of the account for display (0258: ^[0-9A-Za-z]{1,4}$). */
export function last4(s: string): string {
  return digits(s).slice(-4);
}

export type AccountRow = {
  priority: number;
  rule_kind: "fixed" | "percent" | "remainder";
  fixed_cents: number | null;
  basis_points: number | null;
  bank_name: string;
  routing_enc: string;
  account_enc: string;
  account_type: AccountType;
  account_last4: string;
  routing_last4: string;
  account_key_hmac: string;
};

/**
 * Map accepted accounts to ach_authorization_accounts rows, satisfying the
 * 0258 CHECKs (rule shape, encv1 ciphertext, last-4 shapes, hex HMAC). The
 * caller passes the crypto so this stays pure and testable.
 */
export function planAccountRows(
  accounts: readonly RekeyAccount[],
  bankNames: readonly string[],
  crypto: { encrypt: (s: string) => string; hmacKey: (routing: string, account: string, type: AccountType) => string },
): { ok: true; rows: AccountRow[] } | { ok: false; error: string } {
  const rows: AccountRow[] = [];
  for (let i = 0; i < accounts.length; i += 1) {
    const a = accounts[i];
    const routing = digits(a.routing);
    const account = digits(a.account);
    const routingEnc = crypto.encrypt(routing);
    const accountEnc = crypto.encrypt(account);
    if (!routingEnc.startsWith("encv1:") || !accountEnc.startsWith("encv1:")) {
      return { ok: false, error: "Bank numbers cannot be stored: DATA_ENCRYPTION_KEY is not set on the server." };
    }
    const hmac = crypto.hmacKey(routing, account, a.accountType);
    if (!isSha256Hex(hmac)) return { ok: false, error: "Could not fingerprint the account (HMAC)." };
    rows.push({
      priority: i + 1,
      rule_kind: a.rule.kind,
      fixed_cents: a.rule.kind === "fixed" ? a.rule.cents : null,
      basis_points: a.rule.kind === "percent" ? a.rule.basisPoints : null,
      bank_name: (bankNames[i] ?? "").trim().slice(0, 120),
      routing_enc: routingEnc,
      account_enc: accountEnc,
      account_type: a.accountType,
      account_last4: last4(account),
      routing_last4: routing.slice(-4),
      account_key_hmac: hmac,
    });
  }
  return { ok: true, rows };
}

// ------------------------------------------------------------ self-tests ----

export function __runAchDocumentIntakeTests(): { passed: number; failed: number } {
  let passed = 0;
  let failed = 0;
  const ok = (cond: boolean, name: string) => {
    if (cond) passed += 1;
    else {
      failed += 1;
      console.error(`ach-document-intake FAIL: ${name}`);
    }
  };
  const enc = (s: string) => new TextEncoder().encode(s);
  const heic = (major: string, compat: string[]) => {
    const body = enc(`ftyp${major}\0\0\0\0${compat.join("")}`);
    const len = 4 + body.length;
    return new Uint8Array([0, 0, 0, len, ...body, 0, 0, 0, 8]);
  };

  // signatures
  ok(sniffDocMime(enc("%PDF-1.7\n")) === "application/pdf", "pdf");
  ok(sniffDocMime(enc("%PDF")) === null && sniffDocMime(enc("%PDX-1")) === null, "pdf needs all 5 bytes");
  ok(sniffDocMime(new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0])) === "image/png", "png");
  ok(sniffDocMime(new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0b])) === null, "png last byte");
  ok(sniffDocMime(new Uint8Array([0xff, 0xd8, 0xff, 0xe0])) === "image/jpeg", "jpeg");
  ok(sniffDocMime(new Uint8Array([0xff, 0xd8, 0xfe])) === null, "jpeg third byte");
  ok(sniffDocMime(heic("heic", ["mif1", "miaf", "MiHB", "heic"])) === "image/heic", "iphone heic");
  ok(sniffDocMime(heic("mif1", ["mif1", "heic", "hevc"])) === "image/heic", "libheif mif1 major, heic compatible");
  ok(sniffDocMime(heic("heix", ["mif1", "heix"])) === "image/heic", "canon heix");
  ok(sniffDocMime(heic("mif1", ["mif1", "avif"])) === null, "avif is not heic");
  ok(sniffDocMime(heic("isom", ["isom", "mp41"])) === null, "mp4 is not heic");
  ok(sniffDocMime(enc("<html><body>")) === null && sniffDocMime(new Uint8Array()) === null, "html / empty");

  // filenames
  ok(checkOriginalFilename("Signed Form.PDF").ok && (checkOriginalFilename("Signed Form.PDF") as { ext: string }).ext === "pdf", "ext lowercased");
  ok(!checkOriginalFilename("a:b.pdf").ok, "colon refused");
  ok(!checkOriginalFilename("a\u0000.pdf").ok, "null byte refused");
  ok(!checkOriginalFilename("statement.php.pdf").ok && !checkOriginalFilename("x.HTML.png").ok, "dangerous inner ext");
  ok(checkOriginalFilename("form.v2.final.pdf").ok, "harmless dots ok");
  ok(!checkOriginalFilename("noext").ok && !checkOriginalFilename("trailing.").ok, "no extension");
  ok((checkOriginalFilename("C:\\Users\\x\\scan.jpg") as { ok: boolean }).ok === false, "windows path with colon refused");
  ok((checkOriginalFilename("../../etc/scan.jpg") as { display: string }).display === "scan.jpg", "path stripped");
  ok(!checkOriginalFilename("a".repeat(181) + ".pdf").ok && checkOriginalFilename("a".repeat(176) + ".pdf").ok, "length limit 180");

  // upload verdict
  const pdf = enc("%PDF-1.4 hello");
  ok(checkDocumentUpload({ bytes: pdf, declaredMime: "application/pdf", filename: "f.pdf", kind: "signed_form" }).ok, "good pdf");
  ok(!checkDocumentUpload({ bytes: pdf, declaredMime: "application/pdf", filename: "f.pdf", kind: "esign_certificate" }).ok, "esign cert not uploadable");
  ok(!checkDocumentUpload({ bytes: pdf, declaredMime: "", filename: "f.jpg", kind: "other" }).ok, "pdf named .jpg refused");
  ok(!checkDocumentUpload({ bytes: pdf, declaredMime: "image/png", filename: "f.pdf", kind: "other" }).ok, "declared type disagrees");
  ok(checkDocumentUpload({ bytes: pdf, declaredMime: "application/octet-stream", filename: "f.pdf", kind: "other" }).ok, "octet-stream ok");
  ok(!checkDocumentUpload({ bytes: new Uint8Array(), declaredMime: "", filename: "f.pdf", kind: "other" }).ok, "empty");
  ok(!checkDocumentUpload({ bytes: enc("MZ\x90\x00"), declaredMime: "", filename: "f.pdf", kind: "other" }).ok, "exe named pdf");
  const h = checkDocumentUpload({ bytes: heic("heic", ["mif1"]), declaredMime: "image/heif", filename: "IMG_1.HEIC", kind: "voided_check" });
  ok(h.ok && h.mime === "image/heic" && h.ext === "heic", "heic upload");

  // path
  const pid = "1b4e28ba-2fa1-41d2-883f-0016d3cca427";
  const fid = "6f1c0c9e-8f3a-4d2b-9a1e-2b7c3d4e5f60";
  const p = planDocumentPath({ payeeType: "vendor", payeeId: pid, fileUuid: fid, mime: "image/jpeg" });
  ok(p.ok && p.storagePath === `ach-docs/vendor/${pid}/${fid}.jpg` && p.objectKey === `vendor/${pid}/${fid}.jpg`, "path shape");
  ok(!planDocumentPath({ payeeType: "vendor", payeeId: "../x", fileUuid: fid, mime: "image/jpeg" }).ok, "payee id must be uuid");
  ok(!planDocumentPath({ payeeType: "vendor", payeeId: pid, fileUuid: "x", mime: "image/jpeg" }).ok, "file id must be uuid");
  ok(isSha256Hex("a".repeat(64)) && !isSha256Hex("A".repeat(64)) && !isSha256Hex("a".repeat(63)), "sha hex");

  // intake
  ok(canMoveIntake("received", "extracted") && canMoveIntake("received", "rekeyed") && canMoveIntake("rekeyed", "accepted"), "forward moves");
  ok(!canMoveIntake("received", "accepted") && !canMoveIntake("extracted", "accepted"), "no accept without re-key");
  ok(!canMoveIntake("accepted", "rejected") && !canMoveIntake("rejected", "received"), "terminal");
  ok(Object.values(INTAKE_EVENTS).every((k) => /^[a-z][a-z_]{2,48}$/.test(k)), "event kinds match 0258 regex");

  // amounts
  const fx = parseAmountRule("$1,200.50");
  ok(fx.ok && fx.rule?.kind === "fixed" && fx.rule.cents === 120050, "money with comma");
  const fx2 = parseAmountRule("200.5");
  ok(fx2.ok && fx2.rule?.kind === "fixed" && fx2.rule.cents === 20050, "200.5 = $200.50");
  const pc = parseAmountRule("12.5 %");
  ok(pc.ok && pc.rule?.kind === "percent" && pc.rule.basisPoints === 1250, "percent");
  ok(!parseAmountRule("100%").ok && !parseAmountRule("0%").ok && !parseAmountRule("$0").ok, "bounds");
  ok(!parseAmountRule("about 200").ok && !parseAmountRule("1,20").ok, "no guessing");
  const blank = parseAmountRule("  ");
  ok(blank.ok && blank.rule === null, "blank");

  // acroform employee
  const goodRtn = "021000021";
  const emp = draftFromAcroForm("employee", {
    e_legal_name: "Pat Doe", e_e_date: "2025-01-02", e_rq_new: "Yes", e_pay_dd: "Yes",
    e_a1_bank: "B", e_a1_rtn: goodRtn, e_a1_acct: "1234 5678", e_a1_chk: "Yes", e_a1_amt: "$200",
    e_a2_rtn: goodRtn, e_a2_acct: "999999", e_a2_sav: "Yes", e_a2_rem: "Yes",
  });
  ok(emp.warnings.length === 0 && emp.accounts.length === 2 && emp.request === "new", "employee clean draft");
  ok(emp.accounts[0].account === "12345678" && emp.accounts[0].rule?.kind === "fixed" && emp.accounts[1].rule?.kind === "remainder", "employee draft values");
  const empBad = draftFromAcroForm("employee", { e_a1_rtn: "123456789", e_a1_acct: "1", e_a1_chk: "Yes", e_a1_sav: "Yes", e_a1_amt: "$5", e_a1_rem: "Yes" });
  ok(empBad.warnings.some((w) => w.includes("check digit")) && empBad.warnings.some((w) => w.includes("both checking")) && empBad.warnings.some((w) => w.includes("both an amount")), "employee warnings");
  ok(draftFromAcroForm("employee", { e_rq_new: "Yes", e_rq_can: "Yes" }).request === null, "two requests -> null + warning");

  // acroform vendor
  const ven = draftFromAcroForm("vendor", { v_legal_name: "Acme", v_bank: "B", v_rtn: goodRtn, v_acct: "55555", v_acct2: "55555", v_at_chk: "Yes", v_rq_new: "Yes" });
  ok(ven.warnings.length === 0 && ven.accounts.length === 1 && ven.accounts[0].rule?.kind === "remainder", "vendor clean");
  ok(draftFromAcroForm("vendor", { v_rtn: goodRtn, v_acct: "55555", v_acct2: "55556", v_at_chk: "Yes" }).warnings.some((w) => w.includes("do not match")), "vendor confirm mismatch");
  ok(draftFromAcroForm("vendor", {}).accounts.length === 0, "blank vendor form");

  // text
  ok(routingCandidatesFromText(`MICR \u2446${goodRtn}\u2446 1234\u2448`).join() === goodRtn, "MICR routing found");
  ok(routingCandidatesFromText("call 1234567890 or 123456789").length === 0, "invalid / 10-digit ignored");
  ok(draftFromParsedText(goodRtn).accounts[0].account === "" && draftFromParsedText(goodRtn).warnings.length >= 1, "text draft never usable alone");

  // re-key
  const A: RekeyAccount = { routing: goodRtn, account: "12345678", accountType: "checking", rule: { kind: "fixed", cents: 20000 } };
  const B: RekeyAccount = { routing: goodRtn, account: "999999", accountType: "savings", rule: { kind: "remainder" } };
  const v1 = rekeyVerdict(emp, [{ byId: "s", accounts: [A, B] }]);
  ok(v1.ok && v1.basis === "matches_form", "matches form");
  const v2 = rekeyVerdict(emp, [{ byId: "s", accounts: [{ ...A, account: "12345679" }, B] }]);
  ok(!v2.ok && v2.need === "second_entry" && v2.differences.join() === "account 1 account number", "mismatch names field only");
  ok(!v2.ok && v2.need === "second_entry" && !JSON.stringify(v2).includes("12345678"), "mismatch never leaks the draft");
  const v3 = rekeyVerdict(EMPTY_DRAFT, [{ byId: "s", accounts: [A, B] }]);
  ok(!v3.ok && v3.need === "second_entry", "no draft -> second entry");
  const v4 = rekeyVerdict(EMPTY_DRAFT, [{ byId: "s", accounts: [A, B] }, { byId: "m", accounts: [A, B] }]);
  ok(v4.ok && v4.basis === "two_blind_entries" && v4.note.includes("different"), "two entries match");
  const v5 = rekeyVerdict(EMPTY_DRAFT, [{ byId: "s", accounts: [A, B] }, { byId: "s", accounts: [A, { ...B, accountType: "checking" }] }]);
  ok(!v5.ok && v5.need === "second_entry" && v5.differences.join() === "account 2 checking/savings", "two entries differ");
  const v6 = rekeyVerdict(emp, [{ byId: "s", accounts: [{ ...A, routing: "123456789" }] }]);
  ok(!v6.ok && v6.need === "fix_entry", "bad routing must be fixed first");
  ok(!rekeyVerdict(empBad, [{ byId: "s", accounts: [A] }]).ok, "draft with warnings is not usable alone");
  const v7 = rekeyVerdict(EMPTY_DRAFT, [{ byId: "s", accounts: [A] }, { byId: "s", accounts: [A] }]);
  ok(v7.ok && v7.note.includes("same person"), "same person recorded");

  // accept
  ok(acceptChecks("vendor", [B]).length === 0 && acceptChecks("vendor", [A]).length === 1 && acceptChecks("vendor", [B, B]).length >= 1, "vendor one remainder account");
  ok(acceptChecks("employee", [A, B]).length === 0, "employee split ok");
  ok(acceptChecks("employee", [B, { ...B, account: "0999999" }]).some((e) => e.includes("twice")), "leading zero is the same account");
  ok(acceptChecks("employee", [A]).some((e) => e.includes("remainder")), "employee needs a remainder");
  ok(acceptChecks("employee", [{ ...A, rule: { kind: "percent", basisPoints: 6000 } }, { ...A, account: "77777", rule: { kind: "percent", basisPoints: 4000 } }, B]).some((e) => e.includes("100%")), "percent sum");
  ok(checkSignedOn("2026-02-30", "2026-03-01T00:00:00Z").ok === false && checkSignedOn("2026-03-02", "2026-03-01").ok === false, "signed date real + not future");
  const sd = checkSignedOn(" 2026-03-01 ", "2026-03-01T10:00:00Z");
  ok(sd.ok && sd.date === "2026-03-01" && !checkSignedOn("1999-12-31", "2026-01-01").ok, "signed date today ok / too old");
  const rowsOk = planAccountRows([A, B], ["Bank A"], { encrypt: (s) => `encv1:x:${s.length}`, hmacKey: () => "a".repeat(64) });
  ok(rowsOk.ok && rowsOk.rows[0].fixed_cents === 20000 && rowsOk.rows[0].basis_points === null && rowsOk.rows[1].rule_kind === "remainder" && rowsOk.rows[1].fixed_cents === null, "row rule shape");
  ok(rowsOk.ok && rowsOk.rows[0].account_last4 === "5678" && rowsOk.rows[0].routing_last4 === "0021" && rowsOk.rows[1].priority === 2 && rowsOk.rows[1].bank_name === "", "row last4 + priority");
  ok(!planAccountRows([A], [], { encrypt: (s) => s, hmacKey: () => "a".repeat(64) }).ok, "plaintext refused (no key)");
  ok(!planAccountRows([A], [], { encrypt: (s) => `encv1:${s}`, hmacKey: () => "nothex" }).ok, "bad hmac refused");

  // form wins over two agreeing entries
  const vf = rekeyVerdict(emp, [{ byId: "s", accounts: [{ ...A, account: "11" + A.account }, B] }, { byId: "m", accounts: [{ ...A, account: "11" + A.account }, B] }]);
  ok(!vf.ok && vf.need === "form_disagrees" && vf.differences.join() === "account 1 account number", "form disagrees");
  const vfOk = rekeyVerdict(emp, [{ byId: "s", accounts: [{ ...A, account: "11111111" }, B] }, { byId: "m", accounts: [A, B] }]);
  ok(vfOk.ok && vfOk.basis === "matches_form", "second entry matching form after a wrong first is fine");

  // roles mirror is_manager / is_admin
  ok(canDropDocuments("manager") && canDropDocuments("owner") && !canDropDocuments("content_editor") && !canDropDocuments("staff") && !canDropDocuments(null), "drop roles");
  ok(canReviewDocuments("admin") && !canReviewDocuments("manager"), "review roles");

  // fingerprints + server step (parity with rekeyVerdict)
  const hm = (x: string) => {
    let h = 0;
    for (let i = 0; i < x.length; i += 1) h = (h * 31 + x.charCodeAt(i)) >>> 0;
    return h.toString(16).padStart(8, "0").repeat(8);
  };
  const ent: RekeyEntry = { byId: "u1", accounts: [A, { ...B, rule: { kind: "percent", basisPoints: 2500 } }] };
  const fpr = fingerprintEntry(ent, hm);
  ok(!JSON.stringify(fpr).includes("12345678") && !JSON.stringify(fpr).includes(goodRtn), "fingerprint holds no numbers");
  ok(parseFingerprint(JSON.parse(JSON.stringify(fpr))) !== null && parseFingerprint({ v: 1, byId: "x", accounts: [{ routing: "zz" }] }) === null, "fingerprint parse");
  ok(fingerprintDifferences(fpr, fingerprintEntry({ byId: "u2", accounts: [{ ...A, account: "1234 5678" }, { ...B, rule: { kind: "percent", basisPoints: 2500 } }] }, hm)).length === 0, "fingerprint ignores spaces");
  ok(fingerprintDifferences(fpr, fingerprintEntry({ byId: "u2", accounts: [{ ...A, accountType: "savings" }, B] }, hm)).join() === "account 1 checking/savings,account 2 amount", "fingerprint names fields");
  const s1 = rekeyStep(EMPTY_DRAFT, null, { byId: "s", accounts: [A] }, hm);
  ok(!s1.ok && s1.need === "second_entry" && "keepPending" in s1, "step 1 keeps pending");
  const s2 = rekeyStep(EMPTY_DRAFT, "keepPending" in s1 ? s1.keepPending : null, { byId: "m", accounts: [A] }, hm);
  ok(s2.ok && s2.basis === "two_blind_entries" && s2.note.includes("different"), "step 2 matches");
  const s3 = rekeyStep(emp, null, { byId: "s", accounts: [A, B] }, hm);
  ok(s3.ok && s3.basis === "matches_form", "step matches form");
  const s4a = rekeyStep(emp, null, { byId: "s", accounts: [{ ...A, account: "11111111" }, B] }, hm);
  const s4 = rekeyStep(emp, "keepPending" in s4a ? s4a.keepPending : null, { byId: "s", accounts: [{ ...A, account: "11111111" }, B] }, hm);
  ok(!s4.ok && s4.need === "form_disagrees", "step form disagrees");

  // form post
  const post = (o: Record<string, string>) => (k: string) => o[k] ?? "";
  const fe = entryFromForm(post({ a1_rtn: goodRtn, a1_acct: "1234-5678", a1_type: "checking", a1_how: "fixed", a1_amt: "200", a2_rtn: goodRtn, a2_acct: "999999", a2_type: "savings", a2_how: "remainder" }), "employee");
  ok(fe.ok && fe.accounts.length === 2 && fe.accounts[0].account === "12345678" && fe.accounts[0].rule.kind === "fixed", "form entry");
  const fp = entryFromForm(post({ a1_rtn: goodRtn, a1_acct: "1234", a1_type: "checking", a1_how: "percent", a1_amt: "25" }), "employee");
  ok(fp.ok && fp.accounts[0].rule.kind === "percent" && (fp.accounts[0].rule as { basisPoints: number }).basisPoints === 2500, "percent without % sign");
  ok(!entryFromForm(post({ a1_rtn: goodRtn, a1_acct: "1234", a1_type: "checking", a1_how: "fixed", a1_amt: "25%" }), "employee").ok, "fixed with % refused");
  ok(!entryFromForm(post({ a1_rtn: goodRtn, a1_acct: "1234", a1_how: "remainder" }), "employee").ok, "type required");
  const fv = entryFromForm(post({ a1_rtn: goodRtn, a1_acct: "1234", a1_type: "savings", a2_rtn: goodRtn, a2_acct: "5", a2_type: "checking" }), "vendor");
  ok(fv.ok && fv.accounts.length === 1 && fv.accounts[0].rule.kind === "remainder", "vendor: one row, whole payment");

  console.log(`ach-document-intake: ${passed} passed, ${failed} failed`);
  return { passed, failed };
}
