/**
 * scripts/compliance/run-pure-selftests.ts
 *
 * Runs the embedded self-tests of the PURE compliance/money modules. Exits
 * non-zero on any failure. Run with:  npx tsx scripts/compliance/run-pure-selftests.ts
 */
import { __runOrderPricingTests } from "../../src/lib/orders/order-pricing-core";
import { __runDiscountEngineTests } from "../../src/lib/promotions/discount-engine-core";
import { __runPromoGuardTests } from "../../src/lib/promotions/promo-guard-core";
import { __runSalesLimitTests } from "../../src/lib/compliance/sales-limits-core";
import { __runSalesLimitGateTests } from "../../src/lib/compliance/sales-limit-gate-core";
import { __runChunkedInTests } from "../../src/lib/supabase/chunked-in";
import { __runExemptSaleRecordTests } from "../../src/lib/medical/exempt-sale-record-core";
import { __runSalesHoursCoreTests } from "../../src/lib/compliance/sales-hours-core";
import { __runReceiptCoreTests } from "../../src/lib/printing/receipt-core";
import { __runPinHashTests } from "../../src/lib/security/pin-hash";
import { __runAtRestCryptoTests } from "../../src/lib/security/at-rest-crypto";
import { __runEngineTests } from "../../src/lib/loyalty/engine";
import { __runLoyaltyConfigTests } from "../../src/lib/loyalty/loyalty-config-core";
import { __runLoyaltySaleTests } from "../../src/lib/loyalty/loyalty-sale-core";
import { __runSignupCustomerTests } from "../../src/lib/loyalty/signup-customer-core";
import { __runScheduleCoreTests } from "../../src/lib/staffing/schedule-core";
import { __runEmployeeLifecycleTests } from "../../src/lib/staffing/employee-lifecycle-core";
import { __runUserGuardTests } from "../../src/lib/auth/user-guards-core";
import { __runCampaignRulesTests } from "../../src/lib/marketing/campaign-rules-core";
import { __runCompetitivePlaybookTests } from "../../src/lib/marketing/competitive-playbook-core";
import { __runMidjourneyCoreTests } from "../../src/lib/marketing/midjourney-core";
import { __runFluxCoreTests } from "../../src/lib/marketing/flux-core";
import { __runCreativePlacementsTests } from "../../src/lib/marketing/creative-placements-core";
import { __runCcrsWeekTests } from "../../src/lib/compliance/ccrs-week-core";
import { __runCcrsDeadlineTests } from "../../src/lib/compliance/ccrs-deadline-core";
import { __runCcrsErrorTriageTests } from "../../src/lib/compliance/ccrs-error-triage-core";
import { __runMenuFeedTests } from "../../src/lib/syndication/menu-feed-core";
import { __runLeaflyPayloadTests } from "../../src/lib/leafly/payload-core";
import { __runWmPayloadTests } from "../../src/lib/weedmaps/payload-core";
import { __runIntegrationCredentialsTests } from "../../src/lib/integrations/integration-credentials-core";
import { __runSyncPlanTests } from "../../src/lib/syndication/sync-plan-core";
import { __runPreflightTests } from "../../src/lib/syndication/preflight-core";
import { __runRichnessTests } from "../../src/lib/syndication/richness-core";
import { __runSyncSettingsTests } from "../../src/lib/syndication/sync-settings-core";
import { __runApplySettingsTests } from "../../src/lib/syndication/apply-settings-core";
import { __runSyndicationPlaybookTests } from "../../src/lib/integrations/syndication-playbook";
import { __runPosSaleEventTests } from "../../src/lib/pos/sale-event-core";
import { __runIdScanCoreTests } from "../../src/lib/pos/id-scan-core";
import { __runPosSyncCoreTests } from "../../src/lib/pos/sync-core";
import { __runRegisterClientCoreTests } from "../../src/lib/pos/register-client-core";
import { __runRegisterPolishCoreTests } from "../../src/lib/pos/register-polish-core";
import { __runSaleFlowCoreTests } from "../../src/lib/pos/sale-flow-core";
import { __runMedicalPosCoreTests } from "../../src/lib/pos/medical-pos-core";
import { __runPosReceiptCoreTests } from "../../src/lib/pos/receipt-core";
import { __runReceiptConfigCoreTests } from "../../src/lib/pos/receipt-config-core";
import { __runPosReturnsCoreTests } from "../../src/lib/pos/returns-core";
import { __runSaleDecrementCoreTests } from "../../src/lib/inventory/sale-decrement-core";
import { __runTillCoreTests } from "../../src/lib/pos/till-core";
import { __runDayReportCoreTests } from "../../src/lib/pos/day-report-core";
import { __runPriceDriftCoreTests } from "../../src/lib/pos/price-drift-core";
import { __runExceptionReminderCoreTests } from "../../src/lib/pos/exception-reminder-core";
import { __runRecallHoldCoreTests } from "../../src/lib/pos/recall-hold-core";
import { __runPinThrottleCoreTests } from "../../src/lib/security/pin-throttle-core";
import { __runScanToCartCoreTests } from "../../src/lib/pos/scan-to-cart-core";
import { __runVariantLotCoreTests } from "../../src/lib/pos/variant-lot-core";
import { __runIntakeMasteringCoreTests } from "../../src/lib/pos/intake-mastering-core";
import { __runIntakeMenuStagingCoreTests } from "../../src/lib/pos/intake-menu-staging-core";
import { __runPriceOverrideCoreTests } from "../../src/lib/pos/price-override-core";
import { __runDeviceSetupCoreTests } from "../../src/lib/pos/device-setup-core";
import { __runVoidSaleCoreTests } from "../../src/lib/pos/void-sale-core";
import { __runPickupCoreTests } from "../../src/lib/pos/pickup-core";
import { __runMemberHistoryCoreTests } from "../../src/lib/pos/member-history-core";
import { __runEmailReceiptCoreTests } from "../../src/lib/pos/email-receipt-core";
import { __runChangeCalcCoreTests } from "../../src/lib/pos/change-calc-core";
import { __runLowStockCoreTests } from "../../src/lib/pos/low-stock-core";
import { __runCashRoundingCoreTests } from "../../src/lib/pos/cash-rounding-core";
import { __runLeaderboardCoreTests } from "../../src/lib/pos/leaderboard-core";
import { __runSaleGridCoreTests } from "../../src/lib/pos/sale-grid-core";
import { __runCustomSaleCoreTests } from "../../src/lib/pos/custom-sale-core";
import { __runFavoritesCoreTests } from "../../src/lib/pos/favorites-core";
import { __runScanRequiredCoreTests } from "../../src/lib/pos/scan-required-core";
import { __runProductInfoCoreTests } from "../../src/lib/pos/product-info-core";
import { __runStockFlagCoreTests } from "../../src/lib/pos/stock-flag-core";
import { __runThemeCoreTests } from "../../src/lib/pos/theme-core";
import { __runSwCoreTests } from "../../src/lib/pos/sw-core";
import { __runVariantGramsCoreTests } from "../../src/lib/pos/variant-grams-core";
import { __runMenuLiveStepCoreTests } from "../../src/lib/inventory/menu-live-step-core";
import { __runVendorResolveCoreTests } from "../../src/lib/inventory/vendor-resolve-core";
import { __runCultiveraInvoiceTests } from "../../src/lib/inventory/pdf-cultivera-invoice-core";
import { __runIntakeChecklistCoreTests } from "../../src/lib/inventory/intake-checklist-core";
import { __runDraftSeedCoreTests } from "../../src/lib/inventory/draft-seed-core";
import { __runWedgeScanCoreTests } from "../../src/lib/pos/wedge-scan-core";
import { __runRegisterLoyaltyCoreTests } from "../../src/lib/pos/register-loyalty-core";
import { __runOrderToCartCoreTests } from "../../src/lib/pos/order-to-cart-core";
import { __runMemberMatchCoreTests } from "../../src/lib/pos/member-match-core";

async function main() {
  __runOrderPricingTests();
  __runDiscountEngineTests();
  __runPromoGuardTests();
  __runSalesLimitTests();
  __runSalesLimitGateTests();
  await __runChunkedInTests();
  const exempt = __runExemptSaleRecordTests();
  if (exempt.failed > 0) throw new Error(`exempt-sale-record-core: ${exempt.failed} failure(s)`);
  __runSalesHoursCoreTests();
  __runReceiptCoreTests();
  __runPinHashTests();
  __runAtRestCryptoTests();
  __runEngineTests();
  __runLoyaltyConfigTests();
  __runLoyaltySaleTests();
  __runSignupCustomerTests();
  __runScheduleCoreTests();
  __runEmployeeLifecycleTests();
  __runUserGuardTests();
  __runCampaignRulesTests();
  __runCompetitivePlaybookTests();
  __runMidjourneyCoreTests();
  __runFluxCoreTests();
  __runCreativePlacementsTests();
  const ccrsWeek = __runCcrsWeekTests();
  if (ccrsWeek.failed > 0) throw new Error(`ccrs-week-core: ${ccrsWeek.failed} failure(s)`);
  const ccrsDeadline = __runCcrsDeadlineTests();
  if (ccrsDeadline.failed > 0) throw new Error(`ccrs-deadline-core: ${ccrsDeadline.failed} failure(s)`);
  const ccrsTriage = __runCcrsErrorTriageTests();
  if (ccrsTriage.failed > 0) throw new Error(`ccrs-error-triage-core: ${ccrsTriage.failed} failure(s)`);
  __runMenuFeedTests();
  __runLeaflyPayloadTests();
  __runWmPayloadTests();
  __runIntegrationCredentialsTests();
  __runSyncPlanTests();
  __runPreflightTests();
  __runRichnessTests();
  __runSyncSettingsTests();
  __runApplySettingsTests();
  __runSyndicationPlaybookTests();
  __runPosSaleEventTests();
  __runIdScanCoreTests();
  __runPosSyncCoreTests();
  __runRegisterClientCoreTests();
  __runRegisterPolishCoreTests();
  __runSaleFlowCoreTests();
  __runMedicalPosCoreTests();
  __runPosReceiptCoreTests();
  __runReceiptConfigCoreTests();
  __runPosReturnsCoreTests();
  __runSaleDecrementCoreTests();
  __runTillCoreTests();
  __runDayReportCoreTests();
  __runPriceDriftCoreTests();
  __runExceptionReminderCoreTests();
  __runRecallHoldCoreTests();
  __runPinThrottleCoreTests();
  __runScanToCartCoreTests();
  __runVariantLotCoreTests();
  __runIntakeMasteringCoreTests();
  __runIntakeMenuStagingCoreTests();
  __runPriceOverrideCoreTests();
  __runDeviceSetupCoreTests();
  __runVoidSaleCoreTests();
  __runPickupCoreTests();
  __runMemberHistoryCoreTests();
  __runEmailReceiptCoreTests();
  __runChangeCalcCoreTests();
  __runLowStockCoreTests();
  __runCashRoundingCoreTests();
  __runLeaderboardCoreTests();
  __runSaleGridCoreTests();
  __runCustomSaleCoreTests();
  __runFavoritesCoreTests();
  __runScanRequiredCoreTests();
  __runProductInfoCoreTests();
  __runStockFlagCoreTests();
  __runThemeCoreTests();
  __runDraftSeedCoreTests();
  __runWedgeScanCoreTests();
  __runRegisterLoyaltyCoreTests();
  __runOrderToCartCoreTests();
  __runMemberMatchCoreTests();
  __runSwCoreTests();
  __runVariantGramsCoreTests();
  __runMenuLiveStepCoreTests();
  __runVendorResolveCoreTests();
  __runCultiveraInvoiceTests();
  __runIntakeChecklistCoreTests();
  console.log("ALL PURE SELF-TESTS PASSED");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
