/**
 * scripts/compliance/run-pure-selftests.ts
 *
 * Runs the embedded self-tests of the PURE compliance/money modules. Exits
 * non-zero on any failure. Run with:  npx tsx scripts/compliance/run-pure-selftests.ts
 */
import { __runOrderPricingTests } from "../../src/lib/orders/order-pricing-core";
import { __runTaxBaseCoreTests } from "../../src/lib/reports/tax-base-core";
import { __runExciseReturnTests } from "../../src/lib/compliance/excise-return-core";
import { __runDiscountEngineTests } from "../../src/lib/promotions/discount-engine-core";
import { __runPromoGuardTests } from "../../src/lib/promotions/promo-guard-core";
import { __runSalesLimitTests } from "../../src/lib/compliance/sales-limits-core";
import { __runSalesLimitGateTests } from "../../src/lib/compliance/sales-limit-gate-core";
import { __runChunkedInTests } from "../../src/lib/supabase/chunked-in";
import { __runExemptSaleRecordTests } from "../../src/lib/medical/exempt-sale-record-core";
import { __runSalesHoursCoreTests } from "../../src/lib/compliance/sales-hours-core";
import { __runReceiptCoreTests } from "../../src/lib/printing/receipt-core";
import { __runPinHashTests } from "../../src/lib/security/pin-hash";
import { __runAtRestCryptoTests } from "../../src/lib/security/at-rest-crypto";
import { __runRlsCoverageTests } from "../../src/lib/security/rls-coverage-core";
import { __runEngineTests } from "../../src/lib/loyalty/engine";
import { __runLoyaltyConfigTests } from "../../src/lib/loyalty/loyalty-config-core";
import { __runLoyaltySaleTests } from "../../src/lib/loyalty/loyalty-sale-core";
import { __runSignupCustomerTests } from "../../src/lib/loyalty/signup-customer-core";
import { __runScheduleCoreTests } from "../../src/lib/staffing/schedule-core";
import { __runEmployeeLifecycleTests } from "../../src/lib/staffing/employee-lifecycle-core";
import { __runHandbookAckTests } from "../../src/lib/staffing/handbook-ack-core";
import { __runRegulatoryCoreTests } from "../../src/lib/regulatory/regulatory-core";
import { __runComplianceSurfaceTests } from "../../src/lib/regulatory/compliance-surface";
import { __runUserGuardTests } from "../../src/lib/auth/user-guards-core";
import { __runSetPasswordCoreTests } from "../../src/lib/auth/set-password-core";
import { __runLoginMessagesCoreTests } from "../../src/lib/auth/login-messages-core";
import { __runCampaignRulesTests } from "../../src/lib/marketing/campaign-rules-core";
import { __runCompetitivePlaybookTests } from "../../src/lib/marketing/competitive-playbook-core";
import { __runMidjourneyCoreTests } from "../../src/lib/marketing/midjourney-core";
import { __runFluxCoreTests } from "../../src/lib/marketing/flux-core";
import { __runCreativePlacementsTests } from "../../src/lib/marketing/creative-placements-core";
import { __runCcrsWeekTests } from "../../src/lib/compliance/ccrs-week-core";
import { __runCcrsDeadlineTests } from "../../src/lib/compliance/ccrs-deadline-core";
import { __runCcrsErrorTriageTests } from "../../src/lib/compliance/ccrs-error-triage-core";
import { __runMenuFeedTests } from "../../src/lib/syndication/menu-feed-core";
import { __runLeaflyPayloadTests } from "../../src/lib/leafly/payload-core";
import { __runWmPayloadTests } from "../../src/lib/weedmaps/payload-core";
import { __runIntegrationCredentialsTests } from "../../src/lib/integrations/integration-credentials-core";
import { __runSyncPlanTests } from "../../src/lib/syndication/sync-plan-core";
import { __runPreflightTests } from "../../src/lib/syndication/preflight-core";
import { __runRichnessTests } from "../../src/lib/syndication/richness-core";
import { __runSyncSettingsTests } from "../../src/lib/syndication/sync-settings-core";
import { __runApplySettingsTests } from "../../src/lib/syndication/apply-settings-core";
import { __runSyndicationPlaybookTests } from "../../src/lib/integrations/syndication-playbook";
import { __runPosSaleEventTests } from "../../src/lib/pos/sale-event-core";
import { __runIdScanCoreTests } from "../../src/lib/pos/id-scan-core";
import { __runPosSyncCoreTests } from "../../src/lib/pos/sync-core";
import { __runPendingRecoveryCoreTests } from "../../src/lib/pos/pending-recovery-core";
import { __runNotifyOutcomeCoreTests } from "../../src/lib/orders/notify-outcome-core";
import { __runStatusCasCoreTests } from "../../src/lib/orders/status-cas-core";
import { __runRpcFallbackCoreTests } from "../../src/lib/db/rpc-fallback-core";
import { __runRegisterClientCoreTests } from "../../src/lib/pos/register-client-core";
import { __runRegisterPolishCoreTests } from "../../src/lib/pos/register-polish-core";
import { __runHeldStockCoreTests } from "../../src/lib/pos/held-stock-core";
import { __runSaleFlowCoreTests } from "../../src/lib/pos/sale-flow-core";
import { __runMedicalPosCoreTests } from "../../src/lib/pos/medical-pos-core";
import { __runPosReceiptCoreTests } from "../../src/lib/pos/receipt-core";
import { __runReceiptConfigCoreTests } from "../../src/lib/pos/receipt-config-core";
import { __runPosReturnsCoreTests } from "../../src/lib/pos/returns-core";
import { __runSaleDecrementCoreTests } from "../../src/lib/inventory/sale-decrement-core";
import { __runTillCoreTests } from "../../src/lib/pos/till-core";
import { __runDayReportCoreTests } from "../../src/lib/pos/day-report-core";
import { __runPriceDriftCoreTests } from "../../src/lib/pos/price-drift-core";
import { __runExceptionReminderCoreTests } from "../../src/lib/pos/exception-reminder-core";
import { __runRecallHoldCoreTests } from "../../src/lib/pos/recall-hold-core";
import { __runPinThrottleCoreTests } from "../../src/lib/security/pin-throttle-core";
import { __runScanToCartCoreTests } from "../../src/lib/pos/scan-to-cart-core";
import { __runVariantLotCoreTests } from "../../src/lib/pos/variant-lot-core";
import { __runImportLotCoreTests } from "../../src/lib/pos/import-lot-core";
import { __runCardBrandCoreTests } from "../../src/lib/menu/card-brand-core";
import { __runVendorDirectoryCoreTests } from "../../src/lib/menu/vendor-directory-core";
import { __runCardTypeCoreTests } from "../../src/lib/menu/card-type-core";
import { __runLotTableCoreTests } from "../../src/lib/inventory/lot-table-core";
import { __runLotEditCoreTests } from "../../src/lib/inventory/lot-edit-core";
import { __runCategoryRegistryCoreTests } from "../../src/lib/pos/category-registry-core";
import { __runTypeRegistryCoreTests } from "../../src/lib/pos/type-registry-core";
import { __runHouseTypeCoreTests } from "../../src/lib/inventory/house-type-core";
import { __runDraftApprovalGateTests } from "../../src/lib/inventory/draft-approval-gate-core";
import { __runStrainFieldsCoreTests } from "../../src/lib/inventory/strain-fields-core";
import { __runStrainTypeIntelTests } from "../../src/lib/inventory/strain-type-intel-core";
import { __runBankingVaultUiTests } from "../../src/lib/payments/banking-vault-ui-core";
import { __runRelatedProductsCoreTests } from "../../src/lib/menu/related-products-core";
import { __runDealBadgeCoreTests } from "../../src/lib/promotions/deal-badge-core";
import { __runWeightDisplayCoreTests } from "../../src/lib/menu/weight-display-core";
import { __runVendorRelationsCoreTests } from "../../src/lib/vendors/vendor-relations-core";
import { __runFactExtractionCoreTests } from "../../src/lib/inventory/fact-extraction-core";
import { __runFactReviewCoreTests } from "../../src/lib/pos/fact-review-core";
import { __runImportCommitCoreTests } from "../../src/lib/pos/import-commit-core";
import { __runIntakePotencyCoreTests } from "../../src/lib/pos/intake-potency-core";
import { __runIntakeMasteringCoreTests } from "../../src/lib/pos/intake-mastering-core";
import { __runIntakeMenuStagingCoreTests } from "../../src/lib/pos/intake-menu-staging-core";
import { __runPriceOverrideCoreTests } from "../../src/lib/pos/price-override-core";
import { __runDeviceSetupCoreTests } from "../../src/lib/pos/device-setup-core";
import { __runVoidSaleCoreTests } from "../../src/lib/pos/void-sale-core";
import { __runPickupCoreTests } from "../../src/lib/pos/pickup-core";
import { __runMemberHistoryCoreTests } from "../../src/lib/pos/member-history-core";
import { __runEmailReceiptCoreTests } from "../../src/lib/pos/email-receipt-core";
import { __runChangeCalcCoreTests } from "../../src/lib/pos/change-calc-core";
import { __runLowStockCoreTests } from "../../src/lib/pos/low-stock-core";
import { __runCashRoundingCoreTests } from "../../src/lib/pos/cash-rounding-core";
import { __runLeaderboardCoreTests } from "../../src/lib/pos/leaderboard-core";
import { __runSaleGridCoreTests } from "../../src/lib/pos/sale-grid-core";
import { __runCustomSaleCoreTests } from "../../src/lib/pos/custom-sale-core";
import { __runFavoritesCoreTests } from "../../src/lib/pos/favorites-core";
import { __runScanRequiredCoreTests } from "../../src/lib/pos/scan-required-core";
import { __runProductInfoCoreTests } from "../../src/lib/pos/product-info-core";
import { __runStockFlagCoreTests } from "../../src/lib/pos/stock-flag-core";
import { __runThemeCoreTests } from "../../src/lib/pos/theme-core";
import { __runSwCoreTests } from "../../src/lib/pos/sw-core";
import { __runVariantGramsCoreTests } from "../../src/lib/pos/variant-grams-core";
import { __runMenuLiveStepCoreTests } from "../../src/lib/inventory/menu-live-step-core";
import { __runVendorResolveCoreTests } from "../../src/lib/inventory/vendor-resolve-core";
import { __runCultiveraInvoiceTests } from "../../src/lib/inventory/pdf-cultivera-invoice-core";
import { __runGenericPdfTransportTests } from "../../src/lib/inventory/pdf-generic-transport-core";
import { __runEmailHarvestTests } from "../../src/lib/inbound-email/email-harvest-core";
import { __runIntakeChecklistCoreTests } from "../../src/lib/inventory/intake-checklist-core";
import { __runIdCaptureCoreTests } from "../../src/lib/pos/id-capture-core";
import { __runCultiveraMenuCoreTests } from "../../src/lib/purchasing/cultivera-menu-core";
import { __runGrowflowMenuCoreTests } from "../../src/lib/purchasing/growflow-menu-core";
import { __runLeaflinkMenuCoreTests } from "../../src/lib/purchasing/leaflink-menu-core";
import { __runUnifiedSearchCoreTests } from "../../src/lib/purchasing/unified-search-core";
import { __runUnifiedMenusUiCoreTests } from "../../src/lib/purchasing/unified-menus-ui-core";
import { __runEmailMenuCoreTests } from "../../src/lib/purchasing/email-menu-core";
import { __runCultiveraMenusUiCoreTests } from "../../src/lib/purchasing/cultivera-menus-ui-core";
import { __runCultiveraMediaCoreTests } from "../../src/lib/purchasing/cultivera-media-core";
import { __runCultiveraPoCoreTests } from "../../src/lib/purchasing/cultivera-po-core";
import { __runGrowflowMediaCoreTests } from "../../src/lib/purchasing/growflow-media-core";
import { __runGrowflowKbLinkCoreTests } from "../../src/lib/purchasing/growflow-kb-link-core";
import { __runLeaflinkMediaCoreTests } from "../../src/lib/purchasing/leaflink-media-core";
import { __runLeaflinkKbLinkCoreTests } from "../../src/lib/purchasing/leaflink-kb-link-core";
import { __runMenuDescriptionCoreTests } from "../../src/lib/purchasing/menu-description-core";
import { __runSaveAssetsCoreTests } from "../../src/lib/purchasing/save-assets-core";
import { __runCultiveraKbLinkCoreTests } from "../../src/lib/purchasing/cultivera-kb-link-core";
import { __runGrowflowMenuUiCoreTests } from "../../src/lib/purchasing/growflow-menu-ui-core";
import { __runMediaAutosaveCoreTests } from "../../src/lib/purchasing/media-autosave-core";
import { __runDraftSeedCoreTests } from "../../src/lib/inventory/draft-seed-core";
import { __runWedgeScanCoreTests } from "../../src/lib/pos/wedge-scan-core";
import { __runRegisterLoyaltyCoreTests } from "../../src/lib/pos/register-loyalty-core";
import { __runOrderToCartCoreTests } from "../../src/lib/pos/order-to-cart-core";
import { __runMemberMatchCoreTests } from "../../src/lib/pos/member-match-core";
import { __runActiveSaleResumeCoreTests } from "../../src/lib/pos/active-sale-resume-core";
import { __runMenuNameDisplayCoreTests } from "../../src/lib/pos/menu-name-display-core";
import { __runMedicalTestModeCoreTests } from "../../src/lib/pos/medical-testmode-core";
import { __runSawPrefillCoreTests } from "../../src/lib/pos/saw-prefill-core";
import { __runBackLinkTests } from "../../src/lib/admin/back-link-core";
import { __runPostgrestEscapeTests } from "../../src/lib/supabase/postgrest-escape";
import { __runPrintRetryCoreTests } from "../../src/lib/printing/print-retry-core";
import { __runRevenueBasisTests } from "../../src/lib/reports/revenue-basis";
import { __runRejectedReportTests } from "../../src/lib/pos/rejected-report-core";
import { __runReservationExpiryTests } from "../../src/lib/orders/reservation-expiry-core";
import { __runListWindowTests } from "../../src/lib/admin/list-window-core";
import { __runListFilterTests } from "../../src/lib/admin/list-filter-core";
import { __runSpecialDiscountTests } from "../../src/lib/discounts/special-discount-core";
import { __runSpecialDiscountSaleTests } from "../../src/lib/pos/special-discount-sale-core";
import { __runSpecialDiscountReportTests } from "../../src/lib/discounts/special-discount-report-core";
import { __runSafeCoreTests } from "../../src/lib/registers/safe-core";
import { __runEodCoreTests } from "../../src/lib/registers/eod-core";
import { __runConstantTimeTests } from "../../src/lib/security/constant-time";
import { __runGramsPerOunceTests } from "../../src/lib/compliance/grams-per-ounce";
import { __runEnrichmentMatchCoreTests } from "../../src/lib/enrichment/match-core";
import { __runPublishGuardTests } from "../../src/lib/pos/publish-guard-core";
// SLICE 39 connectivity audit: the 41 suites below existed but ran nowhere.
import { __runAdminNavTests } from "../../src/components/admin/admin-nav-core";
import { __runSageExportsCoreTests } from "../../src/lib/accounting/sage-exports-core";
import { __runSageHelperCoreTests } from "../../src/lib/accounting/sage-helper-core";
import { __runSage50CoreTests } from "../../src/lib/accounting/sage50-core";
import { __runAuditAnomalyTests } from "../../src/lib/admin/audit-anomaly-core";
import { __runCockpitTests } from "../../src/lib/admin/cockpit-core";
import { __runMobileCoreTests } from "../../src/lib/admin/mobile-core";
import { __runStoreProfileTests } from "../../src/lib/admin/store-profile-core";
import { __runKbNotesTests } from "../../src/lib/ai/kb/kb-notes-core";
import { __runProductImageEditTests } from "../../src/lib/ai/kb/product-images-core";
import { __runProductResearchCoreTests } from "../../src/lib/enrichment/research-core";
import { __runWebauthnCoreTests } from "../../src/lib/auth/webauthn-core";
import { __runNormalizeTests } from "../../src/lib/cms/email-events/normalize-core";
import { __runVerifyTests } from "../../src/lib/cms/email-events/verify-core";
import { __runImageSpecTests } from "../../src/lib/cms/image-spec-core";
import { __runCcrsIdentifierTests } from "../../src/lib/compliance/ccrs-identifiers";
import { __runCcrsAdjustmentTests } from "../../src/lib/compliance/ccrs-inventory-adjustment-core";
import { __runCcrsSubmitGateTests } from "../../src/lib/compliance/ccrs-submit-gate-core";
import { __runComplianceHealthTests } from "../../src/lib/compliance/compliance-health-core";
import { __runExcisePaymentCoreTests } from "../../src/lib/compliance/excise-payment-core";
import { __runCcrsManifestCsvTests } from "../../src/lib/inventory/ccrs-manifest-csv-core";
import { __runScanCoreTests } from "../../src/lib/inventory/cycle-count-scan-core";
import { __runDispositionTests } from "../../src/lib/inventory/intake-disposition-core";
import { __runIntakeReviewTests } from "../../src/lib/inventory/intake-review-core";
import { __runIntakeReviewAdapterTests } from "../../src/lib/inventory/intake-review-adapter";
import { __runLotActivationGateTests } from "../../src/lib/inventory/lot-activation-gate-core";
import { __runManifestPipelineTests } from "../../src/lib/inventory/manifest-pipeline-core";
import { __runSampleGuardrailTests } from "../../src/lib/inventory/sample-guardrails";
import { __runCardCannabinoidTests } from "../../src/lib/menu/card-cannabinoids";
import { __runCardIdentityCoreTests } from "../../src/lib/menu/card-identity-core";
import { __runReprocessCoreTests } from "../../src/lib/inventory/reprocess-core";
import { __runTransformCoreTests } from "../../src/lib/pos/transform";
import { __runStrainTerpeneTests } from "../../src/lib/menu/strain-terpenes";
import { __runVariantSortTests } from "../../src/lib/menu/variant-sort";
import { __runVariantCollapseTests } from "../../src/lib/menu/variant-collapse-core";
import { __runNonCannabisTests } from "../../src/lib/naming/noncannabis-core";
import { __runNamingConventionTests } from "../../src/lib/naming/convention-core";
import { __runCcrsProductNameCoreTests } from "../../src/lib/compliance/ccrs-product-name-core";
import { __runNachaCoreTests } from "../../src/lib/payments/nacha-core";
import { __runVendorAchTests } from "../../src/lib/payments/vendor-ach-core";
import { __runPayeeBankingCoreTests } from "../../src/lib/payments/payee-banking-core";
import { __runPayrollCoreTests } from "../../src/lib/payroll/payroll-core";
import { __runPayrollGuardrailsCoreTests } from "../../src/lib/payroll/payroll-guardrails-core";
import { __runInventoryCatalogTests } from "../../src/lib/pos/inventory-type-catalog";
import { __runCode128Tests } from "../../src/lib/printing/code128-core";
import { __runPrinterDiagnosticsTests } from "../../src/lib/printing/printer-diagnostics-core";
import { __runPoCoreTests } from "../../src/lib/purchasing/po-core";
import { __runPoDocumentCoreTests } from "../../src/lib/purchasing/po-document-core";
import { __runPoListInsightsCoreTests } from "../../src/lib/purchasing/po-list-insights-core";
import { __runForecastTests } from "../../src/lib/reports/forecast-core";
import { __runNewsletterStatsTests } from "../../src/lib/reports/newsletter-stats-core";
import { __runRangeTests } from "../../src/lib/reports/range";
import { __runZipTests } from "../../src/lib/reports/zip";
import { __runTimeclockCoreTests } from "../../src/lib/staffing/timeclock-core";
import { __runVendorGoldminerTests } from "../../src/lib/inventory/vendor-goldminer-core";

// Helper for suites that return { passed, failed } without throwing on
// failure: the runner must assert failed === 0 itself.
function assertNoFailures(name: string, result: { passed: number; failed: number }): void {
  if (result.failed > 0) {
    throw new Error(`${name} self-tests failed: ${result.failed} (passed: ${result.passed})`);
  }
}

async function main() {
  __runOrderPricingTests();
  __runTaxBaseCoreTests();
  __runDiscountEngineTests();
  __runPromoGuardTests();
  __runSalesLimitTests();
  __runSalesLimitGateTests();
  await __runChunkedInTests();
  const exempt = __runExemptSaleRecordTests();
  if (exempt.failed > 0) throw new Error(`exempt-sale-record-core: ${exempt.failed} failure(s)`);
  __runSalesHoursCoreTests();
  __runReceiptCoreTests();
  __runPinHashTests();
  __runAtRestCryptoTests();
  __runRlsCoverageTests();
  __runEngineTests();
  __runLoyaltyConfigTests();
  __runLoyaltySaleTests();
  __runSignupCustomerTests();
  __runScheduleCoreTests();
  __runEmployeeLifecycleTests();
  __runHandbookAckTests();
  __runRegulatoryCoreTests();
  __runComplianceSurfaceTests();
  __runUserGuardTests();
  __runSetPasswordCoreTests();
  __runLoginMessagesCoreTests();
  __runCampaignRulesTests();
  __runCompetitivePlaybookTests();
  __runMidjourneyCoreTests();
  __runFluxCoreTests();
  __runCreativePlacementsTests();
  const ccrsWeek = __runCcrsWeekTests();
  if (ccrsWeek.failed > 0) throw new Error(`ccrs-week-core: ${ccrsWeek.failed} failure(s)`);
  const ccrsDeadline = __runCcrsDeadlineTests();
  if (ccrsDeadline.failed > 0) throw new Error(`ccrs-deadline-core: ${ccrsDeadline.failed} failure(s)`);
  const ccrsTriage = __runCcrsErrorTriageTests();
  if (ccrsTriage.failed > 0) throw new Error(`ccrs-error-triage-core: ${ccrsTriage.failed} failure(s)`);
  __runMenuFeedTests();
  __runLeaflyPayloadTests();
  __runWmPayloadTests();
  __runIntegrationCredentialsTests();
  __runSyncPlanTests();
  __runPreflightTests();
  __runRichnessTests();
  __runSyncSettingsTests();
  __runApplySettingsTests();
  __runSyndicationPlaybookTests();
  __runPosSaleEventTests();
  __runIdScanCoreTests();
  __runPosSyncCoreTests();
  __runPendingRecoveryCoreTests();
  __runNotifyOutcomeCoreTests();
  __runStatusCasCoreTests();
  __runRpcFallbackCoreTests();
  __runExciseReturnTests();
  __runRegisterClientCoreTests();
  __runRegisterPolishCoreTests();
  __runHeldStockCoreTests();
  __runSaleFlowCoreTests();
  __runMedicalPosCoreTests();
  __runPosReceiptCoreTests();
  __runReceiptConfigCoreTests();
  __runPosReturnsCoreTests();
  __runSaleDecrementCoreTests();
  __runTillCoreTests();
  __runDayReportCoreTests();
  __runPriceDriftCoreTests();
  __runExceptionReminderCoreTests();
  __runRecallHoldCoreTests();
  __runPinThrottleCoreTests();
  __runScanToCartCoreTests();
  __runVariantLotCoreTests();
  __runImportLotCoreTests();
  __runCardBrandCoreTests();
  __runVendorDirectoryCoreTests();
  __runCardTypeCoreTests();
  __runLotTableCoreTests();
  __runLotEditCoreTests();
  __runCategoryRegistryCoreTests();
  __runTypeRegistryCoreTests();
  __runHouseTypeCoreTests();
  __runDraftApprovalGateTests();
  __runStrainFieldsCoreTests();
  __runStrainTypeIntelTests();
  __runBankingVaultUiTests();
  __runRelatedProductsCoreTests();
  __runDealBadgeCoreTests();
  __runWeightDisplayCoreTests();
  __runVendorRelationsCoreTests();
  __runFactExtractionCoreTests();
  __runFactReviewCoreTests();
  __runImportCommitCoreTests();
  __runIntakePotencyCoreTests();
  __runIntakeMasteringCoreTests();
  __runIntakeMenuStagingCoreTests();
  __runPriceOverrideCoreTests();
  __runDeviceSetupCoreTests();
  __runVoidSaleCoreTests();
  __runPickupCoreTests();
  __runMemberHistoryCoreTests();
  __runEmailReceiptCoreTests();
  __runChangeCalcCoreTests();
  __runLowStockCoreTests();
  __runCashRoundingCoreTests();
  __runLeaderboardCoreTests();
  __runSaleGridCoreTests();
  __runCustomSaleCoreTests();
  __runFavoritesCoreTests();
  __runScanRequiredCoreTests();
  __runProductInfoCoreTests();
  __runStockFlagCoreTests();
  __runThemeCoreTests();
  __runDraftSeedCoreTests();
  __runWedgeScanCoreTests();
  __runRegisterLoyaltyCoreTests();
  __runOrderToCartCoreTests();
  __runMemberMatchCoreTests();
  __runActiveSaleResumeCoreTests();
  __runMenuNameDisplayCoreTests();
  __runMedicalTestModeCoreTests();
  __runSawPrefillCoreTests();
  __runBackLinkTests();
  __runSwCoreTests();
  __runVariantGramsCoreTests();
  __runMenuLiveStepCoreTests();
  __runVendorResolveCoreTests();
  __runCultiveraInvoiceTests();
  assertNoFailures("generic-pdf-transport", __runGenericPdfTransportTests());
  assertNoFailures("email-harvest", __runEmailHarvestTests());
  __runIntakeChecklistCoreTests();
  __runIdCaptureCoreTests();
  __runCultiveraMenuCoreTests();
  __runGrowflowMenuCoreTests();
  __runLeaflinkMenuCoreTests();
  __runUnifiedSearchCoreTests();
  __runUnifiedMenusUiCoreTests();
  __runEmailMenuCoreTests();
  __runCultiveraMenusUiCoreTests();
  __runCultiveraMediaCoreTests();
  __runCultiveraPoCoreTests();
  __runGrowflowMediaCoreTests();
  __runGrowflowKbLinkCoreTests();
  __runLeaflinkMediaCoreTests();
  __runLeaflinkKbLinkCoreTests();
  __runMenuDescriptionCoreTests();
  __runSaveAssetsCoreTests();
  __runCultiveraKbLinkCoreTests();
  __runGrowflowMenuUiCoreTests();
  __runMediaAutosaveCoreTests();
  __runPostgrestEscapeTests();
  __runConstantTimeTests();
  __runGramsPerOunceTests();
  __runPrintRetryCoreTests();
  __runRevenueBasisTests();
  __runRejectedReportTests();
  __runReservationExpiryTests();
  __runListWindowTests();
  __runListFilterTests();
  __runSpecialDiscountTests();
  __runSpecialDiscountSaleTests();
  __runSpecialDiscountReportTests();
  __runSafeCoreTests();
  __runEodCoreTests();
  __runEnrichmentMatchCoreTests();
  __runPublishGuardTests();
  // SLICE 39 connectivity audit: previously-dark suites. Suites that throw
  // internally on assertion failure are bare calls; suites that only return
  // { passed, failed } are wrapped so a failure still fails this runner.
  __runAdminNavTests();
  __runSageExportsCoreTests();
  __runSageHelperCoreTests();
  __runSage50CoreTests();
  __runAuditAnomalyTests();
  __runCockpitTests();
  __runMobileCoreTests();
  __runStoreProfileTests();
  assertNoFailures("kb-notes-core", __runKbNotesTests());
  assertNoFailures("product-image-edit", __runProductImageEditTests());
  __runProductResearchCoreTests();
  assertNoFailures("webauthn-core", __runWebauthnCoreTests());
  __runNormalizeTests();
  __runVerifyTests();
  assertNoFailures("image-spec-core", __runImageSpecTests());
  assertNoFailures("ccrs-identifiers", __runCcrsIdentifierTests());
  __runCcrsAdjustmentTests();
  assertNoFailures("ccrs-submit-gate-core", __runCcrsSubmitGateTests());
  assertNoFailures("compliance-health-core", __runComplianceHealthTests());
  __runExcisePaymentCoreTests();
  assertNoFailures("ccrs-manifest-csv-core", __runCcrsManifestCsvTests());
  __runScanCoreTests();
  assertNoFailures("intake-disposition-core", __runDispositionTests());
  assertNoFailures("intake-review-core", __runIntakeReviewTests());
  assertNoFailures("intake-review-adapter", __runIntakeReviewAdapterTests());
  assertNoFailures("lot-activation-gate-core", __runLotActivationGateTests());
  assertNoFailures("manifest-pipeline-core", __runManifestPipelineTests());
  __runSampleGuardrailTests();
  __runCardCannabinoidTests();
  __runCardIdentityCoreTests();
  __runReprocessCoreTests();
  __runTransformCoreTests();
  assertNoFailures("strain-terpenes", __runStrainTerpeneTests());
  assertNoFailures("variant-sort", __runVariantSortTests());
  assertNoFailures("variant-collapse", __runVariantCollapseTests());
  __runNonCannabisTests();
  __runNamingConventionTests();
  __runCcrsProductNameCoreTests();
  assertNoFailures("nacha-core", __runNachaCoreTests());
  assertNoFailures("vendor-ach-core", __runVendorAchTests());
  __runPayeeBankingCoreTests();
  assertNoFailures("payroll-core", __runPayrollCoreTests());
  assertNoFailures("payroll-guardrails-core", __runPayrollGuardrailsCoreTests());
  __runInventoryCatalogTests();
  assertNoFailures("code128-core", __runCode128Tests());
  __runPrinterDiagnosticsTests();
  __runPoCoreTests();
  __runPoDocumentCoreTests();
  __runPoListInsightsCoreTests();
  assertNoFailures("forecast-core", __runForecastTests());
  __runNewsletterStatsTests();
  assertNoFailures("range", __runRangeTests());
  __runZipTests();
  __runTimeclockCoreTests();
  assertNoFailures("vendor-goldminer", __runVendorGoldminerTests());
  console.log("ALL PURE SELF-TESTS PASSED");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
