import type { GreenwayCategory, GreenwayMenuItem } from "./types";

const variant = (id: string, label: string, priceMinorUnits: number, inventoryLevel: number) => ({
  id,
  label,
  priceMinorUnits,
  inventoryLevel,
  medical: false,
});

export const mockMenuItems: GreenwayMenuItem[] = [
  {
    id: "mock-flower-001",
    name: "Greenway House Flower",
    brand: "Greenway Preview",
    category: "flower",
    strainType: "hybrid",
    thc: "24%",
    cbd: null,
    totalThc: { type: "thc", value: "24", unit: "%" },
    totalCbd: null,
    compounds: [
      { type: "thc", value: "24", unit: "%" },
      { type: "cbg", value: "0.7", unit: "%" },
    ],
    description: "A balanced house flower preview used to test Greenway product browsing, potency display, and variant handling before live Leafly inventory is connected.",
    priceLabel: "$25 eighth",
    priceMinorUnits: 2500,
    inventoryStatus: "mock",
    variants: [variant("mock-flower-001-1g", "1g", 900, 18), variant("mock-flower-001-35g", "3.5g", 2500, 12), variant("mock-flower-001-7g", "7g", 4600, 7)],
  },
  {
    id: "mock-flower-002",
    name: "Sinclair Inlet Kush",
    brand: "Port Orchard Reserve",
    category: "flower",
    strainType: "indica",
    thc: "27%",
    cbd: null,
    totalThc: { type: "thc", value: "27", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "27", unit: "%" }, { type: "cbn", value: "0.3", unit: "%" }],
    description: "An indica-leaning mock product with multiple flower package variants and plain-text product details for Leafly-safe presentation testing.",
    priceLabel: "$32 eighth",
    priceMinorUnits: 3200,
    inventoryStatus: "mock",
    variants: [variant("mock-flower-002-1g", "1g", 1100, 9), variant("mock-flower-002-35g", "3.5g", 3200, 5)],
  },
  {
    id: "mock-flower-003",
    name: "Manette Bridge Blend",
    brand: "Port Orchard Reserve",
    category: "flower",
    strainType: "indica-hybrid",
    thc: "25%",
    cbd: null,
    totalThc: { type: "thc", value: "25", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "25", unit: "%" }, { type: "cbn", value: "0.4", unit: "%" }],
    description: "An indica-hybrid mock product for verifying the new leaning-hybrid strain-type filter, label, and card tone in the menu browser.",
    priceLabel: "$30 eighth",
    priceMinorUnits: 3000,
    inventoryStatus: "mock",
    variants: [variant("mock-flower-003-1g", "1g", 1000, 11), variant("mock-flower-003-35g", "3.5g", 3000, 6)],
  },
  {
    id: "mock-flower-004",
    name: "Kitsap Sunrise Haze",
    brand: "Greenway Preview",
    category: "flower",
    strainType: "sativa-hybrid",
    thc: "23%",
    cbd: null,
    totalThc: { type: "thc", value: "23", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "23", unit: "%" }],
    description: "A sativa-hybrid mock product for verifying the new leaning-hybrid strain-type filter, label, and card tone in the menu browser.",
    priceLabel: "$28 eighth",
    priceMinorUnits: 2800,
    inventoryStatus: "mock",
    variants: [variant("mock-flower-004-1g", "1g", 950, 14), variant("mock-flower-004-35g", "3.5g", 2800, 8)],
  },
  {
    id: "mock-preroll-001",
    name: "Port Orchard Pre-Roll Pack",
    brand: "Greenway Preview",
    category: "preroll",
    strainType: "sativa",
    thc: "21%",
    cbd: null,
    totalThc: { type: "thc", value: "21", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "21", unit: "%" }],
    description: "A sativa-style pre-roll pack preview designed to test quick ordering cards, package options, and inventory messaging.",
    priceLabel: "$18 pack",
    priceMinorUnits: 1800,
    inventoryStatus: "mock",
    variants: [variant("mock-preroll-001-pack", "5-pack", 1800, 24)],
  },
  {
    id: "mock-preroll-002",
    name: "Bethel Ave Infused Pre-Roll",
    brand: "Greenway Preview",
    category: "preroll",
    strainType: "hybrid",
    thc: "36%",
    cbd: null,
    totalThc: { type: "thc", value: "36", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "36", unit: "%" }, { type: "thca", value: "2.1", unit: "%" }],
    description: "A higher potency infused pre-roll mock item for testing prominent cannabinoid values and single-item variant display.",
    priceLabel: "$14 each",
    priceMinorUnits: 1400,
    inventoryStatus: "mock",
    variants: [variant("mock-preroll-002-single", "1g single", 1400, 16)],
  },
  {
    id: "mock-edible-001",
    name: "Washington Fruit Gummies",
    brand: "Greenway Preview",
    category: "edible-solid",
    strainType: "cbd",
    thc: "100mg",
    cbd: "100mg",
    totalThc: { type: "thc", value: "100", unit: "mg" },
    totalCbd: { type: "cbd", value: "100", unit: "mg" },
    compounds: [{ type: "thc", value: "100", unit: "mg" }, { type: "cbd", value: "100", unit: "mg" }],
    description: "A balanced edible preview with milligram-based cannabinoid values, useful for validating edible product details and compliance language spacing.",
    priceLabel: "$16 each",
    priceMinorUnits: 1600,
    inventoryStatus: "mock",
    variants: [variant("mock-edible-001-10pk", "10-pack", 1600, 31)],
  },
  {
    id: "mock-vape-001",
    name: "Puget Sound Live Resin Cart",
    brand: "Sound Extracts Preview",
    category: "cartridge",
    strainType: "sativa",
    thc: "82%",
    cbd: null,
    totalThc: { type: "thc", value: "82", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "82", unit: "%" }, { type: "cbg", value: "1.2", unit: "%" }],
    description: "A vape cartridge mock product for validating high-potency product details, variant pricing, and inventory display.",
    priceLabel: "$36 1g",
    priceMinorUnits: 3600,
    inventoryStatus: "mock",
    variants: [variant("mock-vape-001-05g", "0.5g", 2200, 10), variant("mock-vape-001-1g", "1g", 3600, 8)],
  },
  {
    id: "mock-concentrate-001",
    name: "Blackberry Gelato Badder",
    brand: "Kitsap Concentrates Preview",
    category: "concentrate",
    strainType: "hybrid",
    thc: "74%",
    cbd: null,
    totalThc: { type: "thc", value: "74", unit: "%" },
    totalCbd: null,
    compounds: [{ type: "thc", value: "74", unit: "%" }, { type: "cbg", value: "2.4", unit: "%" }],
    description: "A concentrate preview item for testing dense product detail information, potency badges, and gram-based variant display.",
    priceLabel: "$28 gram",
    priceMinorUnits: 2800,
    inventoryStatus: "mock",
    variants: [variant("mock-concentrate-001-1g", "1g", 2800, 11)],
  },
  {
    id: "mock-topical-001",
    name: "Evergreen Relief Balm",
    brand: "Greenway Wellness Preview",
    category: "topical",
    strainType: "cbd",
    thc: "50mg",
    cbd: "250mg",
    totalThc: { type: "thc", value: "50", unit: "mg" },
    totalCbd: { type: "cbd", value: "250", unit: "mg" },
    compounds: [{ type: "thc", value: "50", unit: "mg" }, { type: "cbd", value: "250", unit: "mg" }],
    description: "A topical preview product that helps test wellness-oriented product copy, milligram cannabinoid values, and inventory status formatting.",
    priceLabel: "$22 each",
    priceMinorUnits: 2200,
    inventoryStatus: "mock",
    variants: [variant("mock-topical-001-jar", "2oz jar", 2200, 14)],
  },
  {
    id: "mock-accessory-001",
    name: "Greenway Glass Taster",
    brand: "Greenway Gear Preview",
    category: "paraphernalia",
    strainType: "unknown",
    thc: null,
    cbd: null,
    totalThc: null,
    totalCbd: null,
    compounds: [],
    description: "A non-cannabis accessory preview. Missing cannabinoid values intentionally remain null rather than zero to mirror Leafly data-standardization guidance.",
    priceLabel: "$6 each",
    priceMinorUnits: 600,
    inventoryStatus: "mock",
    variants: [variant("mock-accessory-001-each", "each", 600, 40)],
  },
];

export const menuCategories: GreenwayCategory[] = [
  "flower",
  "preroll",
  "edible-solid",
  "cartridge",
  "concentrate",
  "topical",
  "paraphernalia",
];

export function getMockMenuItemById(id: string) {
  return mockMenuItems.find((item) => item.id === id);
}
