/**
 * src/lib/ai/kb/product-categories-data.ts
 *
 * GENERATED by back-office/kb_seed/build_product_categories.py — do not edit by hand.
 * Verified customer-facing product-category taxonomy (edibles, liquids,
 * concentrates, topicals, pre-rolls, vapes, …). Each category maps to the WA
 * CCRS inventory_type names it corresponds to. Market-factual only; no medical
 * or effect claims.
 */

export type SeedProductCategory = {
  slug: string;
  name: string;
  group_key: "flower" | "concentrate" | "vape" | "edible" | "liquid" | "topical";
  summary: string;
  aliases: string[];
  wa_inventory_types: string[];
  sort_order: number;
};

export const PRODUCT_CATEGORIES: SeedProductCategory[] = [
  {
    slug: "flower", name: "Flower", group_key: "flower",
    summary: "Dried, cured cannabis buds sold by weight for smoking or as an ingredient in other products.",
    aliases: ["bud", "eighth", "nug"],
    wa_inventory_types: ["Flower Lot", "Marijuana Mix", "Marijuana Mix Packaged"], sort_order: 0,
  },
  {
    slug: "pre-roll", name: "Pre-Rolls", group_key: "flower",
    summary: "Ready-to-smoke cannabis joints rolled from ground flower; may be single or multi-packs and can be infused.",
    aliases: ["preroll", "joint", "pre roll", "cone"],
    wa_inventory_types: ["Marijuana Mix Infused"], sort_order: 1,
  },
  {
    slug: "wax", name: "Wax", group_key: "concentrate",
    summary: "A soft, opaque cannabis concentrate with a wax-like texture, made by extracting resin from flower.",
    aliases: ["budder", "crumble"],
    wa_inventory_types: ["Hydrocarbon Wax"], sort_order: 2,
  },
  {
    slug: "shatter", name: "Shatter", group_key: "concentrate",
    summary: "A hard, glass-like cannabis concentrate that is brittle and translucent.",
    aliases: [],
    wa_inventory_types: ["Food Grade Solvent Extract"], sort_order: 3,
  },
  {
    slug: "live-resin", name: "Live Resin", group_key: "concentrate",
    summary: "A concentrate made from fresh-frozen cannabis to preserve a fuller terpene profile.",
    aliases: ["resin"],
    wa_inventory_types: ["Marijuana Extract for Inhalation"], sort_order: 4,
  },
  {
    slug: "rosin", name: "Rosin", group_key: "concentrate",
    summary: "A solventless concentrate pressed from flower or hash using heat and pressure.",
    aliases: ["solventless"],
    wa_inventory_types: ["Marijuana Extract for Inhalation"], sort_order: 5,
  },
  {
    slug: "co2-oil", name: "CO2 Oil", group_key: "concentrate",
    summary: "A cannabis oil extracted using pressurized carbon dioxide, commonly used in cartridges.",
    aliases: ["co2", "hash oil"],
    wa_inventory_types: ["CO2 Hash Oil"], sort_order: 6,
  },
  {
    slug: "distillate", name: "Distillate", group_key: "concentrate",
    summary: "A highly refined cannabis oil produced by distillation, used in cartridges and edibles.",
    aliases: [],
    wa_inventory_types: ["Marijuana Extract for Inhalation"], sort_order: 7,
  },
  {
    slug: "kief", name: "Kief", group_key: "concentrate",
    summary: "The collected resin trichomes sifted from cannabis flower.",
    aliases: ["dry sift"],
    wa_inventory_types: ["Kief"], sort_order: 8,
  },
  {
    slug: "hash", name: "Hash", group_key: "concentrate",
    summary: "A traditional concentrate made by compressing cannabis resin.",
    aliases: ["hashish"],
    wa_inventory_types: ["Hash"], sort_order: 9,
  },
  {
    slug: "bubble-hash", name: "Bubble Hash", group_key: "concentrate",
    summary: "A solventless hash made using ice water and agitation to separate trichomes.",
    aliases: ["ice water hash", "water hash"],
    wa_inventory_types: ["Bubble Hash"], sort_order: 10,
  },
  {
    slug: "vape-cartridge", name: "Vape Cartridges", group_key: "vape",
    summary: "Pre-filled cartridges of cannabis oil that attach to a battery for vaporizing.",
    aliases: ["cart", "cartridge", "510"],
    wa_inventory_types: ["Marijuana Extract for Inhalation", "CO2 Hash Oil"], sort_order: 11,
  },
  {
    slug: "disposable-vape", name: "Disposable Vapes", group_key: "vape",
    summary: "All-in-one vaporizer pens pre-filled with cannabis oil and a built-in battery.",
    aliases: ["disposable", "all-in-one"],
    wa_inventory_types: ["Marijuana Extract for Inhalation"], sort_order: 12,
  },
  {
    slug: "edible-gummies", name: "Gummies", group_key: "edible",
    summary: "Chewy cannabis-infused candies dosed per piece.",
    aliases: ["gummy", "chew"],
    wa_inventory_types: ["Solid Marijuana Infused Edible"], sort_order: 13,
  },
  {
    slug: "edible-chocolate", name: "Chocolates", group_key: "edible",
    summary: "Cannabis-infused chocolate bars and confections dosed per serving.",
    aliases: ["chocolate bar"],
    wa_inventory_types: ["Solid Marijuana Infused Edible"], sort_order: 14,
  },
  {
    slug: "edible-candy", name: "Candy", group_key: "edible",
    summary: "Cannabis-infused hard candies, caramels, and other confections.",
    aliases: ["hard candy", "caramel"],
    wa_inventory_types: ["Solid Marijuana Infused Edible"], sort_order: 15,
  },
  {
    slug: "edible-baked", name: "Baked Goods", group_key: "edible",
    summary: "Cannabis-infused cookies, brownies, and other baked treats.",
    aliases: ["cookie", "brownie", "snack"],
    wa_inventory_types: ["Solid Marijuana Infused Edible"], sort_order: 16,
  },
  {
    slug: "edible-drink", name: "Beverages", group_key: "edible",
    summary: "Ready-to-drink cannabis-infused beverages and drink mixes.",
    aliases: ["drink", "beverage", "soda", "seltzer"],
    wa_inventory_types: ["Liquid Marijuana Infused Edible"], sort_order: 17,
  },
  {
    slug: "capsule", name: "Capsules", group_key: "edible",
    summary: "Cannabis-infused capsules or pills dosed per unit.",
    aliases: ["pill", "softgel"],
    wa_inventory_types: ["Capsule"], sort_order: 18,
  },
  {
    slug: "tincture", name: "Tinctures", group_key: "liquid",
    summary: "Liquid cannabis extracts dosed with a dropper, taken orally.",
    aliases: ["drops", "sublingual"],
    wa_inventory_types: ["Tincture", "Liquid Marijuana Infused Edible"], sort_order: 19,
  },
  {
    slug: "infused-oil", name: "Cooking Oils", group_key: "liquid",
    summary: "Cannabis-infused cooking oils and butters used as ingredients.",
    aliases: ["cooking oil", "infused butter", "ghee"],
    wa_inventory_types: ["Infused Cooking Oil", "Infused Dairy Butter or Fat in Solid Form"], sort_order: 20,
  },
  {
    slug: "topical", name: "Topicals", group_key: "topical",
    summary: "Cannabis-infused lotions, balms, and salves applied to the skin.",
    aliases: ["lotion", "balm", "salve", "cream"],
    wa_inventory_types: ["Marijuana Infused Topicals"], sort_order: 21,
  },
  {
    slug: "topical-bath", name: "Bath & Body", group_key: "topical",
    summary: "Cannabis-infused bath soaks and body products.",
    aliases: ["bath bomb", "bath soak"],
    wa_inventory_types: ["Marijuana Infused Topicals"], sort_order: 22,
  },
  {
    slug: "suppository", name: "Suppositories", group_key: "topical",
    summary: "Cannabis-infused suppositories.",
    aliases: [],
    wa_inventory_types: ["Suppository"], sort_order: 23,
  },
];

export const PRODUCT_CATEGORY_GROUPS: { key: SeedProductCategory["group_key"]; label: string }[] = [
  { key: "flower", label: "Flower" },
  { key: "concentrate", label: "Concentrates" },
  { key: "vape", label: "Vapes" },
  { key: "edible", label: "Edibles" },
  { key: "liquid", label: "Liquids & Oils" },
  { key: "topical", label: "Topicals" },
];
