/**
 * tests/compliance/owner-report-books-42.test.ts
 *
 * THE OWNER REPORT IS HELD TO THE SAME STANDARD AS THE CODE (standing rule 66).
 *
 * One document ships with this slice:
 *
 *   docs/MICHAEL-books-42-the-financial-statements.md
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THIS IS A TEST AND NOT A PROOFREAD
 * ─────────────────────────────────────────────────────────────────────────────
 * This particular report is more dangerous than most, because it is a TEACHING
 * document. Michael asked to be taught how to read his own statements, so he
 * will read this one carefully, believe it, and act on it for years. Every
 * arithmetic claim in it therefore has to be re-derived from the code that
 * produces the same figures on screen, not checked by eye.
 *
 * The argument for this file was proven inside this very slice, twice:
 *
 *   1. The worked example in the report claimed a gross margin of "47.9%".
 *      The real figure from the same inputs is 42.71%. I wrote a plausible
 *      number rather than computing one, and reading it back did not catch it.
 *      Executing it did.
 *
 *   2. The books-38 gap report went red the moment the financial statements
 *      screen was built, because its claim "nothing imports this engine" had
 *      become false. That is a gate on a DOCUMENT catching a document that had
 *      gone stale within a single slice.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT IS BEING PROTECTED
 * ─────────────────────────────────────────────────────────────────────────────
 *   1. THE WORKED EXAMPLE. Every dollar figure in the report's table is
 *      recomputed from `workedExample()` — the same function the screen uses.
 *      The report and the screen cannot show different numbers.
 *
 *   2. THE HEADLINE SENTENCE. The sentence Michael is meant to remember is
 *      generated by `theSentence()`, and the report must contain it verbatim.
 *
 *   3. THE DEFECT WRITE-UP. The report states specific wrong figures the engine
 *      produced ($13,200.00 net against $10,000.00 gross). Those are re-derived
 *      by actually running the engine without the guard. If someone fixes the
 *      engine upstream, the report's account of the bug becomes historical
 *      fiction and this test says so.
 *
 *   4. THE QUOTES. §280E and the regulations are quoted. Each fragment must
 *      resolve through the authority registry, so the report cannot quote text
 *      I invented.
 *
 *   5. THE COUNTED CLAIMS. "Four statements", "seven steps", "seven
 *      principles", and the test counts quoted in the closing section.
 *
 *   6. THE PDF SHIPPED. A markdown file Michael cannot open is not a delivery.
 */

import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import {
  workedExample,
  theSentence,
  STATEMENT_LESSONS,
  STATEMENT_PRINCIPLES,
} from "@/lib/accounting/financial-statements-reading-mentor";
import {
  READING_ORDER,
  STATEMENT_SCOPE_NOTE,
  basisPoints,
  adaptTrialBalance,
} from "@/lib/accounting/financial-statements-ui-core";
import {
  buildIncomeStatement,
  formatCents,
} from "@/lib/accounting/financial-statements-core";
import { findGuidanceAuthority } from "@/lib/accounting/books-guidance-core";
import type { TrialBalanceView } from "@/lib/accounting/books-ledger-guidance-core";
import {
  GREENWAY_CONTRA_CODES,
  GREENWAY_EXCISE_LIABILITY_CODE,
  GREENWAY_FACTS,
  greenwayView,
} from "./greenway-chart-fixture";

const ROOT = process.cwd();
const REPORT_REL = "docs/MICHAEL-books-42-the-financial-statements.md";
const REPORT = readFileSync(join(ROOT, REPORT_REL), "utf8");

// ---------------------------------------------------------------------------
// 1) THE WORKED EXAMPLE — EVERY FIGURE RE-DERIVED.
// ---------------------------------------------------------------------------

describe("the worked example in the report matches the worked example in the code", () => {
  const lines = workedExample();
  const amountOf = (label: string) => {
    const l = lines.find((x) => x.label === label);
    expect(l, `the code no longer produces a line called '${label}'`).toBeDefined();
    return l!.amountCents;
  };

  it("every line's formatted amount appears in the report", () => {
    // This is the whole point of the file. The report is a table of numbers
    // that Michael will trust; each one must be the number the software
    // actually produces, not the number I typed while writing prose.
    for (const l of lines) {
      expect(
        REPORT,
        `the report is missing ${l.label} = ${formatCents(l.amountCents)}`,
      ).toContain(formatCents(l.amountCents));
    }
  });

  it("the specific figures the narrative leans on are the computed ones", () => {
    expect(REPORT).toContain(formatCents(amountOf("Net sales")));
    expect(REPORT).toContain(formatCents(amountOf("GROSS INCOME — the number §280E taxes")));
    expect(REPORT).toContain(formatCents(amountOf("Book net income")));
    expect(REPORT).toContain(formatCents(amountOf("THE COST OF §280E, this month")));
  });

  it("the report's claim that the §280E cost EXCEEDS the profit is still true", () => {
    // The report says "more than seven times the profit". If the illustrative
    // constants are ever edited, that sentence could silently become false.
    const cost = amountOf("THE COST OF §280E, this month");
    const profit = amountOf("Book net income");
    expect(cost).toBeGreaterThan(profit);
    expect(cost / profit).toBeGreaterThan(7);
    expect(REPORT).toMatch(/more than seven times the profit/i);
  });

  it("the gross margin the report quotes is the gross margin the code computes", () => {
    // THE 47.9% INCIDENT. This assertion is the direct descendant of a false
    // claim that shipped in the first draft of this document.
    const netSales = amountOf("Net sales");
    const grossIncome = amountOf("GROSS INCOME — the number §280E taxes");
    const bp = basisPoints(grossIncome, netSales);
    expect(bp).toBe(4271);
    expect(REPORT).toContain("42.71%");

    // A SECOND MISTAKE, CAUGHT BY THE SAME GATE, AND WORTH LEAVING WRITTEN DOWN.
    //
    // This assertion originally read `.not.toContain("47.9%")`, on the theory
    // that the wrong figure must never appear. It failed immediately — because
    // the report deliberately QUOTES the wrong figure twice, in the two places
    // where it owns up to having published it.
    //
    // So the rule being enforced here is not "the string 47.9% is banned". It
    // is the narrower and actually correct one: every appearance of the old
    // figure must be an admission, never a live claim. Each occurrence has to
    // sit in a sentence that also contains the corrected figure or the word
    // "wrong"/"originally". A blanket ban would have forced me to delete the
    // confession in order to make the build pass, which is the exact incentive
    // a gate must never create.
    const occurrences = [...REPORT.matchAll(/47\.9%/g)];
    expect(
      occurrences.length,
      "the old figure vanished; the report should still own the mistake",
    ).toBeGreaterThan(0);

    for (const m of occurrences) {
      const at = m.index ?? 0;
      const sentence = REPORT.slice(Math.max(0, at - 400), at + 400);
      expect(
        /42\.71%/.test(sentence),
        `an occurrence of 47.9% at offset ${String(at)} is not accompanied by the correction`,
      ).toBe(true);
      expect(
        /(originally|wrong|mistake|claimed)/i.test(sentence),
        `an occurrence of 47.9% at offset ${String(at)} reads as a live claim, not an admission`,
      ).toBe(true);
    }
  });

  it("the headline sentence in the report is the one the code generates, verbatim", () => {
    expect(REPORT).toContain(theSentence());
  });
});

// ---------------------------------------------------------------------------
// 2) THE DEFECT WRITE-UP IS STILL AN ACCURATE ACCOUNT OF THE DEFECT.
// ---------------------------------------------------------------------------

describe("the report's account of the excise defect is re-derived, not remembered", () => {
  /**
   * Rebuild the exact scenario the report describes: a BALANCED trial balance
   * using Greenway's real chart codes, with the excise liability passed as an
   * excise account — which is what any reasonable person would do.
   */
  /**
   * THE FIXTURE IS IMPORTED, NOT REBUILT. Two mistakes are recorded here,
   * because both are the kind that this document is supposed to prevent.
   *
   * MISTAKE ONE — the cast. The first draft wrote the `TrialBalanceView` out by
   * hand and cast it with `as unknown as TrialBalanceView`. That cast silenced
   * the compiler about SIX missing fields — `debitCents`, `creditCents`,
   * `nature`, `totalDebitCents`, `totalCreditCents`, `differenceCents` — and the
   * engine duly computed `NaN`, which `assertIntegerCents` caught at runtime. A
   * cast is a promise to the compiler that you know better than it does, and I
   * did not.
   *
   * MISTAKE TWO — the second set of books, which is the more interesting one.
   * Having removed the cast, the fixture was rebuilt properly with the real
   * `buildTrialBalance()`. It type-checked, it balanced, it ran — and it proved
   * the defect produced net sales of $13,700.00, while the report and the
   * ui-core suite both said $13,200.00. Neither number was wrong. They were
   * outputs of the same engine fed two different sets of books: the fixture
   * invented here had no contra-revenue account, so `50900 Discounts & Comps`
   * was not there to subtract its $500.
   *
   * The failure was not arithmetic. It was having TWO fixtures both claiming to
   * be "Greenway's books". So the fixture was extracted to
   * `greenway-chart-fixture.ts` and both suites now import it. The report's
   * figure and the ui-core suite's figure are now the same figure, derived from
   * the same books, and cannot drift apart again without the build failing.
   *
   * That is the whole thesis of this slice, applied to itself: a number that
   * balances in one place can still be wrong in another, and only executing
   * both against a single source of truth exposes it.
   */
  const facts = GREENWAY_FACTS;
  const view: TrialBalanceView = greenwayView();

  it("the trial balance used really does balance — otherwise the demo proves nothing", () => {
    // Two independent checks. The first is the engine's own verdict; the second
    // re-adds the signed balances by hand, so a bug in `foots` cannot make a
    // crooked demonstration look straight.
    expect(view.foots).toBe(true);
    expect(view.differenceCents).toBe(0);
    expect(view.lines.reduce((a, l) => a + l.balanceCents, 0)).toBe(0);
    expect(view.unmappedAccountCodes).toEqual([]);
    expect(view.abnormalCount).toBe(0);
    // And every line carries real debit/credit columns, which is precisely what
    // the hand-written literal failed to do.
    for (const l of view.lines) {
      expect(Number.isInteger(l.debitCents), `${l.accountCode} debitCents`).toBe(true);
      expect(Number.isInteger(l.creditCents), `${l.accountCode} creditCents`).toBe(true);
    }
    expect(view.totalDebitCents).toBe(view.totalCreditCents);
  });

  it("the engine really does produce net sales ABOVE gross sales when handed the liability", () => {
    const adapted = adaptTrialBalance(view, facts, "greenway", "2026-01-01", "2026-12-31");
    expect(adapted.ok).toBe(true);
    if (!adapted.ok) return;

    // Called DIRECTLY, bypassing the guard in buildFsScreen. This is the whole
    // point: the guard is the only thing standing between Michael and this.
    const result = buildIncomeStatement({
      trialBalance: adapted.trialBalance,
      exciseAccountCodes: [GREENWAY_EXCISE_LIABILITY_CODE],
      contraRevenueAccountCodes: GREENWAY_CONTRA_CODES,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;

    expect(result.statement.grossSalesCents).toBe(10_000_00);
    expect(result.statement.netSalesCents).toBe(13_200_00);
    // The defining absurdity, asserted as an inequality so it reads as the
    // claim it is rather than as two magic numbers.
    expect(result.statement.netSalesCents).toBeGreaterThan(result.statement.grossSalesCents);
  });

  /**
   * THE WHOLE TABLE, NOT JUST THE HEADLINE.
   *
   * The earlier version of this test checked only that "$13,200.00" and
   * "$10,000.00" appeared somewhere in the document. That is far too weak: the
   * table has seven rows, and the first draft got the five rows BENEATH the
   * headline wrong while the headline itself was right. A gate that checks the
   * memorable number and ignores the supporting ones approves a table that is
   * mostly wrong.
   *
   * So every figure in the defect table is now re-derived from the engine and
   * required to appear in the report — both the WRONG column (what the engine
   * produced with the liability passed as excise) and the TRUE column (what it
   * produces with the excise codes correctly empty).
   */
  it("the figures the report prints for the defect are those exact figures", () => {
    const adapted = adaptTrialBalance(view, facts, "greenway", "2026-07-01", "2026-07-31");
    expect(adapted.ok).toBe(true);
    if (!adapted.ok) return;

    const wrong = buildIncomeStatement({
      trialBalance: adapted.trialBalance,
      exciseAccountCodes: [GREENWAY_EXCISE_LIABILITY_CODE],
      contraRevenueAccountCodes: GREENWAY_CONTRA_CODES,
    });
    const right = buildIncomeStatement({
      trialBalance: adapted.trialBalance,
      exciseAccountCodes: [],
      contraRevenueAccountCodes: GREENWAY_CONTRA_CODES,
    });
    expect(wrong.ok && right.ok).toBe(true);
    if (!wrong.ok || !right.ok) return;

    const w = wrong.statement;
    const r = right.statement;

    /*
     * WHY THE TABLE IS PARSED ROW BY ROW INSTEAD OF SEARCHED WITH `toContain`.
     *
     * The first version of this check asserted only that each figure appeared
     * SOMEWHERE in the document. Tamper-testing it (standing rule 16) showed
     * that it does not fire: changing the table's cost-of-goods-sold row from
     * $6,000.00 to $6,500.00 left the suite entirely green, because $6,000.00
     * still appeared two rows lower as net income. A document-wide substring
     * search is satisfied by a coincidence.
     *
     * That is the same defect as the one the report describes, in miniature: a
     * check that passes for a reason unrelated to the thing being checked. So
     * the table is located, its rows are parsed, and each row's cells are
     * matched against the figure the engine produced for THAT row.
     */
    // The document contains SEVERAL money tables — the worked example's is much
    // earlier and also has a "Gross sales" row. Locate the defect table by its
    // unique header ("Engine output" / "The truth") and read only its rows, so
    // this check cannot accidentally validate itself against a different table.
    const allLines = REPORT.split("\n");
    const headerAt = allLines.findIndex(
      (l) => /^\|/.test(l) && /Engine output/i.test(l) && /The truth/i.test(l),
    );
    expect(
      headerAt,
      "the defect table's header row ('Engine output' | 'The truth') was not found",
    ).toBeGreaterThan(-1);

    const tableRows: string[] = [];
    for (let i = headerAt + 1; i < allLines.length; i += 1) {
      const l = allLines[i];
      if (!/^\|/.test(l)) break; // the table ended
      if (/\$/.test(l)) tableRows.push(l);
    }
    expect(tableRows.length, "the defect table has no money rows").toBeGreaterThan(5);
    const rowFor = (label: RegExp): readonly string[] => {
      const row = tableRows.find((l) => label.test(l));
      expect(row, `the defect table has no row matching ${String(label)}`).toBeDefined();
      return (row ?? "").split("|").map((c) => c.trim());
    };

    const checkRow = (label: RegExp, wrongCents: number, trueCents: number): void => {
      const cells = rowFor(label);
      const joined = cells.join(" ");
      expect(
        joined,
        `the '${String(label)}' row should show the engine's wrong figure ${formatCents(wrongCents)}`,
      ).toContain(formatCents(wrongCents));
      expect(
        joined,
        `the '${String(label)}' row should show the true figure ${formatCents(trueCents)}`,
      ).toContain(formatCents(trueCents));
    };

    checkRow(/Gross sales/i, r.grossSalesCents, r.grossSalesCents);
    checkRow(/^\|\s*\*?\*?Net sales/i, w.netSalesCents, r.netSalesCents);
    checkRow(/Cost of goods sold/i, r.costOfGoodsSoldCents, r.costOfGoodsSoldCents);
    checkRow(/Gross income/i, w.grossIncomeCents, r.grossIncomeCents);
    checkRow(/Operating expenses/i, r.operatingExpensesCents, r.operatingExpensesCents);
    checkRow(/Net income/i, w.netIncomeCents, r.netIncomeCents);

    // THE CLAIM THE TABLE IS MAKING. The report tells Michael that every
    // subtotal is overstated by exactly the trust liability. That is the whole
    // teaching point, so it is asserted as arithmetic rather than trusted as
    // prose: three independent differences, all equal to the same $3,700.00.
    const overstatement = w.netSalesCents - r.netSalesCents;
    expect(overstatement).toBe(3_700_00);
    expect(w.grossIncomeCents - r.grossIncomeCents).toBe(overstatement);
    expect(w.netIncomeCents - r.netIncomeCents).toBe(overstatement);
    expect(REPORT).toContain(formatCents(overstatement));
    expect(REPORT).toMatch(/overstated by exactly/i);

    // And the defining absurdity is still stated in words, not just in a table.
    expect(REPORT).toMatch(/net sales (exceeded|above) gross sales/i);
  });

  it("the report names the real account, the real statute and the real reason", () => {
    expect(REPORT).toContain(GREENWAY_EXCISE_LIABILITY_CODE);
    expect(REPORT).toContain("Cannabis Excise Tax Payable");
    expect(REPORT).toContain("RCW 69.50.535(4)");
    // The MECHANISM, not just the symptom. Michael should be able to explain
    // why the number moved the way it did, so the report has to say that a
    // liability carries a credit balance and that subtracting one therefore
    // added. Checked as two facts rather than one brittle sentence.
    expect(REPORT).toMatch(/credit balance/i);
    expect(REPORT).toMatch(/subtracting (it|a negative) added/i);
  });

  it("the report explains WHY the engine's own tests missed it", () => {
    expect(REPORT).toContain("4900");
    expect(REPORT).toContain("6900");
  });
});

// ---------------------------------------------------------------------------
// 3) QUOTED AUTHORITY.
// ---------------------------------------------------------------------------

describe("every statute the report quotes is real", () => {
  it("quotes §280E and the fragment resolves through the registry", () => {
    expect(REPORT).toContain("IRC §280E");
    expect(REPORT).toMatch(/No deduction or credit shall be allowed/);

    // Both directions: the words must exist in the registry, so the report
    // cannot quote text that was written for the report.
    const ids = ["IRC_280E", "IRC_280E_TRAFFICKING"];
    const found = ids.map((i) => findGuidanceAuthority(i)).filter(Boolean);
    expect(found.length, "no §280E authority resolves in the registry").toBeGreaterThan(0);
    const text = found.map((a) => JSON.stringify(a)).join(" ");
    expect(text).toMatch(/No deduction or credit shall be allowed/);
  });

  it("cites the regulation that makes cost of goods sold different from a deduction", () => {
    expect(REPORT).toContain("Treas. Reg. §1.61-3(a)");
    expect(REPORT).toMatch(/subtracted in \*?\*?arriving at\*?\*? income rather than deducted/i);
  });

  it("cites the physical-count requirement for inventory", () => {
    expect(REPORT).toContain("Treas. Reg. §1.471-2(d)");
    expect(REPORT).toMatch(/physical count/i);
  });

  it("cites the statute that makes the excise trust money", () => {
    expect(REPORT).toContain("RCW 69.50.535(4)");
  });
});

// ---------------------------------------------------------------------------
// 4) THE COUNTED CLAIMS.
// ---------------------------------------------------------------------------

describe("the countable claims are counted from the code", () => {
  it("there really are four statements, and the report's table lists all four", () => {
    expect(STATEMENT_LESSONS).toHaveLength(4);
    for (const l of STATEMENT_LESSONS) {
      // Each statement's QUESTION is the thing the report teaches him to use.
      expect(REPORT.toLowerCase()).toContain(l.statement.replace("_", " "));
    }
    expect(REPORT).toMatch(/Income statement/);
    expect(REPORT).toMatch(/Balance sheet/);
    expect(REPORT).toMatch(/Cash flow statement/);
    expect(REPORT).toMatch(/Statement of equity/);
  });

  it("the reading order really has seven steps, and the report says seven", () => {
    expect(READING_ORDER).toHaveLength(7);
    expect(REPORT).toMatch(/Seven steps|seven steps/);
    // Every step number appears as a heading in the report.
    for (const s of READING_ORDER) {
      expect(REPORT, `step ${s.step} is missing from the report`).toContain(`**Step ${s.step} —`);
    }
  });

  it("there really are seven principles, and the report promises seven", () => {
    expect(STATEMENT_PRINCIPLES).toHaveLength(7);
  });

  it("the report's claim about the scope note matches the scope note in the code", () => {
    expect(STATEMENT_SCOPE_NOTE).toMatch(/not audited/);
    expect(REPORT).toMatch(/not audited, not reviewed/);
    expect(REPORT).toMatch(/does not bind you/);
  });

  it("the test counts the report quotes are the real ones", () => {
    // If a later slice adds tests, these numbers become wrong. Better that the
    // build says so than that Michael reads a stale figure.
    const count = (rel: string) => {
      const src = readFileSync(join(ROOT, rel), "utf8");
      return (src.match(/^\s*it\(/gm) ?? []).length;
    };

    const ui = count("tests/compliance/financial-statements-ui-core.test.ts");
    const mentor = count("tests/compliance/financial-statements-reading-mentor.test.ts");
    const acct = count("tests/compliance/account-type-single-truth.test.ts");

    expect(REPORT, `ui-core test count is ${ui}`).toContain(`**${ui} tests** on the screen's decision layer`);
    expect(REPORT, `reading-mentor test count is ${mentor}`).toContain(`**${mentor} tests** on the teaching layer`);
    expect(REPORT, `account-type test count is ${acct}`).toContain(`**${acct} tests** on the account-type gate`);
  });
});

// ---------------------------------------------------------------------------
// 5) THE HONESTY SECTIONS.
// ---------------------------------------------------------------------------

describe("the report is honest about what was not done", () => {
  it("admits the 47.9% mistake by name rather than quietly correcting it", () => {
    expect(REPORT).toMatch(/originally claimed a gross margin of 47\.9%/i);
  });

  it("states plainly that two of the four statements do not render", () => {
    expect(REPORT).toMatch(/statement of cash flows/i);
    expect(REPORT).toMatch(/blocked/i);
  });

  it("names every document still needed, with the form number", () => {
    for (const form of ["Form 2553", "CP261", "Schedule M-2", "Form 7203"]) {
      expect(REPORT, `the report stopped asking for ${form}`).toContain(form);
    }
  });

  it("restates the boundary — this prepares statements and transmits nothing", () => {
    expect(REPORT).toMatch(/transmits nothing|not become a filing agent|did not become a filing agent/i);
  });

  it("records the account-type duplication as policed debt rather than hiding it", () => {
    expect(REPORT).toMatch(/written out four separate times/i);
    expect(REPORT).toMatch(/A known duplicate with a gate on it is manageable/i);
  });
});

// ---------------------------------------------------------------------------
// 6) THE DELIVERY.
// ---------------------------------------------------------------------------

describe("the document actually ships", () => {
  it("the markdown exists and is substantial", () => {
    expect(existsSync(join(ROOT, REPORT_REL))).toBe(true);
    expect(REPORT.length).toBeGreaterThan(15_000);
  });

  it("addresses Michael by name and names the slice", () => {
    expect(REPORT).toContain("Michael");
    expect(REPORT).toContain("books-42");
  });

  it("the PDF was built and is not a stub", () => {
    const pdf = join(ROOT, "docs/MICHAEL-books-42-the-financial-statements.pdf");
    expect(existsSync(pdf), "the PDF has not been built — a markdown file is not a delivery").toBe(
      true,
    );
    expect(statSync(pdf).size).toBeGreaterThan(20_000);
  });
});
