"use client";

/**
 * CcrsAdvisorPanel (Slice 54) — an on-demand, DRAFTS-ONLY AI briefing for the
 * CCRS batch. Click "Ask the CCRS advisor" and the server regenerates the batch
 * summary + sync issues and returns a plain-language read: what's ready, what
 * blocks the upload, and the exact order of steps. Read-only / advisory.
 */
import { useState, useTransition } from "react";
import { useToast } from "@/components/admin/ux";
import {
  generateCcrsAdviceAction,
  type CcrsAdvisorResult,
} from "@/app/admin/reports/compliance/advisor-action";
import type { CcrsAdvice } from "@/lib/compliance/ccrs-advisor";

type Props = {
  aiEnabled: boolean;
  sp: { from?: string; to?: string; range?: string; year?: string };
};

function BulletList({
  title,
  items,
  tone,
}: {
  title: string;
  items: string[];
  tone: "good" | "warn" | "action";
}) {
  if (items.length === 0) return null;
  const color = tone === "good" ? "text-[#7ed957]" : tone === "warn" ? "text-[#ff6b6b]" : "text-white";
  const dot = tone === "good" ? "bg-[#7ed957]" : tone === "warn" ? "bg-[#ff6b6b]" : "bg-[#8ab4f8]";
  return (
    <div>
      <div className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{title}</div>
      <ul className="mt-1.5 space-y-1.5">
        {items.map((it, i) => (
          <li key={i} className="flex gap-2 text-sm text-white/80">
            <span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
            <span>{it}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function CcrsAdvisorPanel({ aiEnabled, sp }: Props) {
  const { toast } = useToast();
  const [advice, setAdvice] = useState<CcrsAdvice | null>(null);
  const [pending, startTransition] = useTransition();

  function run() {
    setAdvice(null);
    startTransition(async () => {
      const res: CcrsAdvisorResult = await generateCcrsAdviceAction(sp);
      if (!res.ok) {
        toast({ tone: "error", message: res.error });
        return;
      }
      setAdvice(res.advice);
      toast({ tone: "success", message: "CCRS advisor ready." });
    });
  }

  return (
    <section className="rounded-2xl border border-[#7ed957]/25 bg-[#7ed957]/[0.04] p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="flex items-center gap-2 text-base font-semibold text-white">
            <span>✨ CCRS advisor</span>
          </h2>
          <p className="mt-0.5 text-sm text-white/60">
            A plain-language read of this batch — what&apos;s ready, what would fail, and the exact upload order.
            Grounded in the batch counts and sync report above (no customer details sent). Advisory / drafts only.
          </p>
        </div>
        {aiEnabled && (
          <button
            type="button"
            onClick={run}
            disabled={pending}
            className="rounded-lg bg-[#7ed957] px-4 py-2 text-sm font-bold text-black transition hover:bg-[#6bc746] disabled:opacity-50"
          >
            {pending ? "Reviewing…" : advice ? "Re-review" : "Ask the CCRS advisor"}
          </button>
        )}
      </div>

      {!aiEnabled ? (
        <p className="mt-3 text-xs text-[#ffd700]">
          The advisor turns on once an <code className="font-mono">AI_API_KEY</code> is set. The batch, files, and sync
          report above work without it.
        </p>
      ) : advice ? (
        <div className="mt-4 space-y-4 rounded-xl border border-white/10 bg-black/40 p-4">
          {advice.headline && <p className="text-sm font-medium text-white/90">{advice.headline}</p>}
          <div className="grid gap-4 md:grid-cols-3">
            <BulletList title="Ready" items={advice.ready} tone="good" />
            <BulletList title="Fix first" items={advice.blockers} tone="warn" />
            <BulletList title="Upload steps" items={advice.steps} tone="action" />
          </div>
          <p className="text-[0.65rem] text-white/35">
            Generated by {advice.model} from the aggregate batch above. Advisory only — verify against the sync report
            and review the files before uploading.
          </p>
        </div>
      ) : (
        <p className="mt-3 text-xs text-white/45">
          Click <span className="font-semibold text-white/70">Ask the CCRS advisor</span> for a checklist you can follow
          before you upload.
        </p>
      )}
    </section>
  );
}
