"use client";

/**
 * ForecastInsightsPanel — on-demand AI outlook for the Forecast tab (Slice 45).
 * Click "Generate outlook" and the server narrates the statistical forecast:
 * a headline, what to expect, what to watch (uncertainty), and concrete next
 * steps (staffing/ordering/promotions). Read-only / advisory.
 */
import { useState, useTransition } from "react";
import { Button } from "@/components/admin/ui";
import { useToast } from "@/components/admin/ux";
import {
  generateForecastInsightsAction,
  type ForecastInsightsResult,
} from "@/app/admin/reports/forecast/actions";
import type { ForecastInsights } from "@/lib/reports/forecast-ai";

function BulletList({ title, items, tone }: { title: string; items: string[]; tone: "good" | "warn" | "action" }) {
  if (items.length === 0) return null;
  const color = tone === "good" ? "text-[var(--admin-accent)]" : tone === "warn" ? "text-[var(--admin-gold)]" : "text-white";
  const dot = tone === "good" ? "bg-[var(--admin-accent)]" : tone === "warn" ? "bg-[var(--admin-gold)]" : "bg-[#8ab4f8]";
  return (
    <div>
      <div className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{title}</div>
      <ul className="mt-1.5 space-y-1.5">
        {items.map((it, i) => (
          <li key={i} className="flex gap-2 text-sm text-white/80">
            <span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
            <span>{it}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function ForecastInsightsPanel({ horizon, aiEnabled }: { horizon: number; aiEnabled: boolean }) {
  const { toast } = useToast();
  const [insights, setInsights] = useState<ForecastInsights | null>(null);
  const [pending, startTransition] = useTransition();

  function run() {
    setInsights(null);
    startTransition(async () => {
      const res: ForecastInsightsResult = await generateForecastInsightsAction(horizon);
      if (!res.ok) {
        toast({ tone: "error", message: res.error });
        return;
      }
      setInsights(res.insights);
      toast({ tone: "success", message: "AI outlook ready." });
    });
  }

  return (
    <section className="rounded-2xl border border-[var(--admin-gold)]/25 bg-[var(--admin-gold)]/[0.04] p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="flex items-center gap-2 text-base font-semibold text-white">
            <span>🔮 AI forecast outlook</span>
          </h2>
          <p className="mt-0.5 text-sm text-white/60">
            A plain-language read on the next {horizon} days — what to expect, what to watch, and how
            to staff, order, and promote around it.
          </p>
        </div>
        {aiEnabled && (
          <Button type="button" onClick={run} disabled={pending} variant="special" size="sm">
            {pending ? "Analyzing…" : insights ? "Regenerate" : "Generate outlook"}
          </Button>
        )}
      </div>

      {!aiEnabled ? (
        <p className="mt-3 text-xs text-[var(--admin-gold)]">
          The AI outlook turns on once an <code className="font-mono">AI_API_KEY</code> is set. The
          forecast charts and accuracy grade work without it.
        </p>
      ) : insights ? (
        <div className="mt-4 space-y-4 rounded-xl border border-white/10 bg-black/40 p-4">
          {insights.headline && <p className="text-sm font-medium text-white/90">{insights.headline}</p>}
          <div className="grid gap-4 md:grid-cols-3">
            <BulletList title="What to expect" items={insights.outlook} tone="good" />
            <BulletList title="Watch out" items={insights.watchouts} tone="warn" />
            <BulletList title="Do next" items={insights.actions} tone="action" />
          </div>
          <p className="text-[0.65rem] text-white/35">
            Generated by {insights.model} from the statistical forecast above (no customer details
            sent). A forecast is a range, not a promise — advisory only.
          </p>
        </div>
      ) : (
        <p className="mt-3 text-xs text-white/45">
          Click <span className="font-semibold text-white/70">Generate outlook</span> for an instant
          plan you can share with the team.
        </p>
      )}
    </section>
  );
}
