"use client";

/**
 * ReportInsightsPanel — an on-demand AI briefing for the Reports page (PR E).
 * Click "Generate insights" and the server re-reads the same aggregate
 * analytics the page renders, then returns a plain-language summary:
 * a headline, what's going well, what to watch, and 2-3 next actions.
 *
 * Read-only / advisory. Gated on the AI key being present (graceful no-op).
 */
import { useState, useTransition } from "react";
import { useToast } from "@/components/admin/ux";
import {
  generateReportInsightsAction,
  type ReportInsightsResult,
} from "@/app/admin/reports/actions";
import type { ReportInsights } from "@/lib/reports/ai-insights";

type Props = { days: number; aiEnabled: boolean };

function BulletList({
  title,
  items,
  tone,
}: {
  title: string;
  items: string[];
  tone: "good" | "warn" | "action";
}) {
  if (items.length === 0) return null;
  const color =
    tone === "good" ? "text-[#7ed957]" : tone === "warn" ? "text-[#ffd700]" : "text-white";
  const dot =
    tone === "good" ? "bg-[#7ed957]" : tone === "warn" ? "bg-[#ffd700]" : "bg-[#8ab4f8]";
  return (
    <div>
      <div className={`text-xs font-semibold uppercase tracking-wide ${color}`}>{title}</div>
      <ul className="mt-1.5 space-y-1.5">
        {items.map((it, i) => (
          <li key={i} className="flex gap-2 text-sm text-white/80">
            <span className={`mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${dot}`} />
            <span>{it}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

export function ReportInsightsPanel({ days, aiEnabled }: Props) {
  const { toast } = useToast();
  const [insights, setInsights] = useState<ReportInsights | null>(null);
  const [pending, startTransition] = useTransition();

  function run() {
    setInsights(null);
    startTransition(async () => {
      const res: ReportInsightsResult = await generateReportInsightsAction(days);
      if (!res.ok) {
        toast({ tone: "error", message: res.error });
        return;
      }
      setInsights(res.insights);
      toast({ tone: "success", message: "AI insights ready." });
    });
  }

  return (
    <section className="rounded-2xl border border-[#7ed957]/25 bg-[#7ed957]/[0.04] p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="flex items-center gap-2 text-base font-semibold text-white">
            <span>✨ AI insights</span>
          </h2>
          <p className="mt-0.5 text-sm text-white/60">
            A plain-language read on the last {days} days — what&apos;s working, what to watch, and
            what to do next.
          </p>
        </div>
        {aiEnabled && (
          <button
            type="button"
            onClick={run}
            disabled={pending}
            className="rounded-lg bg-[#7ed957] px-4 py-2 text-sm font-bold text-black transition hover:bg-[#6bc746] disabled:opacity-50"
          >
            {pending ? "Analyzing…" : insights ? "Regenerate" : "Generate insights"}
          </button>
        )}
      </div>

      {!aiEnabled ? (
        <p className="mt-3 text-xs text-[#ffd700]">
          AI insights turn on once an <code className="font-mono">AI_API_KEY</code> is set. The
          charts and tables on this page work without it.
        </p>
      ) : insights ? (
        <div className="mt-4 space-y-4 rounded-xl border border-white/10 bg-black/40 p-4">
          {insights.headline && (
            <p className="text-sm font-medium text-white/90">{insights.headline}</p>
          )}
          <div className="grid gap-4 md:grid-cols-3">
            <BulletList title="Going well" items={insights.wins} tone="good" />
            <BulletList title="Watch out" items={insights.watchouts} tone="warn" />
            <BulletList title="Do next" items={insights.actions} tone="action" />
          </div>
          <p className="text-[0.65rem] text-white/35">
            Generated by {insights.model} from the aggregate numbers above (no customer details
            sent). Advisory only.
          </p>
        </div>
      ) : (
        <p className="mt-3 text-xs text-white/45">
          Click <span className="font-semibold text-white/70">Generate insights</span> for an
          instant summary you can paste into a team update.
        </p>
      )}
    </section>
  );
}
