/**
 * ACH AUTHORITIES - the written rules behind paying people by direct deposit.
 *
 * R39 S1. GENERATED by /workspace/scripts/r39_gen_authorities.py from quotes
 * that r39_extract_quotes.py copied mechanically out of docs/authorities/.
 * No quote below was typed by hand. Edit the mirrored source and regenerate;
 * do not hand-edit a quote here, because the verbatim test will reject it.
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WHAT THIS REGISTRY ANSWERS
 * ──────────────────────────────────────────────────────────────────────────
 *
 *   - How is a payee's account proven to be real before money goes to it?
 *     (prenote vs. micro-entry "test credit" - Nacha's own definitions)
 *   - What must happen when somebody asks to change where their money goes?
 *     (Nacha Fraud Monitoring Phase 2; the WA State Auditor's callback advice)
 *   - How long must the signed form be kept? (Nacha 2 years after
 *     termination via ODFI summaries; WAC 314-55-087 five years for licensee
 *     employee records)
 *   - Which day is a banking day? (FedACH holiday rule)
 *   - Is an e-signed form as good as paper? (RCW 1.80 / 15 U.S.C. §7001, §7006)
 *
 * ──────────────────────────────────────────────────────────────────────────
 * WEIGHT, HONESTLY
 * ──────────────────────────────────────────────────────────────────────────
 *
 * The Nacha Operating Rules themselves are a licensed publication and are not
 * mirrored. What IS mirrored is Nacha's own public rule summaries and the
 * originator guides that ODFIs (banks) publish to their customers. Those are
 * tagged `industry_guidance`: they tell Greenway what its bank will expect,
 * but they are not law, and the badge on screen says so. The Washington and
 * federal e-signature statutes and WAC 314-55-087 are binding law and carry
 * their own kinds.
 *
 * STANDING RULE 24: every `quote` is a character-for-character copy of the
 * file named in `sourceFile`; tests/compliance/r39-ach-authorities.test.ts and
 * scripts/verify-verbatim-quotes.ts both re-read it on every run.
 */

export type AchAuthorityKind = "industry_guidance" | "state_manual" | "state_law" | "statute";

export type AchAuthority = {
  readonly id: AchAuthorityId;
  readonly kind: AchAuthorityKind;
  /** Full citation as shown on screen. Publication prefixes are routed by ACH_PUBLICATION_FILES. */
  readonly citation: string;
  /** Mirrored file, relative to docs/authorities/. */
  readonly sourceFile: string;
  /** Public URL of the original. */
  readonly source: string;
  readonly quote: string;
  readonly whatItMeansHere: string;
};

