/**
 * src/lib/compliance/ccrs-sale-correction-core.ts  (Task Q)
 *
 * PURE builder for CCRS Sale.csv CORRECTION rows (Operation Update/Delete)
 * generated by customer returns. Per the LCB CCRS FAQ (verbatim): "If a
 * retailer receives a valid return from a customer, the sale identifier should
 * be deleted from CCRS, and the inventory identifier reported on an Inventory
 * Adjustment as a return, with details provided about why it was a return."
 *
 * Upload User Guide (June 2025) facts this module encodes:
 *  • Operation valid values: Insert | Update (alter an existing record
 *    indicated by external identifier) | Delete (delete a record indicated by
 *    external identifier).
 *  • SaleExternalIdentifier + SaleDetailExternalIdentifier are REQUIRED on
 *    Insert, Update AND Delete — corrections must carry the ORIGINAL ids.
 *  • All money is decimal dollars, no $, no parentheses, NO NEGATIVES.
 *  • UpdatedBy/UpdatedDate are filled on corrections; "Updated Date cannot be
 *    prior to Created Date".
 *
 * Semantics used here (documented in docs/RETURNS_DESTRUCTION_COMPLIANCE.md):
 *  • FULL line return  ⇒ Operation = Delete (row restates the original values).
 *  • PARTIAL return    ⇒ Operation = Update (row reports the REMAINING
 *    quantity with taxes recomputed pro-rata from the original line totals).
 *
 * Money is MINOR UNITS (cents) at the boundary and converted to decimal
 * dollars in the emitted rows. PURE — no server-only/DB imports.
 */
import { assembleCcrsFile, ccrsFileName, ccrsDate, CCRS_COLUMNS } from "@/lib/compliance/ccrs-batch-core";

export type SaleCorrectionSource = {
  /** Delete (full-line return) or Update (partial). */
  correctionOperation: "Delete" | "Update";
  /** ORIGINAL identifiers — must match the Insert already filed. */
  saleExternalId: string;
  saleDetailExternalId: string;
  inventoryExternalId: string;
  saleType: string; // RecreationalRetail | RecreationalMedical
  /** Original sale date, ISO or YYYY-MM-DD (Pacific business day). */
  saleDateISO: string;
  /** Original line quantity and the quantity being returned. */
  originalQuantity: number;
  returnQuantity: number;
  /** Original line money, MINOR UNITS (cents). */
  unitPriceMinor: number; // ONE unit, pre-discount/tax
  discountMinor: number; // whole original line
  salesTaxMinor: number; // whole original line
  exciseMinor: number; // whole original line
  /** Date the return was accepted (UpdatedDate), ISO. */
  returnedAtISO: string;
};

export type SaleCorrectionRowResult = { row: string[] | null; skipReason?: string };

function dollars(cents: number): string {
  return (Math.max(0, cents) / 100).toFixed(2);
}

/**
 * MM/DD/YYYY for CCRS. A plain YYYY-MM-DD is treated as ALREADY being the
 * Pacific business day (that is how customer_returns.sale_date is stored) and
 * is reformatted directly — running it through the timezone converter would
 * parse it as UTC midnight and shift it back a day. Full ISO timestamps go
 * through the shared Pacific-day formatter.
 */
export function ccrsDateLoose(v: string): string {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(v.trim());
  if (m) return `${m[2]}/${m[3]}/${m[1]}`;
  return ccrsDate(v);
}

/** Comparable day number (YYYYMMDD) from an MM/DD/YYYY string. */
function dayNumber(mmddyyyy: string): number {
  const [mm, dd, yyyy] = mmddyyyy.split("/");
  return Number(`${yyyy}${mm}${dd}`) || 0;
}

/** Pro-rate a whole-line money amount to a remaining quantity. */
export function prorateLineMinor(lineMinor: number, remainingQty: number, originalQty: number): number {
  if (!(originalQty > 0)) return 0;
  const r = Math.max(0, Math.min(remainingQty, originalQty));
  return Math.round((lineMinor * r) / originalQty);
}

/** Map one customer-return correction to a CCRS Sale.csv row. PURE. */
export function mapSaleCorrectionRow(
  src: SaleCorrectionSource,
  license: { licenseNumber: string; submittedBy: string },
): SaleCorrectionRowResult {
  if (!src.saleExternalId || !src.saleDetailExternalId) {
    return { row: null, skipReason: "missing original sale identifiers (required on Update/Delete)" };
  }
  if (!src.inventoryExternalId) {
    return { row: null, skipReason: "missing InventoryExternalIdentifier (required on Update/Delete)" };
  }
  if (!(src.originalQuantity > 0) || !(src.returnQuantity > 0)) {
    return { row: null, skipReason: "quantities must be positive" };
  }
  if (src.returnQuantity > src.originalQuantity) {
    return { row: null, skipReason: "return quantity exceeds original quantity" };
  }

  const remaining = src.originalQuantity - src.returnQuantity;
  const isDelete = src.correctionOperation === "Delete" || remaining <= 0;
  const qty = isDelete ? src.originalQuantity : remaining;
  const discount = isDelete ? src.discountMinor : prorateLineMinor(src.discountMinor, remaining, src.originalQuantity);
  const salesTax = isDelete ? src.salesTaxMinor : prorateLineMinor(src.salesTaxMinor, remaining, src.originalQuantity);
  const excise = isDelete ? src.exciseMinor : prorateLineMinor(src.exciseMinor, remaining, src.originalQuantity);

  const saleDate = ccrsDateLoose(src.saleDateISO);
  // "Updated Date cannot be prior to Created Date" — clamp forward if needed
  // (compared as Pacific calendar days, the granularity CCRS validates).
  const returnedDate = ccrsDateLoose(src.returnedAtISO);
  const updatedDate = dayNumber(returnedDate) < dayNumber(saleDate) ? saleDate : returnedDate;

  const row = [
    license.licenseNumber, // LicenseNumber
    "", // SoldToLicenseNumber (retail = blank)
    src.inventoryExternalId, // InventoryExternalIdentifier
    "", // PlantExternalIdentifier
    src.saleType, // SaleType (must match the original Insert)
    saleDate, // SaleDate (must match the original Insert)
    String(qty), // Quantity (Delete: original; Update: REMAINING)
    dollars(src.unitPriceMinor), // UnitPrice (unchanged per-unit)
    dollars(discount), // Discount
    dollars(salesTax), // RetailSalesTax
    dollars(excise), // CannabisExciseTax
    src.saleExternalId, // SaleExternalIdentifier (ORIGINAL)
    src.saleDetailExternalId, // SaleDetailExternalIdentifier (ORIGINAL)
    license.submittedBy, // CreatedBy
    saleDate, // CreatedDate (original)
    license.submittedBy, // UpdatedBy (required on corrections)
    updatedDate, // UpdatedDate (>= CreatedDate)
    isDelete ? "Delete" : "Update", // Operation
  ];
  return { row };
}

/** Assemble the correction file (3-row header + Sale columns + rows). */
export function buildSaleCorrectionFile(
  rows: string[][],
  license: { licenseNumber: string; submittedBy: string },
): string {
  return assembleCcrsFile({ type: "Sale", submittedBy: license.submittedBy, rows });
}

export function makeSaleCorrectionFileName(licenseNumber: string): string {
  return ccrsFileName("Sale", licenseNumber);
}

// ---------------------------------------------------------------------------
// Self-tests (tsx/vitest-runnable — PURE module)
// ---------------------------------------------------------------------------

export function __runSaleCorrectionTests(): { passed: number; failed: number } {
  let passed = 0;
  let failed = 0;
  const ok = (cond: boolean, msg: string) => {
    if (cond) passed += 1;
    else {
      failed += 1;
      throw new Error("FAIL: " + msg);
    }
  };
  const eq = (a: unknown, b: unknown, msg: string) =>
    ok(JSON.stringify(a) === JSON.stringify(b), `${msg} (got ${JSON.stringify(a)})`);

  const lic = { licenseNumber: "413541", submittedBy: "Greenway" };
  const base: SaleCorrectionSource = {
    correctionOperation: "Delete",
    saleExternalId: "GW-1001",
    saleDetailExternalId: "GW-1001-abcd1234",
    inventoryExternalId: "LOT-XYZ-001",
    saleType: "RecreationalRetail",
    saleDateISO: "2026-06-01T20:00:00Z",
    originalQuantity: 2,
    returnQuantity: 2,
    unitPriceMinor: 2500,
    discountMinor: 500,
    salesTaxMinor: 420,
    exciseMinor: 1665,
    returnedAtISO: "2026-06-10T20:00:00Z",
  };

  // Full return ⇒ Delete restating original values.
  const del = mapSaleCorrectionRow(base, lic);
  ok(del.row !== null, "delete row produced");
  eq(del.row?.length, CCRS_COLUMNS.Sale.length, "row width matches Sale columns");
  eq(del.row?.[17], "Delete", "Operation Delete");
  eq(del.row?.[6], "2", "Delete restates original quantity");
  eq(del.row?.[7], "25.00", "UnitPrice dollars");
  eq(del.row?.[8], "5.00", "Discount dollars");
  eq(del.row?.[9], "4.20", "RetailSalesTax dollars");
  eq(del.row?.[10], "16.65", "CannabisExciseTax dollars");
  eq(del.row?.[11], "GW-1001", "original SaleExternalIdentifier");
  eq(del.row?.[12], "GW-1001-abcd1234", "original SaleDetailExternalIdentifier");
  eq(del.row?.[15], "Greenway", "UpdatedBy filled");
  eq(del.row?.[16], "06/10/2026", "UpdatedDate = return date");
  eq(del.row?.[14], "06/01/2026", "CreatedDate = original sale date");

  // Partial return ⇒ Update with REMAINING quantity + pro-rata taxes.
  const upd = mapSaleCorrectionRow(
    { ...base, correctionOperation: "Update", returnQuantity: 1 },
    lic,
  );
  eq(upd.row?.[17], "Update", "Operation Update");
  eq(upd.row?.[6], "1", "Update reports remaining quantity");
  eq(upd.row?.[8], "2.50", "discount pro-rated");
  eq(upd.row?.[9], "2.10", "sales tax pro-rated");
  eq(upd.row?.[10], "8.33", "excise pro-rated (rounded)");

  // A "Update" that returns everything degrades safely to Delete.
  const updAll = mapSaleCorrectionRow({ ...base, correctionOperation: "Update" }, lic);
  eq(updAll.row?.[17], "Delete", "full-quantity Update degrades to Delete");

  // UpdatedDate can never precede CreatedDate.
  const early = mapSaleCorrectionRow({ ...base, returnedAtISO: "2026-05-01T00:00:00Z" }, lic);
  eq(early.row?.[16], early.row?.[14], "UpdatedDate clamped to CreatedDate");

  // Guards.
  ok(mapSaleCorrectionRow({ ...base, saleExternalId: "" }, lic).row === null, "missing sale id skipped");
  ok(
    mapSaleCorrectionRow({ ...base, inventoryExternalId: "" }, lic).row === null,
    "missing inventory id skipped",
  );
  ok(
    mapSaleCorrectionRow({ ...base, returnQuantity: 3 }, lic).row === null,
    "over-return skipped",
  );

  // Pro-rata math.
  eq(prorateLineMinor(1000, 1, 2), 500, "half pro-rate");
  eq(prorateLineMinor(999, 1, 3), 333, "thirds rounded");
  eq(prorateLineMinor(1000, 0, 2), 0, "zero remaining ⇒ 0");
  eq(prorateLineMinor(1000, 5, 2), 1000, "remaining clamped to original");

  // File assembly sanity: NumberRecords equals row count, CRLF joined.
  const file = buildSaleCorrectionFile([del.row as string[]], lic);
  ok(file.includes("NumberRecords,1"), "NumberRecords matches");
  ok(file.includes("\r\n"), "CRLF line endings");
  ok(file.split("\r\n")[3]?.startsWith("LicenseNumber,"), "column header present");

  return { passed, failed };
}
