/**
 * medical-intake-core.ts — Task P (pure, dependency-free, self-tested).
 *
 * Date rules and age classification for GUIDED patient intake, grounded in
 * verbatim-scraped sources (see docs/MEDICAL_CANNABIS_COMPLIANCE.md §3):
 *
 * - RCW 69.51A.230(4)(a): recognition cards are valid ONE YEAR from the date
 *   the health care professional issued the AUTHORIZATION for adults (18+),
 *   and SIX MONTHS for minors (<18).
 * - DOH Patient FAQ: "Your recognition card will have the same expiration date
 *   as your medical cannabis authorization form" — the practitioner may
 *   authorize LESS than the maximum, never more.
 * - RCW 69.51A.230(3)(a): the card number (UPID) is "a randomly generated and
 *   unique identifying number" — GENERATED BY THE MCR when the consultant
 *   enters the patient. Staff never invent one; they copy it from the MCR.
 * - RCW 69.51A.220 / DOH FAQ: minors must have a parent/legal-guardian
 *   designated provider; patients 18–20 MUST register to buy at all.
 *
 * PURE: no imports, no Date.now() reads outside injected "today" strings, so
 * every rule is unit-testable.
 */

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

/**
 * True only for a REAL calendar date in `yyyy-mm-dd`.
 *
 * books-69 D-29. The previous implementation was
 * `ISO_DATE.test(s) && !Number.isNaN(Date.parse(`${s}T00:00:00Z`))`, and it
 * accepted `2026-02-30`, `2025-02-29` and `2026-04-31` as valid, because
 * `Date.parse` does not reject an out-of-range day — it silently ROLLS OVER
 * into the following month and returns a perfectly good timestamp. The regex
 * checks the shape and `Date.parse` was trusted to check the calendar, and it
 * does not.
 *
 * That mattered here more than it looks. This predicate guards the recognition
 * card's `effectiveOn` / `expiresOn` / `authorizationIssuedOn`, and RCW
 * 69.51A.230(4)(a) makes those dates legally operative — a card is valid one
 * year from authorization for an adult and six months for a minor. A typed
 * `2026-02-30` passed validation, then `addMonthsClamped` and `ageOn` parsed it
 * with `parseInt`, so the stored expiry was computed from a day that does not
 * exist. Worse for a minor: an impossible birthdate passed straight through
 * `ageOn`, and age is what decides whether a designated provider is required at
 * all.
 *
 * The round-trip through `Date.UTC` is what catches it: build the date from the
 * parts, then check the parts came back unchanged. A rollover changes them.
 * Leap years are handled by construction rather than by a rule — 2024-02-29
 * round-trips and 2025-02-29 does not.
 *
 * Deliberately still dependency-free. `payroll-rate-registry-core` has an
 * identical, correct implementation, but this module's header promises "PURE:
 * no imports" and eleven pure modules in this repository make the same promise.
 * Importing across a domain boundary to save nine lines would trade a real
 * architectural guarantee for a cosmetic one. D-29 records that the class of
 * defect is wider than this instance.
 */
export function isIsoDate(s: string | null | undefined): s is string {
  if (typeof s !== "string" || !ISO_DATE.test(s)) return false;
  const y = Number(s.slice(0, 4));
  const m = Number(s.slice(5, 7));
  const d = Number(s.slice(8, 10));
  if (m < 1 || m > 12 || d < 1 || d > 31) return false;
  const dt = new Date(Date.UTC(y, m - 1, d));
  return dt.getUTCFullYear() === y && dt.getUTCMonth() === m - 1 && dt.getUTCDate() === d;
}

/**
 * Add calendar months to a yyyy-mm-dd date, clamping to the last day of the
 * target month (e.g. 2026-08-31 + 6 months → 2027-02-28, not an invalid date
 * or a rollover into March).
 */
export function addMonthsClamped(ymd: string, months: number): string {
  if (!isIsoDate(ymd)) return ymd;
  const [y, m, d] = ymd.split("-").map((n) => parseInt(n, 10));
  const totalMonths = y * 12 + (m - 1) + months;
  const ty = Math.floor(totalMonths / 12);
  const tm = totalMonths - ty * 12; // 0-based target month
  // Last day of the target month: day 0 of the following month.
  const lastDay = new Date(Date.UTC(ty, tm + 1, 0)).getUTCDate();
  const td = Math.min(d, lastDay);
  const mm = String(tm + 1).padStart(2, "0");
  const dd = String(td).padStart(2, "0");
  return `${ty}-${mm}-${dd}`;
}

/** Whole-year age on `onDate` for a yyyy-mm-dd birthdate. Null when unknown. */
export function ageOn(birthdate: string | null, onDate: string): number | null {
  if (!isIsoDate(birthdate) || !isIsoDate(onDate)) return null;
  const [by, bm, bd] = birthdate.split("-").map((n) => parseInt(n, 10));
  const [oy, om, od] = onDate.split("-").map((n) => parseInt(n, 10));
  let age = oy - by;
  if (om < bm || (om === bm && od < bd)) age -= 1;
  return age;
}

export type PatientAgeClass = "minor" | "adult_18_20" | "adult_21_plus" | "unknown";

/**
 * Classify the patient's age for intake rules:
 * - minor (<18): parent/legal-guardian DP REQUIRED; card max 6 months.
 * - adult_18_20: MUST register (cannot buy anywhere without a card); 1 year.
 * - adult_21_plus: registration voluntary; 1 year.
 */
export function classifyPatientAge(birthdate: string | null, onDate: string): PatientAgeClass {
  const age = ageOn(birthdate, onDate);
  if (age === null) return "unknown";
  if (age < 18) return "minor";
  if (age < 21) return "adult_18_20";
  return "adult_21_plus";
}

/**
 * The LATEST lawful card expiration for an authorization issued on
 * `authorizationIssuedOn`: +6 months for minors, +1 year for adults
 * (RCW 69.51A.230(4)(a)). Returns null when the issue date is missing/invalid.
 */
export function maxExpirationFor(authorizationIssuedOn: string, minor: boolean): string | null {
  if (!isIsoDate(authorizationIssuedOn)) return null;
  return addMonthsClamped(authorizationIssuedOn, minor ? 6 : 12);
}

export type IntakeDatesInput = {
  /** Date the practitioner issued the authorization (from the paper form). */
  authorizationIssuedOn: string | null;
  /** Card effective date (usually today — the day of MCR entry). */
  effectiveOn: string | null;
  /** Card expiration (must MATCH the authorization form's expiration). */
  expiresOn: string | null;
  /** Patient is under 18 (6-month maximum instead of 1 year). */
  minor: boolean;
  /** Today's date (Pacific), injected for purity. */
  today: string;
};

export type IntakeDatesCheck = {
  ok: boolean;
  problems: string[];
  /** The computed statutory maximum expiration, when derivable. */
  maxExpiration: string | null;
};

/**
 * Guardrails for the card dates. Blocks (problems):
 * - missing/invalid dates;
 * - expiration on/before the effective date;
 * - expiration already past;
 * - authorization issue date in the future;
 * - effective date BEFORE the authorization was issued;
 * - expiration LATER than the statutory maximum (auth issue + 6mo/1yr).
 */
export function checkIntakeDates(input: IntakeDatesInput): IntakeDatesCheck {
  const problems: string[] = [];
  const maxExp =
    input.authorizationIssuedOn && isIsoDate(input.authorizationIssuedOn)
      ? maxExpirationFor(input.authorizationIssuedOn, input.minor)
      : null;

  if (!isIsoDate(input.effectiveOn)) problems.push("Enter the card's effective date.");
  if (!isIsoDate(input.expiresOn)) problems.push("Enter the card's expiration date.");
  if (!isIsoDate(input.authorizationIssuedOn)) {
    problems.push("Enter the date the practitioner issued the authorization (on the paper form).");
  }

  if (isIsoDate(input.effectiveOn) && isIsoDate(input.expiresOn)) {
    if (input.expiresOn <= input.effectiveOn) {
      problems.push("Expiration must be after the effective date.");
    }
  }
  if (isIsoDate(input.expiresOn) && isIsoDate(input.today) && input.expiresOn < input.today) {
    problems.push("This card would already be expired — check the authorization form.");
  }
  if (
    isIsoDate(input.authorizationIssuedOn) &&
    isIsoDate(input.today) &&
    input.authorizationIssuedOn > input.today
  ) {
    problems.push("The authorization issue date cannot be in the future.");
  }
  if (
    isIsoDate(input.authorizationIssuedOn) &&
    isIsoDate(input.effectiveOn) &&
    input.effectiveOn < input.authorizationIssuedOn
  ) {
    problems.push("The card cannot take effect before the authorization was issued.");
  }
  if (maxExp && isIsoDate(input.expiresOn) && input.expiresOn > maxExp) {
    problems.push(
      input.minor
        ? `Expiration exceeds the 6-month maximum for a minor (latest lawful date: ${maxExp}; RCW 69.51A.230(4)(a)).`
        : `Expiration exceeds the 1-year maximum (latest lawful date: ${maxExp}; RCW 69.51A.230(4)(a)).`,
    );
  }

  return { ok: problems.length === 0, problems, maxExpiration: maxExp };
}

/**
 * Light shape check for a card number copied from the MCR. We can NOT know the
 * MCR's exact format (it is randomly generated by the database), so this only
 * rejects blatantly wrong entries: blank, whitespace-padded, too short, or
 * containing characters that never appear in an identifier.
 */
export function checkCardNumber(raw: string): { ok: boolean; problem: string | null } {
  const s = raw.trim();
  if (!s) return { ok: false, problem: "Enter the recognition-card number generated by the MCR." };
  if (s.length < 4) {
    return { ok: false, problem: "That looks too short — copy the full card number from the MCR." };
  }
  if (!/^[A-Za-z0-9-]+$/.test(s)) {
    return {
      ok: false,
      problem: "Card numbers contain only letters, digits, and dashes — copy it exactly from the MCR.",
    };
  }
  return { ok: true, problem: null };
}

// ── Self-tests (registered in tests/compliance/pure-selftests.test.ts) ──────

export function __runMedicalIntakeTests(): { passed: number; failed: number } {
  let passed = 0;
  let failed = 0;
  const ok = (cond: boolean, label: string) => {
    if (cond) passed += 1;
    else {
      failed += 1;
      console.error(`medical-intake-core self-test FAILED: ${label}`);
    }
  };

  // isIsoDate — books-69 D-29. Every one of these three returned TRUE before
  // the fix, because Date.parse rolls an out-of-range day into the next month
  // instead of rejecting it. Named individually rather than as one assertion,
  // so a partial regression cannot hide behind a passing test (rule 129).
  ok(!isIsoDate("2026-02-30"), "D-29: February 30th is not a date");
  ok(!isIsoDate("2025-02-29"), "D-29: 2025 is not a leap year");
  ok(!isIsoDate("2026-04-31"), "D-29: April has thirty days");
  ok(isIsoDate("2024-02-29"), "D-29: a real leap day is still accepted");
  ok(isIsoDate("2026-12-31"), "D-29: an ordinary date is still accepted");
  ok(!isIsoDate("2026-13-01"), "D-29: there is no thirteenth month");
  ok(!isIsoDate("2026-7-12"), "D-29: an unpadded month is rejected");

  // addMonthsClamped
  ok(addMonthsClamped("2026-07-12", 12) === "2027-07-12", "+12 months plain");
  ok(addMonthsClamped("2026-08-31", 6) === "2027-02-28", "+6 months clamps to Feb 28");
  ok(addMonthsClamped("2027-08-31", 6) === "2028-02-29", "+6 months clamps to leap Feb 29");
  ok(addMonthsClamped("2026-12-15", 1) === "2027-01-15", "year rollover");

  // ageOn / classifyPatientAge
  ok(ageOn("2000-07-12", "2026-07-12") === 26, "birthday today counts");
  ok(ageOn("2000-07-13", "2026-07-12") === 25, "day before birthday");
  ok(classifyPatientAge("2010-01-01", "2026-07-12") === "minor", "minor");
  ok(classifyPatientAge("2007-01-01", "2026-07-12") === "adult_18_20", "18-20");
  ok(classifyPatientAge("2000-01-01", "2026-07-12") === "adult_21_plus", "21+");
  ok(classifyPatientAge(null, "2026-07-12") === "unknown", "unknown when no DOB");

  // maxExpirationFor
  ok(maxExpirationFor("2026-07-01", false) === "2027-07-01", "adult max = +1yr");
  ok(maxExpirationFor("2026-07-01", true) === "2027-01-01", "minor max = +6mo");
  ok(maxExpirationFor("bogus", false) === null, "invalid issue date -> null");

  // checkIntakeDates — happy path (adult)
  const good = checkIntakeDates({
    authorizationIssuedOn: "2026-07-01",
    effectiveOn: "2026-07-12",
    expiresOn: "2027-07-01",
    minor: false,
    today: "2026-07-12",
  });
  ok(good.ok && good.problems.length === 0, "valid adult dates pass");
  ok(good.maxExpiration === "2027-07-01", "max expiration surfaced");

  // expiration beyond the 1-year maximum
  const tooLong = checkIntakeDates({
    authorizationIssuedOn: "2026-07-01",
    effectiveOn: "2026-07-12",
    expiresOn: "2027-07-02",
    minor: false,
    today: "2026-07-12",
  });
  ok(!tooLong.ok && tooLong.problems.some((p) => p.includes("1-year maximum")), "blocks >1yr");

  // minor: 6-month maximum
  const minorTooLong = checkIntakeDates({
    authorizationIssuedOn: "2026-07-01",
    effectiveOn: "2026-07-12",
    expiresOn: "2027-07-01",
    minor: true,
    today: "2026-07-12",
  });
  ok(
    !minorTooLong.ok && minorTooLong.problems.some((p) => p.includes("6-month maximum")),
    "blocks >6mo for minor",
  );

  // expired / inverted / future-issued / effective-before-issued
  ok(
    !checkIntakeDates({
      authorizationIssuedOn: "2025-01-01",
      effectiveOn: "2025-01-02",
      expiresOn: "2025-06-01",
      minor: false,
      today: "2026-07-12",
    }).ok,
    "blocks already-expired card",
  );
  ok(
    !checkIntakeDates({
      authorizationIssuedOn: "2026-07-01",
      effectiveOn: "2026-07-12",
      expiresOn: "2026-07-12",
      minor: false,
      today: "2026-07-12",
    }).ok,
    "blocks expiration == effective",
  );
  ok(
    !checkIntakeDates({
      authorizationIssuedOn: "2026-08-01",
      effectiveOn: "2026-08-01",
      expiresOn: "2027-08-01",
      minor: false,
      today: "2026-07-12",
    }).ok,
    "blocks future-issued authorization",
  );
  ok(
    !checkIntakeDates({
      authorizationIssuedOn: "2026-07-10",
      effectiveOn: "2026-07-01",
      expiresOn: "2027-07-01",
      minor: false,
      today: "2026-07-12",
    }).ok,
    "blocks effective before authorization issued",
  );
  ok(
    !checkIntakeDates({
      authorizationIssuedOn: null,
      effectiveOn: "2026-07-12",
      expiresOn: "2027-07-01",
      minor: false,
      today: "2026-07-12",
    }).ok,
    "requires authorization issue date",
  );

  // checkCardNumber
  ok(checkCardNumber("  ").ok === false, "blank card number rejected");
  ok(checkCardNumber("abc").ok === false, "too-short card number rejected");
  ok(checkCardNumber("12 34").ok === false, "spaces rejected");
  ok(checkCardNumber("MCR-1234567").ok === true, "plausible card number accepted");

  return { passed, failed };
}
