"use server";

import { revalidatePath } from "next/cache";
import { requirePermission } from "@/lib/auth/session";
import { recordAudit } from "@/lib/auth/audit";
import { redirect } from "next/navigation";
import {
  createAuthorization,
  setAuthorizationStatus,
  recordMcrValidation,
  attachFormScan,
  markCardPrinted,
} from "@/lib/medical/store";
import { upsertMedicalRegistryEntry, removeMedicalRegistryEntry } from "@/lib/medical/sale-store";
import { isDohCategory } from "@/lib/medical/medical-sale-core";
import { checkIntakeDates, checkCardNumber } from "@/lib/medical/medical-intake-core";
import { pacificToday } from "@/lib/reports/timezone";

function bool(form: FormData, key: string): boolean {
  return String(form.get(key) ?? "") === "on" || String(form.get(key) ?? "") === "true";
}

function str(form: FormData, key: string): string {
  return String(form.get(key) ?? "").trim();
}

export async function setCardStatusAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const id = str(form, "authorization_row_id");
  const customerId = str(form, "customer_id");
  const statusRaw = str(form, "status");
  const status = (["active", "expired", "revoked"].includes(statusRaw) ? statusRaw : "revoked") as
    | "active"
    | "expired"
    | "revoked";
  if (!id) return;
  await setAuthorizationStatus(id, status, session.userId);
  await recordAudit({
    actorId: session.userId,
    actorEmail: session.email,
    action: "medical.card.status",
    entityType: "patient_authorization",
    entityId: id,
    after: { status },
  });
  if (customerId) revalidatePath(`/admin/customers/${customerId}`);
}

/**
 * Task P — the GUIDED intake action (replaces the Slice 85 flow at
 * /admin/medical/intake, now retired). One hardened path from
 * /admin/medical: statutory date guardrails (RCW 69.51A.230(4)(a): +1yr
 * adult / +6mo minor from the authorization issue date), MCR card-number
 * shape check, $1 fee confirmation (RCW 69.51A.230(10)), photo-in-MCR
 * confirmation (RCW 69.51A.230(3)(c), waived for compassionate renewals),
 * DOH 608-048 checklist, optional scan upload — then redirects to the wizard
 * with the print step highlighted.
 */
export async function guidedIntakeAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const customerId = str(form, "customer_id");
  const back = (extra: string) =>
    `/admin/medical?${customerId ? `patient=${customerId}&` : ""}${extra}`;
  if (!customerId) redirect("/admin/medical?intake_error=Choose+a+patient+first.");

  const problems: string[] = [];
  const today = pacificToday();

  // Card number — generated by the MCR, copied here. Never invented by staff.
  const upid = str(form, "unique_patient_identifier");
  const upidCheck = checkCardNumber(upid);
  if (!upidCheck.ok && upidCheck.problem) problems.push(upidCheck.problem);

  // Statutory date rules.
  const minor = bool(form, "is_minor");
  const dates = checkIntakeDates({
    authorizationIssuedOn: str(form, "authorization_issued_on") || null,
    effectiveOn: str(form, "effective_on") || null,
    expiresOn: str(form, "expires_on") || null,
    minor,
    today,
  });
  problems.push(...dates.problems);

  // A minor's card must belong to a registered minor patient WITH a
  // parent/guardian designated provider (RCW 69.51A.220). We can only warn in
  // data (the DP is a separate card) — but the consultant must confirm it.
  if (minor && !bool(form, "chk_minor_dp")) {
    problems.push(
      "A minor patient requires a parent/legal-guardian designated provider (RCW 69.51A.220) — confirm the DP is registered too.",
    );
  }

  // Only a DOH-Certified Medical Cannabis Consultant may enter patients into
  // the MCR and create cards (DOH MCR roles). Budtenders may only VERIFY.
  if (!bool(form, "chk_consultant")) {
    problems.push(
      "Only a DOH-Certified Medical Cannabis Consultant may register patients — confirm you hold a current certification.",
    );
  }

  // RCW 69.51A.230(10): the retailer SHALL collect the minimum $1 fee at
  // registration time. Hard requirement.
  if (!bool(form, "card_fee_collected")) {
    problems.push("Collect the $1 recognition-card fee (RCW 69.51A.230(10)) and check the box.");
  }

  // RCW 69.51A.230(3)(c): photo taken by store staff and uploaded INTO the
  // MCR — waived only for compassionate-care renewals (RCW 69.51A.230(4)(b)).
  const compassionate = bool(form, "compassionate_renewal");
  if (!compassionate && !bool(form, "photo_uploaded_to_mcr")) {
    problems.push(
      "Take the patient photo and upload it in the MCR (RCW 69.51A.230(3)(c)), then check the box — or mark this a compassionate-care renewal.",
    );
  }

  if (problems.length > 0) {
    redirect(back(`intake_error=${encodeURIComponent(problems.join(" "))}`));
  }

  const checklist = {
    formCompleteSigned: bool(form, "chk_form"),
    tamperResistantVerified: bool(form, "chk_tamper"),
    identityVerified: bool(form, "chk_identity"),
    embossedSealVerified: bool(form, "chk_seal"),
  };

  const res = await createAuthorization(
    {
      customerId,
      authorizationId: str(form, "authorization_id") || null,
      uniquePatientIdentifier: upid || null,
      holderType:
        str(form, "holder_type") === "designated_provider" ? "designated_provider" : "patient",
      effectiveOn: str(form, "effective_on") || null,
      expiresOn: str(form, "expires_on") || null,
      inDohDatabase: bool(form, "in_doh_database"),
      checklist,
      notes: str(form, "notes") || null,
      authorizationIssuedOn: str(form, "authorization_issued_on") || null,
      cardFeeCollected: true,
      photoUploadedToMcr: compassionate ? false : true,
      compassionateRenewal: compassionate,
    },
    session.userId,
  );

  if (!res.ok) {
    redirect(back(`intake_error=${encodeURIComponent(res.error)}`));
  }

  // Optional scanned form (from the Canon PIXMA TS3522 flatbed).
  let scanError: string | null = null;
  const file = form.get("form_scan");
  if (file instanceof File && file.size > 0) {
    const bytes = await file.arrayBuffer();
    const up = await attachFormScan(
      res.id,
      { bytes, filename: file.name, contentType: file.type },
      session.userId,
    );
    if (!up.ok) scanError = up.error;
  }

  await recordAudit({
    actorId: session.userId,
    actorEmail: session.email,
    action: "medical.card.issue",
    entityType: "patient_authorization",
    entityId: res.id,
    after: {
      customer_id: customerId,
      unique_patient_identifier: upid,
      minor,
      compassionate_renewal: compassionate,
    },
  });
  revalidatePath("/admin/medical");
  redirect(
    back(`intake_ok=${res.id}${scanError ? `&scan_error=${encodeURIComponent(scanError)}` : ""}`),
  );
}


/** Attach a scanned form to an EXISTING authorization row. */
export async function attachScanAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const id = str(form, "authorization_row_id");
  if (!id) return;
  const file = form.get("form_scan");
  if (file instanceof File && file.size > 0) {
    const bytes = await file.arrayBuffer();
    await attachFormScan(id, { bytes, filename: file.name, contentType: file.type }, session.userId);
    await recordAudit({
      actorId: session.userId,
      actorEmail: session.email,
      action: "medical.card.scan_attached",
      entityType: "patient_authorization",
      entityId: id,
    });
  }
  revalidatePath("/admin/medical");
}

/** Stamp that the physical recognition card was printed (before laminating). */
export async function markCardPrintedAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const id = str(form, "authorization_row_id");
  if (!id) return;
  await markCardPrinted(id, session.userId);
  revalidatePath("/admin/medical");
}

export async function validateMcrAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const id = str(form, "authorization_row_id");
  const customerId = str(form, "customer_id");
  if (!id) return;
  await recordMcrValidation(id, session.userId);
  await recordAudit({
    actorId: session.userId,
    actorEmail: session.email,
    action: "medical.card.mcr_validated",
    entityType: "patient_authorization",
    entityId: id,
  });
  if (customerId) revalidatePath(`/admin/customers/${customerId}`);
}

// ---------------------------------------------------------------------------
// Task O — DOH product registry (durable 246-70 categories per POS product)
// ---------------------------------------------------------------------------
/**
 * Register (or re-verify) a product's DOH 246-70 category. The category MUST
 * be read from the DOH logo on the PHYSICAL PACKAGE — any name-based hint in
 * the UI is a suggestion only. Upsert keyed by the stable POS product key.
 */
export async function upsertDohProductAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const key = str(form, "pos_product_key");
  const categoryRaw = str(form, "doh_category");
  if (!key || !isDohCategory(categoryRaw)) {
    redirect(`/admin/medical?reg_error=${encodeURIComponent("Pick a product and a DOH category.")}`);
  }

  const res = await upsertMedicalRegistryEntry(
    {
      posProductKey: key,
      productName: str(form, "product_name") || null,
      dohCategory: categoryRaw,
      notes: str(form, "notes") || null,
    },
    session.userId,
  );

  if (res.ok) {
    await recordAudit({
      actorId: session.userId,
      actorEmail: session.email,
      action: "medical.doh_product.verified",
      entityType: "medical_product_registry",
      entityId: res.id,
      after: { pos_product_key: key, doh_category: categoryRaw },
    });
    revalidatePath("/admin/medical");
  } else {
    redirect(`/admin/medical?reg_error=${encodeURIComponent(res.error)}`);
  }
}

/** Remove a registry entry (e.g. mis-verified). Future sales lose the exemption. */
export async function removeDohProductAction(form: FormData): Promise<void> {
  const session = await requirePermission("medical.manage");
  const id = str(form, "registry_id");
  if (!id) return;
  const res = await removeMedicalRegistryEntry(id);
  if (res.ok) {
    await recordAudit({
      actorId: session.userId,
      actorEmail: session.email,
      action: "medical.doh_product.removed",
      entityType: "medical_product_registry",
      entityId: id,
    });
  }
  revalidatePath("/admin/medical");
}
