import Link from "next/link";
import { requirePermission } from "@/lib/auth/session";
import { isSupabaseServiceConfigured } from "@/lib/supabase/env";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { Breadcrumbs, HelpPanel, EmptyState } from "@/components/admin/ux";
import { StatCard } from "@/components/admin/StatCard";
import { Badge } from "@/components/admin/ui";
import { getEndorsementConfig, medicalSummary, listExemptSales, listRecentAuthorizations } from "@/lib/medical/store";
import { DohProductRegistry } from "@/components/admin/medical/DohProductRegistry";
import { GuidedIntakeWizard } from "@/components/admin/medical/GuidedIntakeWizard";

export const dynamic = "force-dynamic";

function money(minor: number): string {
  return `$${(minor / 100).toFixed(2)}`;
}

export default async function MedicalOverviewPage({
  searchParams,
}: {
  searchParams?: Promise<{
    prodq?: string;
    reg_error?: string;
    patq?: string;
    patient?: string;
    intake_error?: string;
    intake_ok?: string;
    scan_error?: string;
  }>;
}) {
  await requirePermission("medical.manage");
  const sp = searchParams ? await searchParams : {};
  const productQuery = typeof sp.prodq === "string" ? sp.prodq : "";
  const registryError = typeof sp.reg_error === "string" ? sp.reg_error : null;
  const patientQuery = typeof sp.patq === "string" ? sp.patq : "";
  const patientId = typeof sp.patient === "string" ? sp.patient : "";
  const intakeError = typeof sp.intake_error === "string" ? sp.intake_error : null;
  const intakeOk = typeof sp.intake_ok === "string" ? sp.intake_ok : null;
  const scanError = typeof sp.scan_error === "string" ? sp.scan_error : null;

  if (!isSupabaseServiceConfigured) {
    return (
      <div className="space-y-6">
        <Breadcrumbs items={[{ label: "Operations" }, { label: "Medical" }]} />
        <AdminPageHeader title="Medical cannabis" subtitle="Recognition cards & DOH compliance." />
        <EmptyState title="Supabase not configured" description="Connect the service role key to manage medical." />
      </div>
    );
  }

  const [config, summary, exempt, recent] = await Promise.all([
    getEndorsementConfig(),
    medicalSummary(),
    listExemptSales({ limit: 50 }),
    listRecentAuthorizations(15),
  ]);

  return (
    <div className="space-y-6">
      <Breadcrumbs items={[{ label: "Operations" }, { label: "Medical" }]} />
      <AdminPageHeader
        title="Medical cannabis"
        subtitle="Recognition cards, DOH database (MCR) status, and excise-exempt sale records."
        action={
          <Link
            href="#intake"
            className="inline-flex items-center gap-2 rounded-[var(--admin-radius)] bg-[var(--admin-accent)] px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90"
          >
            📇 Start guided intake
          </Link>
        }
        help={
          <HelpPanel
            id="medical-overview"
            title="How medical compliance works"
            steps={[
              "New patient? Use the Guided intake below — it walks you through the paper form, the MCR, the $1 fee, the photo, and print & laminate, and blocks anything unlawful.",
              "The card number is GENERATED BY THE MCR when the consultant enters the patient — you copy it here, never invent one. Adults: 1-year max; minors: 6-month max (RCW 69.51A.230(4)).",
              "Register DOH-compliant products (chapter 246-70 WAC) below — only registered products qualify for exemptions.",
              "Attach the patient's card on the order; both exemptions (9.3% sales + 37% excise) apply ONLY to DOH-compliant products (RCW 82.08.9998; WAC 314-55-090). High-CBD products are sales-tax-free for anyone.",
              "High-THC products sell ONLY to valid cardholders — the completion gate blocks this with no override.",
            ]}
          >
            <p>
              Every excise-exempt line is recorded with the unique patient identifier, card dates, SKU, and price,
              and retained five years per WAC 314-55-090(2). See the project doc for full source citations.
            </p>
          </HelpPanel>
        }
      />

      {/* Endorsement status */}
      <section className="rounded-[var(--admin-radius-lg)] border border-[var(--admin-border)] bg-[var(--admin-surface)] p-5">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <h2 className="text-sm font-semibold text-white">Store medical endorsement</h2>
          {config?.isMedicallyEndorsed ? (
            <Badge tone="green">Endorsed</Badge>
          ) : (
            <Badge tone="danger">Not endorsed — exemptions disabled</Badge>
          )}
        </div>
        <p className="mt-2 text-xs text-white/50">
          {config?.endorsementNumber ? `Endorsement ${config.endorsementNumber}. ` : ""}
          37% excise exemption effective through {config?.exciseExemptionUntil ?? "2029-06-30"} (WAC
          314-55-090(6)).
        </p>
      </section>

      <div className="grid gap-4 sm:grid-cols-3">
        <StatCard label="Medical patients" value={summary.patients.toLocaleString("en-US")} accent="gold" />
        <StatCard label="Active cards" value={summary.activeCards.toLocaleString("en-US")} accent="green" />
        <StatCard
          label="Excise exempted (recorded)"
          value={money(summary.exciseExemptedMinor)}
          hint="Lifetime"
          accent="muted"
        />
      </div>

      {/* Task P — guided patient intake (single hardened path) */}
      <GuidedIntakeWizard
        patientQuery={patientQuery}
        patientId={patientId}
        errorMessage={intakeError}
        issuedId={intakeOk}
        scanError={scanError}
      />

      {/* Recent recognition cards — the working queue with print status */}
      <section className="rounded-[var(--admin-radius-lg)] border border-[var(--admin-border)] bg-[var(--admin-surface)] p-5">
        <h2 className="mb-3 text-sm font-semibold text-white">Recent recognition cards</h2>
        {recent.length === 0 ? (
          <p className="text-sm text-white/50">No recognition cards yet.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[820px] text-sm">
              <thead>
                <tr className="border-b border-[var(--admin-border)] text-left text-xs uppercase tracking-wide text-white/40">
                  <th className="px-3 py-2 font-medium">Patient</th>
                  <th className="px-3 py-2 font-medium">Card #</th>
                  <th className="px-3 py-2 font-medium">Dates</th>
                  <th className="px-3 py-2 font-medium">MCR</th>
                  <th className="px-3 py-2 font-medium">Scan</th>
                  <th className="px-3 py-2 font-medium">Printed</th>
                  <th className="px-3 py-2 font-medium" />
                </tr>
              </thead>
              <tbody>
                {recent.map((r) => (
                  <tr key={r.id} className="border-b border-[var(--admin-border)]/50 last:border-0">
                    <td className="px-3 py-2 text-white/70">
                      <Link href={`/admin/customers/${r.customer_id}`} className="underline-offset-2 hover:underline">
                        {r.customer_name ?? "—"}
                      </Link>
                    </td>
                    <td className="px-3 py-2 font-mono text-xs text-white/70">
                      {r.unique_patient_identifier ?? "—"}
                    </td>
                    <td className="px-3 py-2 text-xs text-white/50">
                      {r.effective_on ?? "—"} → {r.expires_on ?? "—"}
                    </td>
                    <td className="px-3 py-2">
                      {r.in_doh_database ? <Badge tone="green">In MCR</Badge> : <Badge tone="orange">Not yet</Badge>}
                    </td>
                    <td className="px-3 py-2">
                      {r.form_scan_path ? <Badge tone="green">Scanned</Badge> : <Badge tone="orange">Missing</Badge>}
                    </td>
                    <td className="px-3 py-2">
                      {r.card_printed_at ? (
                        <Badge tone="green">Printed</Badge>
                      ) : (
                        <Badge tone="gold">To print</Badge>
                      )}
                    </td>
                    <td className="px-3 py-2 text-right">
                      <Link
                        href={`/admin/medical/card/${r.id}`}
                        target="_blank"
                        className="text-xs font-semibold text-[var(--admin-accent)] underline"
                      >
                        🖨 Print
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      {/* Task O — DOH product registry (chapter 246-70 WAC) */}
      <DohProductRegistry productQuery={productQuery} errorMessage={registryError} />

      {/* Excise-exempt sale records (WAC 314-55-090(2)) */}
      <section className="rounded-[var(--admin-radius-lg)] border border-[var(--admin-border)] bg-[var(--admin-surface)] p-5">
        <h2 className="mb-3 text-sm font-semibold text-white">
          Excise-exempt sale records <span className="text-xs font-normal text-white/40">· WAC 314-55-090(2)</span>
        </h2>
        {exempt.length === 0 ? (
          <p className="text-sm text-white/50">No excise-exempt sales recorded yet.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[720px] text-sm">
              <thead>
                <tr className="border-b border-[var(--admin-border)] text-left text-xs uppercase tracking-wide text-white/40">
                  <th className="px-3 py-2 font-medium">Date</th>
                  <th className="px-3 py-2 font-medium">UPID</th>
                  <th className="px-3 py-2 font-medium">Card dates</th>
                  <th className="px-3 py-2 font-medium">SKU</th>
                  <th className="px-3 py-2 text-right font-medium">Price</th>
                  <th className="px-3 py-2 text-right font-medium">Excise exempted</th>
                </tr>
              </thead>
              <tbody>
                {exempt.map((r) => (
                  <tr key={r.id} className="border-b border-[var(--admin-border)]/50 last:border-0">
                    <td className="px-3 py-2 text-white/70">{r.sale_date}</td>
                    <td className="px-3 py-2 font-mono text-xs text-white/70">{r.unique_patient_identifier}</td>
                    <td className="px-3 py-2 text-xs text-white/50">
                      {r.card_effective_on ?? "—"} → {r.card_expires_on ?? "—"}
                    </td>
                    <td className="px-3 py-2 text-white/70">{r.product_sku}</td>
                    <td className="px-3 py-2 text-right tabular-nums text-white/70">{money(r.sales_price_minor)}</td>
                    <td className="px-3 py-2 text-right tabular-nums text-[var(--admin-green)]">
                      {money(r.excise_amount_exempt_minor)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
