/**
 * scripts/pos/preflight-ios-build.ts  (SLICE 9)
 *
 * Runs BEFORE the iPad bundle is built (`npm run register:build:ios`) and
 * refuses to continue if the app would be dead on arrival.
 *
 * WHY A PREFLIGHT AT ALL
 * The failures this guards against share one nasty property: the build still
 * SUCCEEDS. Vite emits a bundle, Xcode archives it, the app installs, the
 * Greenway logo appears — and then nothing works, because the app has no idea
 * what server to call, or because Apple was told the app needs a 32-bit CPU
 * that no iPad has had since 2014. Every one of those is a wasted evening for
 * Michael, and the last one cannot be fully undone after the first upload
 * (Apple only lets device requirements be RELAXED, never added).
 *
 * So: one second of checking here, on the Mac, with a plain-English
 * explanation, instead of a mystery at the counter.
 *
 * All judgement lives in the PURE core (src/lib/pos/ios-build-config-core.ts).
 * This file only does the I/O the core is forbidden to do: read the process
 * environment, read Info.plist off disk, print, and set the exit code.
 */

import { readFileSync } from "node:fs";
import path from "node:path";

import {
  API_BASE_ENV_VAR,
  auditRequiredDeviceCapabilities,
  describeApiBaseForBuild,
  describeEncryptionDeclaration,
  type EncryptionDeclaration,
} from "../../src/lib/pos/ios-build-config-core";
import { auditStarPlist, STAR_EA_PROTOCOL } from "../../src/lib/pos/star-printer-core";

const repoRoot = path.resolve(__dirname, "..", "..");
const INFO_PLIST = path.join(repoRoot, "ios", "App", "App", "Info.plist");
const PBXPROJ = path.join(repoRoot, "ios", "App", "App.xcodeproj", "project.pbxproj");
const STORYBOARD = path.join(repoRoot, "ios", "App", "App", "Base.lproj", "Main.storyboard");
const SCENE_DELEGATE = path.join(repoRoot, "ios", "App", "App", "SceneDelegate.swift");

/**
 * Read `UIRequiredDeviceCapabilities` out of Info.plist.
 *
 * Deliberately a small regex reader rather than a plist library: this script
 * must run on a stock Mac with nothing but the repo installed, and adding a
 * native plist dependency to make ONE array readable would be a poor trade.
 * The shape of the file is fixed (Capacitor generates it, we edit two keys),
 * and if the shape ever changes this returns null and the preflight FAILS
 * loudly rather than passing by accident.
 */
function readRequiredCapabilities(xml: string): string[] | null {
  const block = xml.match(
    /<key>UIRequiredDeviceCapabilities<\/key>\s*<array>([\s\S]*?)<\/array>/,
  );
  if (!block) return null;
  return [...block[1].matchAll(/<string>([^<]*)<\/string>/g)].map((m) => m[1].trim());
}

/**
 * Read `UISupportedExternalAccessoryProtocols`.
 *
 * Returns null when the key is absent, which is a DIFFERENT and worse state
 * than an empty array, so the two are not collapsed.
 */
function readAccessoryProtocols(xml: string): string[] | null {
  const block = xml.match(
    /<key>UISupportedExternalAccessoryProtocols<\/key>\s*<array>([\s\S]*?)<\/array>/,
  );
  if (!block) return null;
  return [...block[1].matchAll(/<string>([^<]*)<\/string>/g)].map((m) => m[1].trim());
}

/** Read `NSBluetoothAlwaysUsageDescription`, or null when absent. */
function readBluetoothUsage(xml: string): string | null {
  const m = xml.match(
    /<key>NSBluetoothAlwaysUsageDescription<\/key>\s*<string>([^<]*)<\/string>/,
  );
  return m ? m[1] : null;
}

/** Read the export-compliance answer, distinguishing "false" from "absent". */
function readEncryptionDeclaration(xml: string): EncryptionDeclaration {
  const m = xml.match(
    /<key>ITSAppUsesNonExemptEncryption<\/key>\s*<(true|false)\s*\/>/,
  );
  if (!m) return { declared: false, value: null };
  return { declared: true, value: m[1] === "true" };
}

function main(): void {
  const problems: string[] = [];

  console.log("Greenway register — iPad build preflight");
  console.log("────────────────────────────────────────");

  // ── 1. the server address ────────────────────────────────────────────────
  const verdict = describeApiBaseForBuild(process.env[API_BASE_ENV_VAR], "native");
  if (verdict.ok) {
    console.log(`  OK   server address: ${verdict.message}`);
  } else {
    console.log(`  FAIL server address`);
    problems.push(verdict.message);
  }

  // ── 2 & 3. what Info.plist actually says ─────────────────────────────────
  let xml: string;
  try {
    xml = readFileSync(INFO_PLIST, "utf8");
  } catch {
    console.error(`  FAIL cannot read ${INFO_PLIST}`);
    process.exit(1);
    return;
  }

  const caps = readRequiredCapabilities(xml);
  if (caps === null) {
    console.log("  FAIL device requirements");
    problems.push(
      "UIRequiredDeviceCapabilities could not be found in Info.plist. The file " +
        "may have been regenerated by `npx cap add ios`, which would also have " +
        "restored Capacitor's placeholder values.",
    );
  } else {
    const capProblems = auditRequiredDeviceCapabilities(caps);
    if (capProblems.length === 0) {
      console.log(`  OK   device requirements: [${caps.join(", ")}]`);
    } else {
      console.log(`  FAIL device requirements: [${caps.join(", ")}]`);
      for (const p of capProblems) problems.push(p.detail);
    }
  }

  const encryption = readEncryptionDeclaration(xml);
  const encryptionText = describeEncryptionDeclaration(encryption);
  if (encryption.declared && encryption.value === false) {
    console.log("  OK   export compliance: declared, no non-exempt encryption");
  } else {
    console.log("  FAIL export compliance");
    problems.push(encryptionText);
  }

  // ── 4. can the app reach the counter printer at all? ──────────────────────
  const plistProblems = auditStarPlist({
    externalAccessoryProtocols: readAccessoryProtocols(xml),
    bluetoothUsageDescription: readBluetoothUsage(xml),
  });
  if (plistProblems.length === 0) {
    console.log(`  OK   receipt printer: ${STAR_EA_PROTOCOL} declared, Bluetooth explained`);
  } else {
    console.log("  FAIL receipt printer");
    for (const p of plistProblems) problems.push(p.detail);
  }

  // ── 5. is the printer plugin actually going to be COMPILED? ──────────────
  // Xcode compiles target MEMBERS, not folder contents. StarPrinterPlugin.swift
  // sat in ios/App/App/ for two whole slices without ever being in the Sources
  // build phase: never compiled, never registered with the Capacitor bridge, so
  // the register kept reporting "no native printer" on a perfectly healthy
  // build. `cap sync` CANNOT fix that - the CLI only scans installed npm plugin
  // packages, never app-local Swift files. So it is verified here instead.
  try {
    const pbx = readFileSync(PBXPROJ, "utf8");
    const sources = pbx.match(
      /Begin PBXSourcesBuildPhase section \*\/([\s\S]*?)\/\* End PBXSourcesBuildPhase section/,
    );
    if (!sources) {
      console.log("  FAIL printer plugin");
      problems.push(
        "Could not find the Sources build phase in project.pbxproj, so I cannot " +
          "confirm StarPrinterPlugin.swift will be compiled.",
      );
    } else if (!sources[1].includes("StarPrinterPlugin.swift in Sources")) {
      console.log("  FAIL printer plugin");
      problems.push(
        "StarPrinterPlugin.swift is NOT a member of the App target, so Xcode will " +
          "not compile it. The app will install and run, but the register will " +
          'report "Printer setup is only available on the iPad", print nothing, ' +
          "and never open the cash drawer.\n" +
          "This almost always means a `git pull` was ABORTED. Run `git status`: if " +
          "ios/App/App.xcodeproj/project.pbxproj is listed as modified, your copy " +
          "is missing the fix. See the troubleshooting section titled " +
          '"the git pull that did not happen" in the SLICE 10 document.',
      );
    } else {
      console.log("  OK   printer plugin: StarPrinterPlugin.swift is in Compile Sources");
    }

    // ── 6. is the plugin actually REGISTERED with the bridge? ──────────────
    // Compiling the plugin is necessary but NOT sufficient, which cost us
    // three rounds of Michael's evenings. Capacitor does not discover plugins
    // by scanning the binary: CapacitorBridge.registerPlugins() only registers
    // five hard-coded core plugins plus the class NAMES listed in
    // capacitor.config.json's packageClassList. That list is generated by
    // @capacitor/cli (dist/util/iosplugin.js), whose getPluginFiles() iterates
    // INSTALLED NPM PLUGIN PACKAGES only. ios/App/App is not an npm package,
    // so our app-local plugin can never appear there. The only way it reaches
    // the bridge is an explicit registerPluginInstance call, which lives in
    // GreenwayBridgeViewController. If that file is not compiled, or the app
    // no longer uses it as the root view controller, the register goes back to
    // "Printer setup is only available on the iPad" with a perfectly green
    // build. So both halves are checked.
    if (!sources || !sources[1].includes("GreenwayBridgeViewController.swift in Sources")) {
      console.log("  FAIL plugin registration");
      problems.push(
        "GreenwayBridgeViewController.swift is not in the App target's Compile " +
          "Sources. That file is the ONLY thing that registers the Star printer " +
          "plugin with the Capacitor bridge — Capacitor cannot discover an " +
          "app-local plugin by itself. Without it the app builds and runs, but " +
          'the register reports "Printer setup is only available on the iPad", ' +
          "prints nothing, and never opens the cash drawer.",
      );
    } else {
      const storyboard = readFileSync(STORYBOARD, "utf8");
      const sceneDelegate = readFileSync(SCENE_DELEGATE, "utf8");
      const inStoryboard = storyboard.includes(
        'customClass="GreenwayBridgeViewController"',
      );
      const inScene = sceneDelegate.includes("GreenwayBridgeViewController()");
      if (!inStoryboard || !inScene) {
        console.log("  FAIL plugin registration");
        problems.push(
          "GreenwayBridgeViewController is compiled, but the app does not use it " +
            `as its root view controller (Main.storyboard: ${inStoryboard ? "ok" : "MISSING"}, ` +
            `SceneDelegate.swift: ${inScene ? "ok" : "MISSING"}). Both must name it ` +
            "instead of Capacitor's stock CAPBridgeViewController, or the Star " +
            "printer plugin is never registered and the printer silently " +
            "disappears from the register. This is usually caused by re-running " +
            "`npx cap add ios`, which restores Capacitor's template files.",
        );
      } else {
        console.log(
          "  OK   plugin registration: GreenwayBridgeViewController registers StarPrinter",
        );
      }
    }
  } catch {
    console.log("  FAIL printer plugin");
    problems.push(`Cannot read ${PBXPROJ}.`);
  }

  // ── verdict ──────────────────────────────────────────────────────────────
  console.log("");
  if (problems.length === 0) {
    console.log("All preflight checks passed. Building the iPad bundle…");
    return;
  }

  console.error(
    `Build stopped: ${problems.length} problem${problems.length === 1 ? "" : "s"} ` +
      "would have produced an app that installs but does not work.\n",
  );
  problems.forEach((p, i) => console.error(`${i + 1}. ${p}\n`));
  process.exit(1);
}

main();
