/**
 * scripts/pos/preflight-ios-build.ts  (SLICE 9)
 *
 * Runs BEFORE the iPad bundle is built (`npm run register:build:ios`) and
 * refuses to continue if the app would be dead on arrival.
 *
 * WHY A PREFLIGHT AT ALL
 * The failures this guards against share one nasty property: the build still
 * SUCCEEDS. Vite emits a bundle, Xcode archives it, the app installs, the
 * Greenway logo appears — and then nothing works, because the app has no idea
 * what server to call, or because Apple was told the app needs a 32-bit CPU
 * that no iPad has had since 2014. Every one of those is a wasted evening for
 * Michael, and the last one cannot be fully undone after the first upload
 * (Apple only lets device requirements be RELAXED, never added).
 *
 * So: one second of checking here, on the Mac, with a plain-English
 * explanation, instead of a mystery at the counter.
 *
 * All judgement lives in the PURE core (src/lib/pos/ios-build-config-core.ts).
 * This file only does the I/O the core is forbidden to do: read the process
 * environment, read Info.plist off disk, print, and set the exit code.
 */

import { readFileSync } from "node:fs";
import path from "node:path";

import {
  API_BASE_ENV_VAR,
  auditRequiredDeviceCapabilities,
  describeApiBaseForBuild,
  describeEncryptionDeclaration,
  type EncryptionDeclaration,
} from "../../src/lib/pos/ios-build-config-core";

const repoRoot = path.resolve(__dirname, "..", "..");
const INFO_PLIST = path.join(repoRoot, "ios", "App", "App", "Info.plist");

/**
 * Read `UIRequiredDeviceCapabilities` out of Info.plist.
 *
 * Deliberately a small regex reader rather than a plist library: this script
 * must run on a stock Mac with nothing but the repo installed, and adding a
 * native plist dependency to make ONE array readable would be a poor trade.
 * The shape of the file is fixed (Capacitor generates it, we edit two keys),
 * and if the shape ever changes this returns null and the preflight FAILS
 * loudly rather than passing by accident.
 */
function readRequiredCapabilities(xml: string): string[] | null {
  const block = xml.match(
    /<key>UIRequiredDeviceCapabilities<\/key>\s*<array>([\s\S]*?)<\/array>/,
  );
  if (!block) return null;
  return [...block[1].matchAll(/<string>([^<]*)<\/string>/g)].map((m) => m[1].trim());
}

/** Read the export-compliance answer, distinguishing "false" from "absent". */
function readEncryptionDeclaration(xml: string): EncryptionDeclaration {
  const m = xml.match(
    /<key>ITSAppUsesNonExemptEncryption<\/key>\s*<(true|false)\s*\/>/,
  );
  if (!m) return { declared: false, value: null };
  return { declared: true, value: m[1] === "true" };
}

function main(): void {
  const problems: string[] = [];

  console.log("Greenway register — iPad build preflight");
  console.log("────────────────────────────────────────");

  // ── 1. the server address ────────────────────────────────────────────────
  const verdict = describeApiBaseForBuild(process.env[API_BASE_ENV_VAR], "native");
  if (verdict.ok) {
    console.log(`  OK   server address: ${verdict.message}`);
  } else {
    console.log(`  FAIL server address`);
    problems.push(verdict.message);
  }

  // ── 2 & 3. what Info.plist actually says ─────────────────────────────────
  let xml: string;
  try {
    xml = readFileSync(INFO_PLIST, "utf8");
  } catch {
    console.error(`  FAIL cannot read ${INFO_PLIST}`);
    process.exit(1);
    return;
  }

  const caps = readRequiredCapabilities(xml);
  if (caps === null) {
    console.log("  FAIL device requirements");
    problems.push(
      "UIRequiredDeviceCapabilities could not be found in Info.plist. The file " +
        "may have been regenerated by `npx cap add ios`, which would also have " +
        "restored Capacitor's placeholder values.",
    );
  } else {
    const capProblems = auditRequiredDeviceCapabilities(caps);
    if (capProblems.length === 0) {
      console.log(`  OK   device requirements: [${caps.join(", ")}]`);
    } else {
      console.log(`  FAIL device requirements: [${caps.join(", ")}]`);
      for (const p of capProblems) problems.push(p.detail);
    }
  }

  const encryption = readEncryptionDeclaration(xml);
  const encryptionText = describeEncryptionDeclaration(encryption);
  if (encryption.declared && encryption.value === false) {
    console.log("  OK   export compliance: declared, no non-exempt encryption");
  } else {
    console.log("  FAIL export compliance");
    problems.push(encryptionText);
  }

  // ── verdict ──────────────────────────────────────────────────────────────
  console.log("");
  if (problems.length === 0) {
    console.log("All preflight checks passed. Building the iPad bundle…");
    return;
  }

  console.error(
    `Build stopped: ${problems.length} problem${problems.length === 1 ? "" : "s"} ` +
      "would have produced an app that installs but does not work.\n",
  );
  problems.forEach((p, i) => console.error(`${i + 1}. ${p}\n`));
  process.exit(1);
}

main();
