#!/usr/bin/env python3
"""
scripts/recon/atm-custody-measure.py  (books-75)

Measure the ATM CASH CIRCUIT from Michael's real exports, because his books-75
answer describes a custody relationship and the accounting turns on whether the
settlement money is the ATM's REVENUE or Greenway's CASH in the ATM's hands.

Michael, verbatim (books-75):
  "The atm has its own bank account, it's 6228. Its only purpose is to accept
   deposits from the atm. Right now I just transfer the deposited money from
   6228 to 6048, because vendors and payroll are paid through that account.
   Cash generated by the sales of cannabis go back into the physical atm. So I
   suppose what we could say is the money is simply in the atm businesses
   custody. I usually transfer the fees to the cannabis account too, but going
   forward we can leave the atm fees in the atm account because that revenue
   belongs to the atm."

Nothing is assumed here. Every number printed is summed from a file on disk.
"""
import csv
import io
import os

WS = "/workspace"


def money(s):
    """'$6,160.00' / '11427.50' / '' -> cents int. Refuses silently-bad input."""
    if s is None:
        return None
    t = str(s).strip().replace("$", "").replace(",", "").replace('"', "")
    if t in ("", "-"):
        return None
    neg = t.startswith("(") and t.endswith(")")
    if neg:
        t = t[1:-1]
    if t.startswith("-"):
        neg = True
        t = t[1:]
    try:
        cents = int(round(float(t) * 100))
    except ValueError:
        return None
    return -cents if neg else cents


def fmt(cents):
    return f"${cents/100:,.2f}"


def rows(name):
    p = os.path.join(WS, name)
    if not os.path.exists(p):
        print(f"  !! MISSING {name}")
        return []
    with io.open(p, encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


print("=" * 74)
print("1) FUNDS MOVEMENT  --  what the ATM network actually deposits into 6228")
print("=" * 74)
fm = rows("Funds Movement By Account By Day 5.1.26-8.23.26.csv")
by_type = {}
accts = {}
bad = 0
for r in fm:
    st = (r.get("Settlement Type") or "").strip()
    c = money(r.get("Amount"))
    if c is None:
        bad += 1
        continue
    by_type.setdefault(st, [0, 0])
    by_type[st][0] += 1
    by_type[st][1] += c
    a = (r.get("Acct #") or "").strip()
    accts[a] = accts.get(a, 0) + 1

print(f"rows: {len(fm)}   unparseable amounts: {bad}")
print(f"deposit accounts seen: {accts}")
total = 0
for st, (n, c) in sorted(by_type.items(), key=lambda kv: -kv[1][1]):
    print(f"  {st:<14} {n:>5} rows   {fmt(c):>14}")
    total += c
print(f"  {'TOTAL':<14} {len(fm)-bad:>5} rows   {fmt(total):>14}")

settle = by_type.get("Transaction", [0, 0])[1]
surch = by_type.get("Surcharge", [0, 0])[1]
if settle and surch:
    print()
    print(f"  Reimbursement of vault cash (Transaction): {fmt(settle)}")
    print(f"  ATM's OWN revenue (Surcharge):             {fmt(surch)}")
    print(f"  Surcharge as a share of deposits:          {100.0*surch/total:.2f}%")
    print()
    print("  READ THIS: if every dollar deposited into 6228 were treated as ATM")
    print("  revenue, revenue would be overstated by a factor of")
    print(f"  {total/surch:.1f}x  ({fmt(total)} instead of {fmt(surch)}).")

print()
print("=" * 74)
print("2) DAILY SETTLEMENT  --  independent second source for the same split")
print("=" * 74)
ds = rows("ATM Daily Settlement Report 5.1.26-8.23.26.csv")
d_surch = d_settle = 0
d_bad = 0
for r in ds:
    s = money(r.get("Surch"))
    t = money(r.get("Settlement"))
    if s is None or t is None:
        d_bad += 1
        continue
    d_surch += s
    d_settle += t
print(f"rows: {len(ds)}   unparseable: {d_bad}")
print(f"  Surch      total: {fmt(d_surch)}")
print(f"  Settlement total: {fmt(d_settle)}")
print()
print("  CROSS-CHECK against Funds Movement:")
print(f"    surcharge  {fmt(surch)} vs {fmt(d_surch)}  ->  "
      f"{'AGREE' if surch == d_surch else 'DISAGREE by ' + fmt(abs(surch - d_surch))}")
print(f"    settlement {fmt(settle)} vs {fmt(d_settle)}  ->  "
      f"{'AGREE' if settle == d_settle else 'DISAGREE by ' + fmt(abs(settle - d_settle))}")

print()
print("=" * 74)
print("3) CASH LOAD  --  Greenway cannabis cash physically put INTO the machine")
print("=" * 74)
cl = rows("ATM Cash Load Report-5.1.26-8.23.26.csv")
load = 0
l_bad = 0
terms = set()
for r in cl:
    c = money(r.get("Cash Load"))
    if c is None:
        l_bad += 1
        continue
    load += c
    terms.add((r.get("Terminal Number") or "").strip())
print(f"rows: {len(cl)}   unparseable: {l_bad}")
print(f"terminals: {sorted(terms)}")
print(f"  TOTAL CASH LOADED: {fmt(load)}")
print()
print("  This is Greenway's cannabis cash leaving Greenway and entering the ATM.")
print("  It is the OTHER LEG of the settlement deposits measured in (1).")

print()
print("=" * 74)
print("4) THE BANK ACCOUNT  --  6228 activity, and the 6228->6048 sweep")
print("=" * 74)
tb = rows("Timberland Bank ATM Account 5.1.26-8.23.26.csv")
sweep_n = sweep_c = 0
other_d = other_c = 0
cred_n = cred_c = 0
descs = {}
t_bad = 0
for r in tb:
    c = money(r.get("Amount"))
    cd = (r.get("Credit or Debit") or "").strip()
    d = (r.get("Description") or "").strip()
    if c is None:
        t_bad += 1
        continue
    key = d.upper()
    descs.setdefault(key, [0, 0, cd])
    descs[key][0] += 1
    descs[key][1] += c
    if "X6228 TO X6048" in key or ("TRANSFER" in key and "6048" in key):
        sweep_n += 1
        sweep_c += c
    elif cd == "Credit":
        cred_n += 1
        cred_c += c
    else:
        other_d += 1
        other_c += c

print(f"rows: {len(tb)}   unparseable: {t_bad}")
print(f"  6228 -> 6048 SWEEPS:      {sweep_n:>4} rows   {fmt(sweep_c):>14}")
print(f"  credits INTO 6228:        {cred_n:>4} rows   {fmt(cred_c):>14}")
print(f"  other debits OUT of 6228: {other_d:>4} rows   {fmt(other_c):>14}")
print()
print("  Distinct descriptions (top 12 by count):")
for k, (n, c, cd) in sorted(descs.items(), key=lambda kv: -kv[1][0])[:12]:
    print(f"    {n:>4}x {cd:<7} {fmt(c):>13}  {k[:46]}")

if sweep_c and cred_c:
    print()
    print(f"  Swept OUT to Greenway's operating account: {fmt(sweep_c)}")
    print(f"  Deposited IN by the ATM network:           {fmt(cred_c)}")
    print(f"  Swept as a share of deposits:              {100.0*sweep_c/cred_c:.1f}%")
    print()
    print("  If the sweep were booked as a distribution/contribution rather than")
    print("  as the return of Greenway's own vault cash, it would misstate the")
    print(f"  equity accounts by up to {fmt(sweep_c)} over ~4 months.")

print()
print("=" * 74)
print("5) WHAT THIS MEANS FOR THE LEDGER  (stated, not decided)")
print("=" * 74)
print("""
Three flows exist in 6228 and they are NOT the same animal:

  (a) SETTLEMENT of withdrawals  -- reimbursement of vault cash that came from
      Greenway. Michael: "the money is simply in the atm businesses custody."
      Not ATM revenue. Not equity. A CUSTODY / CLEARING balance.

  (b) SURCHARGE                  -- genuinely the ATM's own revenue.
      Michael: "that revenue belongs to the atm."

  (c) SWEEPS and cross-entity payments -- Michael: "no, I do not expect it to
      be repaid... when one account needs cash, I move it there."
      Not a loan. This is the flow D-41 was asking about.

Booking (a) as revenue or as equity is the error this measurement exists to
prevent, and the numbers above size it.
""")
