-- 0047_receipt_printing.sql
-- Slice 37 — Receipt printer alerting via Star CloudPRNT (single-printer design).
--
-- Hardware decision (committed, single model only — no multi-printer abstraction):
--   Star Micronics TSP143IV (TSP100IV) Ethernet + USB-C, CloudPRNT firmware.
--   The printer polls our self-hosted CloudPRNT endpoint over HTTP (no PC, no SaaS).
--
-- Two objects:
--   1. receipt_printer_settings — a singleton row holding the one printer's config
--      (poll token for authenticating the printer, the registered MAC, whether
--      auto-print on new online orders is enabled, paper width, header/footer text).
--   2. receipt_print_jobs — a queue of receipts to print. The CloudPRNT route
--      handler claims the oldest queued job on poll, serves its body on GET, and
--      marks it printed on the DELETE confirmation.
--
-- Idempotent: safe to re-run. Money stays in MINOR UNITS elsewhere; no money here.

-- ---------------------------------------------------------------------------
-- Job status enum
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'receipt_job_status') then
    create type public.receipt_job_status as enum (
      'queued',     -- waiting for the printer to poll
      'printing',   -- claimed by the printer (GET issued), awaiting confirmation
      'printed',    -- confirmed printed (DELETE/GET confirmation received)
      'failed',     -- printer reported an error status while this was active
      'cancelled'   -- staff cancelled before it printed
    );
  end if;
end$$;

-- ---------------------------------------------------------------------------
-- Singleton settings table (one printer)
-- ---------------------------------------------------------------------------
create table if not exists public.receipt_printer_settings (
  id                 smallint primary key default 1,
  -- shared secret the printer sends as Basic-auth password (or query token) so
  -- only our registered printer can poll/claim jobs. Generated by staff in UI.
  poll_token         text,
  -- the printer's MAC address, captured from the first authenticated poll, shown
  -- in the UI so staff can confirm the right device is connected.
  printer_mac        text,
  -- human label for the device (e.g. "Front counter TSP143IV").
  printer_label      text not null default 'Front counter receipt printer',
  -- master switch: queue a receipt automatically when a new online order arrives.
  auto_print_orders  boolean not null default true,
  -- paper width in dots-safe character columns: TSP143IV 80mm = 48, 58mm = 32.
  paper_columns      smallint not null default 48,
  -- optional receipt header/footer lines (store name, address, thank-you note).
  header_text        text,
  footer_text        text,
  -- last time the printer successfully polled (heartbeat) + last decoded status.
  last_poll_at       timestamptz,
  last_status_code   text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint receipt_printer_settings_singleton check (id = 1)
);

-- Seed the singleton row if absent.
insert into public.receipt_printer_settings (id)
values (1)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Print job queue
-- ---------------------------------------------------------------------------
create table if not exists public.receipt_print_jobs (
  id            uuid primary key default gen_random_uuid(),
  -- optional link back to the order that generated this receipt.
  order_id      uuid references public.orders (id) on delete set null,
  order_number  text,
  -- what to print, already rendered to plain text (text/plain media type).
  body_text     text not null,
  -- short label for the staff queue view (e.g. "Order GW-1042 — 3 items").
  title         text,
  status        public.receipt_job_status not null default 'queued',
  -- CloudPRNT jobToken handed to the printer so GET/DELETE map to this row.
  job_token     text,
  attempts      smallint not null default 0,
  error_note    text,
  queued_at     timestamptz not null default now(),
  claimed_at    timestamptz,
  printed_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists receipt_print_jobs_status_idx
  on public.receipt_print_jobs (status, queued_at);
create index if not exists receipt_print_jobs_order_idx
  on public.receipt_print_jobs (order_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers (reuse shared helper public.set_updated_at)
-- ---------------------------------------------------------------------------
drop trigger if exists set_updated_at_receipt_printer_settings on public.receipt_printer_settings;
create trigger set_updated_at_receipt_printer_settings
  before update on public.receipt_printer_settings
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at_receipt_print_jobs on public.receipt_print_jobs;
create trigger set_updated_at_receipt_print_jobs
  before update on public.receipt_print_jobs
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS — staff-only via shared helpers. The CloudPRNT route uses the service
-- role (bypasses RLS) because the printer authenticates with the poll_token,
-- not a Supabase session.
-- ---------------------------------------------------------------------------
alter table public.receipt_printer_settings enable row level security;
alter table public.receipt_print_jobs       enable row level security;

drop policy if exists receipt_printer_settings_read on public.receipt_printer_settings;
create policy receipt_printer_settings_read
  on public.receipt_printer_settings for select
  using (public.is_staff());

drop policy if exists receipt_printer_settings_write on public.receipt_printer_settings;
create policy receipt_printer_settings_write
  on public.receipt_printer_settings for all
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists receipt_print_jobs_read on public.receipt_print_jobs;
create policy receipt_print_jobs_read
  on public.receipt_print_jobs for select
  using (public.is_staff());

drop policy if exists receipt_print_jobs_write on public.receipt_print_jobs;
create policy receipt_print_jobs_write
  on public.receipt_print_jobs for all
  using (public.is_staff())
  with check (public.is_staff());
