/**
 * src/lib/pos/device-setup-core.ts  (POS Slice B25)
 *
 * PURE helpers for the one-time register setup screen. No React, no DB.
 *
 * Why this exists (verified failure in the field): during first provisioning
 * the owner pasted the DEVICE KEY into the id field and the DEVICE ID (a
 * UUID) into the key field. The server's authenticateDevice checks
 * isUuid(deviceId) and correctly refused with "Missing or malformed device
 * credentials." — but the register gave no hint WHY. The two credentials
 * have unmistakable shapes:
 *
 *   - device id : UUID (pos_devices.id, generated by Postgres), and
 *   - device key: 32-char base64url string (randomBytes(24) in
 *     provisionDevice — base64url of 24 bytes is exactly 32 chars, and a
 *     UUID can never look like one because of its dashes).
 *
 * So the setup screen can DETECT a swap with certainty and fix it, and can
 * explain a malformed id before burning a network round-trip.
 */

/** RFC-4122-shaped UUID (any version) — mirrors sale-event-core's isUuid. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isUuidShaped(v: string): boolean {
  return UUID_RE.test(v);
}

export type SetupCredentialsCheck = {
  /** Cleaned values, in the CORRECT slots (swapped back when detected). */
  deviceId: string;
  deviceKey: string;
  /** True when the two values were pasted into each other's fields. */
  swapped: boolean;
  /** Null = shape looks right, submit away. Otherwise a human explanation. */
  problem: string | null;
};

/**
 * Clean + shape-check the setup credentials BEFORE the network call.
 * Trims whitespace (iPad paste loves trailing newlines) and strips inner
 * whitespace/zero-width characters that ride along with copied text.
 */
export function checkSetupCredentials(idRaw: string, keyRaw: string): SetupCredentialsCheck {
  const clean = (s: string) => s.replace(/[\s\u200b\u200c\u200d\ufeff]/g, "");
  let deviceId = clean(idRaw);
  let deviceKey = clean(keyRaw);
  let swapped = false;

  // The unmistakable swap: the KEY field holds the UUID and the id field
  // holds something that is NOT a UUID. Fix silently-but-loudly (the UI
  // tells the manager what happened).
  if (!isUuidShaped(deviceId) && isUuidShaped(deviceKey)) {
    const tmp = deviceId;
    deviceId = deviceKey;
    deviceKey = tmp;
    swapped = true;
  }

  if (!deviceId || !deviceKey) {
    return { deviceId, deviceKey, swapped, problem: "Enter both the device id and the device key." };
  }
  if (!isUuidShaped(deviceId)) {
    return {
      deviceId,
      deviceKey,
      swapped,
      problem:
        "The device id should be a UUID (eight-four-four-four-twelve hex characters with dashes) — copy it from Admin → Registers → POS devices.",
    };
  }
  if (isUuidShaped(deviceKey)) {
    return {
      deviceId,
      deviceKey,
      swapped,
      problem:
        "Both fields contain a UUID — the device key is the long random string shown ONCE when the device was provisioned. If it was lost, rotate the key in Admin → Registers → POS devices.",
    };
  }
  if (deviceKey.length < 16) {
    return {
      deviceId,
      deviceKey,
      swapped,
      problem: "That device key looks too short — copy the full one-time key (32 characters).",
    };
  }
  return { deviceId, deviceKey, swapped, problem: null };
}

// ---------------------------------------------------------------------------
// Embedded self-tests
// ---------------------------------------------------------------------------

export function __runDeviceSetupCoreTests(): void {
  let pass = 0;
  let fail = 0;
  const ok = (cond: boolean, msg: string) => {
    if (cond) pass += 1;
    else { fail += 1; console.log("FAIL:", msg); }
  };

  const ID = "59768c42-aa8c-4dab-8e6e-a2e766fe16b0";
  const KEY = "RJH5doEHCd78c2fneJmS7vgKGb1TXWiA"; // 32-char base64url shape

  // Correct input passes untouched.
  const good = checkSetupCredentials(ID, KEY);
  ok(good.problem === null && !good.swapped, "correct id+key accepted");
  ok(good.deviceId === ID && good.deviceKey === KEY, "correct values untouched");

  // The field swap that hit the owner: detected and corrected.
  const swap = checkSetupCredentials(KEY, ID);
  ok(swap.swapped, "swapped fields detected");
  ok(swap.deviceId === ID && swap.deviceKey === KEY, "swap corrected into the right slots");
  ok(swap.problem === null, "corrected swap is submittable");

  // Whitespace + trailing newline from an iPad paste is cleaned.
  const pasted = checkSetupCredentials(`  ${ID}\n`, `${KEY} \n`);
  ok(pasted.problem === null && pasted.deviceId === ID && pasted.deviceKey === KEY, "pasted whitespace cleaned");

  // Zero-width characters riding a copy are stripped.
  const zw = checkSetupCredentials(`${ID}\u200b`, `\ufeff${KEY}`);
  ok(zw.problem === null && zw.deviceId === ID, "zero-width characters stripped");

  // Uppercase UUID accepted (RFC 4122 is case-insensitive).
  ok(checkSetupCredentials(ID.toUpperCase(), KEY).problem === null, "uppercase uuid accepted");

  // Missing values named clearly.
  ok(checkSetupCredentials("", KEY).problem !== null, "empty id refused");
  ok(checkSetupCredentials(ID, "").problem !== null, "empty key refused");

  // A non-uuid id with a non-uuid key = clear guidance, no swap.
  const badId = checkSetupCredentials("register-1", KEY);
  ok(!badId.swapped && (badId.problem ?? "").includes("UUID"), "non-uuid id explained, not swapped");

  // Two UUIDs = the key was never the key; point at rotation.
  const twoIds = checkSetupCredentials(ID, "11111111-1111-4111-8111-111111111111");
  ok((twoIds.problem ?? "").includes("rotate"), "uuid-in-key-field points at key rotation");

  // A too-short key is caught before the network call.
  ok((checkSetupCredentials(ID, "shortkey").problem ?? "").includes("too short"), "short key caught");

  if (fail > 0) throw new Error(`device-setup-core self-tests: ${fail} FAILED (${pass} passed)`);
  console.log(`device-setup-core self-tests: ALL PASS (${pass} assertions)`);
}
