/**
 * src/lib/pos/device-setup-core.ts  (POS Slice B25)
 *
 * PURE helpers for the one-time register setup screen. No React, no DB.
 *
 * Why this exists (verified failure in the field): during first provisioning
 * the owner pasted the DEVICE KEY into the id field and the DEVICE ID (a
 * UUID) into the key field. The server's authenticateDevice checks
 * isUuid(deviceId) and correctly refused with "Missing or malformed device
 * credentials." — but the register gave no hint WHY. The two credentials
 * have unmistakable shapes:
 *
 *   - device id : UUID (pos_devices.id, generated by Postgres), and
 *   - device key: 32-char base64url string (randomBytes(24) in
 *     provisionDevice — base64url of 24 bytes is exactly 32 chars, and a
 *     UUID can never look like one because of its dashes).
 *
 * So the setup screen can DETECT a swap with certainty and fix it, and can
 * explain a malformed id before burning a network round-trip.
 *
 * B26 (verified second failure in the field): with the id correct, the
 * server answered "Device key rejected." even after a key rotation. The key
 * is TYPED on the iPad and is case-sensitive base64url; the setup inputs
 * lacked autoCapitalize="none"/autoCorrect="off", so iOS silently mangles a
 * typed key (first-letter capitalization, autocorrect, smart dashes). This
 * module now also normalizes typographic dashes to ASCII hyphens and
 * verifies the key's exact shape (32 chars, base64url alphabet — both
 * minting sites, provisionDevice and rotateDeviceKey, use
 * randomBytes(24).toString("base64url") which is always exactly 32 chars)
 * so a keyboard-mangled key is explained BEFORE the network call.
 */

/** RFC-4122-shaped UUID (any version) — mirrors sale-event-core's isUuid. */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isUuidShaped(v: string): boolean {
  return UUID_RE.test(v);
}

/**
 * The exact shape of every device key ever minted: base64url of 24 random
 * bytes = exactly 32 chars from [A-Za-z0-9_-]. (Both minting sites —
 * provisionDevice and rotateDeviceKey in device-store.ts — use
 * randomBytes(24).toString("base64url").)
 */
const KEY_RE = /^[A-Za-z0-9_-]{32}$/;

function isKeyShaped(v: string): boolean {
  return KEY_RE.test(v);
}

export type SetupCredentialsCheck = {
  /** Cleaned values, in the CORRECT slots (swapped back when detected). */
  deviceId: string;
  deviceKey: string;
  /** True when the two values were pasted into each other's fields. */
  swapped: boolean;
  /** Null = shape looks right, submit away. Otherwise a human explanation. */
  problem: string | null;
};

/**
 * Clean + shape-check the setup credentials BEFORE the network call.
 * Trims whitespace (iPad paste loves trailing newlines) and strips inner
 * whitespace/zero-width characters that ride along with copied text.
 */
export function checkSetupCredentials(idRaw: string, keyRaw: string): SetupCredentialsCheck {
  // Strip whitespace/zero-width paste artifacts, and normalize the smart
  // dashes iOS substitutes for typed hyphens (en dash, em dash, minus,
  // figure dash, non-breaking hyphen) back to ASCII "-": UUIDs use hyphens
  // and base64url keys may legitimately contain "-".
  const clean = (s: string) =>
    s.replace(/[\s\u200b\u200c\u200d\ufeff]/g, "").replace(/[\u2010\u2011\u2012\u2013\u2014\u2212]/g, "-");
  let deviceId = clean(idRaw);
  let deviceKey = clean(keyRaw);
  let swapped = false;

  // The unmistakable swap: the KEY field holds the UUID and the id field
  // holds something that is NOT a UUID. Fix silently-but-loudly (the UI
  // tells the manager what happened).
  if (!isUuidShaped(deviceId) && isUuidShaped(deviceKey)) {
    const tmp = deviceId;
    deviceId = deviceKey;
    deviceKey = tmp;
    swapped = true;
  }

  if (!deviceId || !deviceKey) {
    return { deviceId, deviceKey, swapped, problem: "Enter both the device id and the device key." };
  }
  if (!isUuidShaped(deviceId)) {
    return {
      deviceId,
      deviceKey,
      swapped,
      problem:
        "The device id should be a UUID (eight-four-four-four-twelve hex characters with dashes) — copy it from Admin → Registers → POS devices.",
    };
  }
  if (isUuidShaped(deviceKey)) {
    return {
      deviceId,
      deviceKey,
      swapped,
      problem:
        "Both fields contain a UUID — the device key is the long random string shown ONCE when the device was provisioned. If it was lost, rotate the key in Admin → Registers → POS devices.",
    };
  }
  if (deviceKey.length < 16) {
    return {
      deviceId,
      deviceKey,
      swapped,
      problem: "That device key looks too short — copy the full one-time key (32 characters).",
    };
  }
  if (!isKeyShaped(deviceKey)) {
    // Every key ever minted is exactly 32 base64url chars. A wrong length or
    // an out-of-alphabet character means the key was mangled in transit —
    // on an iPad this is usually autocorrect/auto-capitalize rewriting a
    // TYPED key. The server would answer "Device key rejected."; explain
    // the real cause here instead.
    const badChar = deviceKey.match(/[^A-Za-z0-9_-]/)?.[0];
    const detail =
      deviceKey.length !== 32
        ? `it has ${deviceKey.length} characters instead of 32`
        : `it contains "${badChar ?? "?"}", which never appears in a key`;
    return {
      deviceId,
      deviceKey,
      swapped,
      problem:
        `That device key doesn't match the shape of a real key (${detail}). ` +
        "Keys are exactly 32 letters/digits/dashes/underscores and are CASE-SENSITIVE. " +
        "If you typed it, the iPad keyboard may have auto-capitalized or auto-corrected it — " +
        "retype it carefully or paste it, and compare character by character with the key shown in " +
        "Admin → Registers → POS devices (rotate the key there to get a fresh one you can copy).",
    };
  }
  return { deviceId, deviceKey, swapped, problem: null };
}

// ---------------------------------------------------------------------------
// Embedded self-tests
// ---------------------------------------------------------------------------

export function __runDeviceSetupCoreTests(): void {
  let pass = 0;
  let fail = 0;
  const ok = (cond: boolean, msg: string) => {
    if (cond) pass += 1;
    else { fail += 1; console.log("FAIL:", msg); }
  };

  const ID = "59768c42-aa8c-4dab-8e6e-a2e766fe16b0";
  const KEY = "RJH5doEHCd78c2fneJmS7vgKGb1TXWiA"; // 32-char base64url shape

  // Correct input passes untouched.
  const good = checkSetupCredentials(ID, KEY);
  ok(good.problem === null && !good.swapped, "correct id+key accepted");
  ok(good.deviceId === ID && good.deviceKey === KEY, "correct values untouched");

  // The field swap that hit the owner: detected and corrected.
  const swap = checkSetupCredentials(KEY, ID);
  ok(swap.swapped, "swapped fields detected");
  ok(swap.deviceId === ID && swap.deviceKey === KEY, "swap corrected into the right slots");
  ok(swap.problem === null, "corrected swap is submittable");

  // Whitespace + trailing newline from an iPad paste is cleaned.
  const pasted = checkSetupCredentials(`  ${ID}\n`, `${KEY} \n`);
  ok(pasted.problem === null && pasted.deviceId === ID && pasted.deviceKey === KEY, "pasted whitespace cleaned");

  // Zero-width characters riding a copy are stripped.
  const zw = checkSetupCredentials(`${ID}\u200b`, `\ufeff${KEY}`);
  ok(zw.problem === null && zw.deviceId === ID, "zero-width characters stripped");

  // Uppercase UUID accepted (RFC 4122 is case-insensitive).
  ok(checkSetupCredentials(ID.toUpperCase(), KEY).problem === null, "uppercase uuid accepted");

  // Missing values named clearly.
  ok(checkSetupCredentials("", KEY).problem !== null, "empty id refused");
  ok(checkSetupCredentials(ID, "").problem !== null, "empty key refused");

  // A non-uuid id with a non-uuid key = clear guidance, no swap.
  const badId = checkSetupCredentials("register-1", KEY);
  ok(!badId.swapped && (badId.problem ?? "").includes("UUID"), "non-uuid id explained, not swapped");

  // Two UUIDs = the key was never the key; point at rotation.
  const twoIds = checkSetupCredentials(ID, "11111111-1111-4111-8111-111111111111");
  ok((twoIds.problem ?? "").includes("rotate"), "uuid-in-key-field points at key rotation");

  // A too-short key is caught before the network call.
  ok((checkSetupCredentials(ID, "shortkey").problem ?? "").includes("too short"), "short key caught");

  // --- B26: key-shape integrity (the "Device key rejected." field failure) ---

  // A key with a stray character (e.g. autocorrect inserted a period) is
  // explained, naming the bad character.
  const badChar = checkSetupCredentials(ID, "RJH5doEHCd78c2fneJmS7vgKGb1TXWi.");
  ok((badChar.problem ?? "").includes('"."'), "out-of-alphabet char named");
  ok((badChar.problem ?? "").includes("CASE-SENSITIVE"), "case sensitivity called out");

  // A 31- or 33-char key (missed/extra character) is explained with the count.
  ok((checkSetupCredentials(ID, KEY.slice(0, 31)).problem ?? "").includes("31 characters"), "31-char key counted");
  ok((checkSetupCredentials(ID, `${KEY}X`).problem ?? "").includes("33 characters"), "33-char key counted");

  // iOS smart-dash substitution in either field is normalized back to "-".
  const enDashId = ID.replace(/-/g, "\u2013");
  ok(checkSetupCredentials(enDashId, KEY).problem === null, "en-dash uuid normalized");
  const KEY_WITH_DASH = "RJH5doEHCd78c2fneJmS7vgKGb1TXW-A"; // 32 chars, one hyphen
  ok(
    checkSetupCredentials(ID, KEY_WITH_DASH.replace("-", "\u2014")).problem === null,
    "em-dash in key normalized",
  );

  // Keys with base64url specials (- and _) pass untouched.
  ok(checkSetupCredentials(ID, "A-b_C-d_E-f_G-h_I-j_K-l_M-n_O-p_").problem === null, "base64url specials accepted");

  // A well-formed 32-char key still passes (regression guard).
  ok(checkSetupCredentials(ID, KEY).problem === null, "canonical key still accepted");

  if (fail > 0) throw new Error(`device-setup-core self-tests: ${fail} FAILED (${pass} passed)`);
  console.log(`device-setup-core self-tests: ALL PASS (${pass} assertions)`);
}
